/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -o jo_02_t.c -f jo_02_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t johab_encoding;
