/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -O -o ebcdic_t.c -f ebcdic_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t cp1026_encoding;
extern encode_t cp1047_encoding;
extern encode_t cp37_encoding;
extern encode_t cp500_encoding;
extern encode_t cp875_encoding;
extern encode_t posix_bc_encoding;
