/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -o gb_03_t.c -f gb_03_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t gb2312_raw_encoding;
