/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -o ir_04_t.c -f ir_04_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t iso_ir_165_encoding;
