/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -o eu_01_t.c -f eu_01_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t euc_jp_encoding;
