.section .rdata,"dr"
.globl __imp__CallMsgFilterA@8
__imp__CallMsgFilterA@8:
  .long _CallMsgFilterA@8
.globl __imp__CloseHandle@4
__imp__CloseHandle@4:
  .long _CloseHandle@4
.globl __imp__CreateFileA@28
__imp__CreateFileA@28:
  .long _CreateFileA@28
.globl __imp__CreateHardLinkW@12
__imp__CreateHardLinkW@12:
  .long _CreateHardLinkW@12
.globl __imp__CreateProcessA@40
__imp__CreateProcessA@40:
  .long _CreateProcessA@40
.globl __imp__CreateWindowExA@48
__imp__CreateWindowExA@48:
  .long _CreateWindowExA@48
.globl __imp__DefWindowProcA@16
__imp__DefWindowProcA@16:
  .long _DefWindowProcA@16
.globl __imp__DestroyWindow@4
__imp__DestroyWindow@4:
  .long _DestroyWindow@4
.globl __imp__DeviceIoControl@32
__imp__DeviceIoControl@32:
  .long _DeviceIoControl@32
.globl __imp__DispatchMessageA@4
__imp__DispatchMessageA@4:
  .long _DispatchMessageA@4
.globl __imp__FileTimeToSystemTime@8
__imp__FileTimeToSystemTime@8:
  .long _FileTimeToSystemTime@8
.globl __imp__FindClose@4
__imp__FindClose@4:
  .long _FindClose@4
.globl __imp__FindFirstFileA@8
__imp__FindFirstFileA@8:
  .long _FindFirstFileA@8
.globl __imp__FormatMessageA@28
__imp__FormatMessageA@28:
  .long _FormatMessageA@28
.globl __imp__FreeEnvironmentStringsA@4
__imp__FreeEnvironmentStringsA@4:
  .long _FreeEnvironmentStringsA@4
.globl __imp__FreeEnvironmentStringsW@4
__imp__FreeEnvironmentStringsW@4:
  .long _FreeEnvironmentStringsW@4
.globl __imp__FreeLibrary@4
__imp__FreeLibrary@4:
  .long _FreeLibrary@4
.globl __imp__GenerateConsoleCtrlEvent@8
__imp__GenerateConsoleCtrlEvent@8:
  .long _GenerateConsoleCtrlEvent@8
.globl __imp__GetComputerNameA@8
__imp__GetComputerNameA@8:
  .long _GetComputerNameA@8
.globl __imp__GetConsoleCP@0
__imp__GetConsoleCP@0:
  .long _GetConsoleCP@0
.globl __imp__GetConsoleMode@8
__imp__GetConsoleMode@8:
  .long _GetConsoleMode@8
.globl __imp__GetCurrentDirectoryA@8
__imp__GetCurrentDirectoryA@8:
  .long _GetCurrentDirectoryA@8
.globl __imp__GetCurrentProcess@0
__imp__GetCurrentProcess@0:
  .long _GetCurrentProcess@0
.globl __imp__GetEnvironmentStrings@0
__imp__GetEnvironmentStrings@0:
  .long _GetEnvironmentStrings@0
.globl __imp__GetEnvironmentStringsW@0
__imp__GetEnvironmentStringsW@0:
  .long _GetEnvironmentStringsW@0
.globl __imp__GetEnvironmentVariableA@12
__imp__GetEnvironmentVariableA@12:
  .long _GetEnvironmentVariableA@12
.globl __imp__GetEnvironmentVariableW@12
__imp__GetEnvironmentVariableW@12:
  .long _GetEnvironmentVariableW@12
.globl __imp__GetExitCodeProcess@8
__imp__GetExitCodeProcess@8:
  .long _GetExitCodeProcess@8
.globl __imp__GetFileAttributesA@4
__imp__GetFileAttributesA@4:
  .long _GetFileAttributesA@4
.globl __imp__GetFileInformationByHandle@8
__imp__GetFileInformationByHandle@8:
  .long _GetFileInformationByHandle@8
.globl __imp__GetFileType@4
__imp__GetFileType@4:
  .long _GetFileType@4
.globl __imp__GetFullPathNameW@16
__imp__GetFullPathNameW@16:
  .long _GetFullPathNameW@16
.globl __imp__GetLastError@0
__imp__GetLastError@0:
  .long _GetLastError@0
.globl __imp__GetModuleFileNameW@12
__imp__GetModuleFileNameW@12:
  .long _GetModuleFileNameW@12
.globl __imp__GetModuleHandleA@4
__imp__GetModuleHandleA@4:
  .long _GetModuleHandleA@4
.globl __imp__GetModuleHandleExA@12
__imp__GetModuleHandleExA@12:
  .long _GetModuleHandleExA@12
.globl __imp__GetProcAddress@8
__imp__GetProcAddress@8:
  .long _GetProcAddress@8
.globl __imp__GetProcessTimes@20
__imp__GetProcessTimes@20:
  .long _GetProcessTimes@20
.globl __imp__GetShortPathNameW@12
__imp__GetShortPathNameW@12:
  .long _GetShortPathNameW@12
.globl __imp__GetStdHandle@4
__imp__GetStdHandle@4:
  .long _GetStdHandle@4
.globl __imp__GetSystemDirectoryA@8
__imp__GetSystemDirectoryA@8:
  .long _GetSystemDirectoryA@8
.globl __imp__GetSystemInfo@4
__imp__GetSystemInfo@4:
  .long _GetSystemInfo@4
.globl __imp__GetSystemTimeAsFileTime@4
__imp__GetSystemTimeAsFileTime@4:
  .long _GetSystemTimeAsFileTime@4
.globl __imp__GetTempFileNameA@16
__imp__GetTempFileNameA@16:
  .long _GetTempFileNameA@16
.globl __imp__GetTempPathA@8
__imp__GetTempPathA@8:
  .long _GetTempPathA@8
.globl __imp__GetUserNameA@8
__imp__GetUserNameA@8:
  .long _GetUserNameA@8
.globl __imp__GetVersionExA@4
__imp__GetVersionExA@4:
  .long _GetVersionExA@4
.globl __imp__InitCommonControls@0
__imp__InitCommonControls@0:
  .long _InitCommonControls@0
.globl __imp__KillTimer@8
__imp__KillTimer@8:
  .long _KillTimer@8
.globl __imp__LoadLibraryExA@12
__imp__LoadLibraryExA@12:
  .long _LoadLibraryExA@12
.globl __imp__LocalAlloc@8
__imp__LocalAlloc@8:
  .long _LocalAlloc@8
.globl __imp__LocalFree@4
__imp__LocalFree@4:
  .long _LocalFree@4
.globl __imp__LockFileEx@24
__imp__LockFileEx@24:
  .long _LockFileEx@24
.globl __imp__MoveFileExA@12
__imp__MoveFileExA@12:
  .long _MoveFileExA@12
.globl __imp__MsgWaitForMultipleObjects@20
__imp__MsgWaitForMultipleObjects@20:
  .long _MsgWaitForMultipleObjects@20
.globl __imp__MultiByteToWideChar@24
__imp__MultiByteToWideChar@24:
  .long _MultiByteToWideChar@24
.globl __imp__OpenProcess@12
__imp__OpenProcess@12:
  .long _OpenProcess@12
.globl __imp__PeekMessageA@20
__imp__PeekMessageA@20:
  .long _PeekMessageA@20
.globl __imp__Perl_init_os_extras
__imp__Perl_init_os_extras:
  .long _Perl_init_os_extras
.globl __imp__Perl_win32_init
__imp__Perl_win32_init:
  .long _Perl_win32_init
.globl __imp__Perl_win32_term
__imp__Perl_win32_term:
  .long _Perl_win32_term
.globl __imp__PostQuitMessage@4
__imp__PostQuitMessage@4:
  .long _PostQuitMessage@4
.globl __imp__ReadConsoleW@20
__imp__ReadConsoleW@20:
  .long _ReadConsoleW@20
.globl __imp__RegCloseKey@4
__imp__RegCloseKey@4:
  .long _RegCloseKey@4
.globl __imp__RegOpenKeyExW@20
__imp__RegOpenKeyExW@20:
  .long _RegOpenKeyExW@20
.globl __imp__RegQueryValueExA@24
__imp__RegQueryValueExA@24:
  .long _RegQueryValueExA@24
.globl __imp__RegisterClassA@4
__imp__RegisterClassA@4:
  .long _RegisterClassA@4
.globl __imp__SetConsoleCtrlHandler@8
__imp__SetConsoleCtrlHandler@8:
  .long _SetConsoleCtrlHandler@8
.globl __imp__SetEndOfFile@4
__imp__SetEndOfFile@4:
  .long _SetEndOfFile@4
.globl __imp__SetEnvironmentVariableA@8
__imp__SetEnvironmentVariableA@8:
  .long _SetEnvironmentVariableA@8
.globl __imp__SetFileAttributesA@8
__imp__SetFileAttributesA@8:
  .long _SetFileAttributesA@8
.globl __imp__SetFileTime@16
__imp__SetFileTime@16:
  .long _SetFileTime@16
.globl __imp__SetHandleInformation@12
__imp__SetHandleInformation@12:
  .long _SetHandleInformation@12
.globl __imp__SetLastError@4
__imp__SetLastError@4:
  .long _SetLastError@4
.globl __imp__SetTimer@16
__imp__SetTimer@16:
  .long _SetTimer@16
.globl __imp__Sleep@4
__imp__Sleep@4:
  .long _Sleep@4
.globl __imp__SystemTimeToFileTime@8
__imp__SystemTimeToFileTime@8:
  .long _SystemTimeToFileTime@8
.globl __imp__TerminateProcess@8
__imp__TerminateProcess@8:
  .long _TerminateProcess@8
.globl __imp__TranslateMessage@4
__imp__TranslateMessage@4:
  .long _TranslateMessage@4
.globl __imp__UnlockFileEx@20
__imp__UnlockFileEx@20:
  .long _UnlockFileEx@20
.globl __imp__VirtualProtect@16
__imp__VirtualProtect@16:
  .long _VirtualProtect@16
.globl __imp__WSACleanup@0
__imp__WSACleanup@0:
  .long _WSACleanup@0
.globl __imp__WSAGetLastError@0
__imp__WSAGetLastError@0:
  .long _WSAGetLastError@0
.globl __imp__WSASetLastError@4
__imp__WSASetLastError@4:
  .long _WSASetLastError@4
.globl __imp__WSASocketA@24
__imp__WSASocketA@24:
  .long _WSASocketA@24
.globl __imp__WSAStartup@8
__imp__WSAStartup@8:
  .long _WSAStartup@8
.globl __imp__WideCharToMultiByte@32
__imp__WideCharToMultiByte@32:
  .long _WideCharToMultiByte@32
.globl __imp____mb_cur_max
__imp____mb_cur_max:
  .long ___mb_cur_max
.globl __imp___close
__imp___close:
  .long __close
.globl __imp___environ
__imp___environ:
  .long __environ
.globl __imp___errno
__imp___errno:
  .long __errno
.globl __imp___execv
__imp___execv:
  .long __execv
.globl __imp___execvp
__imp___execvp:
  .long __execvp
.globl __imp___fcloseall
__imp___fcloseall:
  .long __fcloseall
.globl __imp___flushall
__imp___flushall:
  .long __flushall
.globl __imp___fmode
__imp___fmode:
  .long __fmode
.globl __imp___get_osfhandle
__imp___get_osfhandle:
  .long __get_osfhandle
.globl __imp___getpid
__imp___getpid:
  .long __getpid
.globl __imp___iob
__imp___iob:
  .long __iob
.globl __imp___open_osfhandle
__imp___open_osfhandle:
  .long __open_osfhandle
.globl __imp___pipe
__imp___pipe:
  .long __pipe
.globl __imp___stricmp
__imp___stricmp:
  .long __stricmp
.globl __imp___sys_nerr
__imp___sys_nerr:
  .long __sys_nerr
.globl __imp___wcsnicmp
__imp___wcsnicmp:
  .long __wcsnicmp
.globl __imp___wsetlocale
__imp___wsetlocale:
  .long __wsetlocale
.globl __imp__accept@12
__imp__accept@12:
  .long _accept@12
.globl __imp__bind@12
__imp__bind@12:
  .long _bind@12
.globl __imp__closesocket@4
__imp__closesocket@4:
  .long _closesocket@4
.globl __imp__connect@12
__imp__connect@12:
  .long _connect@12
.globl __imp__gethostbyaddr@12
__imp__gethostbyaddr@12:
  .long _gethostbyaddr@12
.globl __imp__gethostbyname@4
__imp__gethostbyname@4:
  .long _gethostbyname@4
.globl __imp__gethostname@8
__imp__gethostname@8:
  .long _gethostname@8
.globl __imp__getpeername@12
__imp__getpeername@12:
  .long _getpeername@12
.globl __imp__getprotobyname@4
__imp__getprotobyname@4:
  .long _getprotobyname@4
.globl __imp__getprotobynumber@4
__imp__getprotobynumber@4:
  .long _getprotobynumber@4
.globl __imp__getservbyname@8
__imp__getservbyname@8:
  .long _getservbyname@8
.globl __imp__getservbyport@8
__imp__getservbyport@8:
  .long _getservbyport@8
.globl __imp__getsockname@12
__imp__getsockname@12:
  .long _getsockname@12
.globl __imp__getsockopt@20
__imp__getsockopt@20:
  .long _getsockopt@20
.globl __imp__inet_addr@4
__imp__inet_addr@4:
  .long _inet_addr@4
.globl __imp__inet_ntoa@4
__imp__inet_ntoa@4:
  .long _inet_ntoa@4
.globl __imp__ioctlsocket@12
__imp__ioctlsocket@12:
  .long _ioctlsocket@12
.globl __imp__isalnum
__imp__isalnum:
  .long _isalnum
.globl __imp__isalpha
__imp__isalpha:
  .long _isalpha
.globl __imp__iscntrl
__imp__iscntrl:
  .long _iscntrl
.globl __imp__isgraph
__imp__isgraph:
  .long _isgraph
.globl __imp__islower
__imp__islower:
  .long _islower
.globl __imp__isprint
__imp__isprint:
  .long _isprint
.globl __imp__ispunct
__imp__ispunct:
  .long _ispunct
.globl __imp__isspace
__imp__isspace:
  .long _isspace
.globl __imp__isupper
__imp__isupper:
  .long _isupper
.globl __imp__isxdigit
__imp__isxdigit:
  .long _isxdigit
.globl __imp__listen@8
__imp__listen@8:
  .long _listen@8
.globl __imp__localeconv
__imp__localeconv:
  .long _localeconv
.globl __imp__recv@16
__imp__recv@16:
  .long _recv@16
.globl __imp__recvfrom@24
__imp__recvfrom@24:
  .long _recvfrom@24
.globl __imp__select@20
__imp__select@20:
  .long _select@20
.globl __imp__send@16
__imp__send@16:
  .long _send@16
.globl __imp__sendto@24
__imp__sendto@24:
  .long _sendto@24
.globl __imp__setsockopt@20
__imp__setsockopt@20:
  .long _setsockopt@20
.globl __imp__shutdown@8
__imp__shutdown@8:
  .long _shutdown@8
.globl __imp__tolower
__imp__tolower:
  .long _tolower
.globl __imp__toupper
__imp__toupper:
  .long _toupper
.globl __imp__win32_abort
__imp__win32_abort:
  .long _win32_abort
.globl __imp__win32_access
__imp__win32_access:
  .long _win32_access
.globl __imp__win32_alarm
__imp__win32_alarm:
  .long _win32_alarm
.globl __imp__win32_ansipath
__imp__win32_ansipath:
  .long _win32_ansipath
.globl __imp__win32_async_check
__imp__win32_async_check:
  .long _win32_async_check
.globl __imp__win32_calloc
__imp__win32_calloc:
  .long _win32_calloc
.globl __imp__win32_chdir
__imp__win32_chdir:
  .long _win32_chdir
.globl __imp__win32_chmod
__imp__win32_chmod:
  .long _win32_chmod
.globl __imp__win32_chsize
__imp__win32_chsize:
  .long _win32_chsize
.globl __imp__win32_clearenv
__imp__win32_clearenv:
  .long _win32_clearenv
.globl __imp__win32_clearerr
__imp__win32_clearerr:
  .long _win32_clearerr
.globl __imp__win32_close
__imp__win32_close:
  .long _win32_close
.globl __imp__win32_closedir
__imp__win32_closedir:
  .long _win32_closedir
.globl __imp__win32_crypt
__imp__win32_crypt:
  .long _win32_crypt
.globl __imp__win32_dup
__imp__win32_dup:
  .long _win32_dup
.globl __imp__win32_dup2
__imp__win32_dup2:
  .long _win32_dup2
.globl __imp__win32_environ
__imp__win32_environ:
  .long _win32_environ
.globl __imp__win32_errno
__imp__win32_errno:
  .long _win32_errno
.globl __imp__win32_execv
__imp__win32_execv:
  .long _win32_execv
.globl __imp__win32_execvp
__imp__win32_execvp:
  .long _win32_execvp
.globl __imp__win32_fclose
__imp__win32_fclose:
  .long _win32_fclose
.globl __imp__win32_fdopen
__imp__win32_fdopen:
  .long _win32_fdopen
.globl __imp__win32_feof
__imp__win32_feof:
  .long _win32_feof
.globl __imp__win32_ferror
__imp__win32_ferror:
  .long _win32_ferror
.globl __imp__win32_fflush
__imp__win32_fflush:
  .long _win32_fflush
.globl __imp__win32_fgetc
__imp__win32_fgetc:
  .long _win32_fgetc
.globl __imp__win32_fileno
__imp__win32_fileno:
  .long _win32_fileno
.globl __imp__win32_flock
__imp__win32_flock:
  .long _win32_flock
.globl __imp__win32_fopen
__imp__win32_fopen:
  .long _win32_fopen
.globl __imp__win32_fread
__imp__win32_fread:
  .long _win32_fread
.globl __imp__win32_free
__imp__win32_free:
  .long _win32_free
.globl __imp__win32_free_childdir
__imp__win32_free_childdir:
  .long _win32_free_childdir
.globl __imp__win32_free_childenv
__imp__win32_free_childenv:
  .long _win32_free_childenv
.globl __imp__win32_freopen
__imp__win32_freopen:
  .long _win32_freopen
.globl __imp__win32_fseek
__imp__win32_fseek:
  .long _win32_fseek
.globl __imp__win32_fstat
__imp__win32_fstat:
  .long _win32_fstat
.globl __imp__win32_ftell
__imp__win32_ftell:
  .long _win32_ftell
.globl __imp__win32_fwrite
__imp__win32_fwrite:
  .long _win32_fwrite
.globl __imp__win32_get_childdir
__imp__win32_get_childdir:
  .long _win32_get_childdir
.globl __imp__win32_get_childenv
__imp__win32_get_childenv:
  .long _win32_get_childenv
.globl __imp__win32_get_osfhandle
__imp__win32_get_osfhandle:
  .long _win32_get_osfhandle
.globl __imp__win32_getenv
__imp__win32_getenv:
  .long _win32_getenv
.globl __imp__win32_getpid
__imp__win32_getpid:
  .long _win32_getpid
.globl __imp__win32_gettimeofday
__imp__win32_gettimeofday:
  .long _win32_gettimeofday
.globl __imp__win32_ioctl
__imp__win32_ioctl:
  .long _win32_ioctl
.globl __imp__win32_isatty
__imp__win32_isatty:
  .long _win32_isatty
.globl __imp__win32_kill
__imp__win32_kill:
  .long _win32_kill
.globl __imp__win32_link
__imp__win32_link:
  .long _win32_link
.globl __imp__win32_lseek
__imp__win32_lseek:
  .long _win32_lseek
.globl __imp__win32_lstat
__imp__win32_lstat:
  .long _win32_lstat
.globl __imp__win32_malloc
__imp__win32_malloc:
  .long _win32_malloc
.globl __imp__win32_mkdir
__imp__win32_mkdir:
  .long _win32_mkdir
.globl __imp__win32_msgwait
__imp__win32_msgwait:
  .long _win32_msgwait
.globl __imp__win32_open
__imp__win32_open:
  .long _win32_open
.globl __imp__win32_open_osfhandle
__imp__win32_open_osfhandle:
  .long _win32_open_osfhandle
.globl __imp__win32_opendir
__imp__win32_opendir:
  .long _win32_opendir
.globl __imp__win32_pause
__imp__win32_pause:
  .long _win32_pause
.globl __imp__win32_pclose
__imp__win32_pclose:
  .long _win32_pclose
.globl __imp__win32_pipe
__imp__win32_pipe:
  .long _win32_pipe
.globl __imp__win32_popen
__imp__win32_popen:
  .long _win32_popen
.globl __imp__win32_popenlist
__imp__win32_popenlist:
  .long _win32_popenlist
.globl __imp__win32_putenv
__imp__win32_putenv:
  .long _win32_putenv
.globl __imp__win32_read
__imp__win32_read:
  .long _win32_read
.globl __imp__win32_readdir
__imp__win32_readdir:
  .long _win32_readdir
.globl __imp__win32_readlink
__imp__win32_readlink:
  .long _win32_readlink
.globl __imp__win32_realloc
__imp__win32_realloc:
  .long _win32_realloc
.globl __imp__win32_rename
__imp__win32_rename:
  .long _win32_rename
.globl __imp__win32_rewinddir
__imp__win32_rewinddir:
  .long _win32_rewinddir
.globl __imp__win32_rmdir
__imp__win32_rmdir:
  .long _win32_rmdir
.globl __imp__win32_seekdir
__imp__win32_seekdir:
  .long _win32_seekdir
.globl __imp__win32_setmode
__imp__win32_setmode:
  .long _win32_setmode
.globl __imp__win32_setvbuf
__imp__win32_setvbuf:
  .long _win32_setvbuf
.globl __imp__win32_signal
__imp__win32_signal:
  .long _win32_signal
.globl __imp__win32_sleep
__imp__win32_sleep:
  .long _win32_sleep
.globl __imp__win32_spawnvp
__imp__win32_spawnvp:
  .long _win32_spawnvp
.globl __imp__win32_stat
__imp__win32_stat:
  .long _win32_stat
.globl __imp__win32_stderr
__imp__win32_stderr:
  .long _win32_stderr
.globl __imp__win32_stdin
__imp__win32_stdin:
  .long _win32_stdin
.globl __imp__win32_stdout
__imp__win32_stdout:
  .long _win32_stdout
.globl __imp__win32_str_os_error
__imp__win32_str_os_error:
  .long _win32_str_os_error
.globl __imp__win32_strerror
__imp__win32_strerror:
  .long _win32_strerror
.globl __imp__win32_symlink
__imp__win32_symlink:
  .long _win32_symlink
.globl __imp__win32_tell
__imp__win32_tell:
  .long _win32_tell
.globl __imp__win32_telldir
__imp__win32_telldir:
  .long _win32_telldir
.globl __imp__win32_times
__imp__win32_times:
  .long _win32_times
.globl __imp__win32_tmpfd
__imp__win32_tmpfd:
  .long _win32_tmpfd
.globl __imp__win32_tmpfd_mode
__imp__win32_tmpfd_mode:
  .long _win32_tmpfd_mode
.globl __imp__win32_ungetc
__imp__win32_ungetc:
  .long _win32_ungetc
.globl __imp__win32_unlink
__imp__win32_unlink:
  .long _win32_unlink
.globl __imp__win32_utime
__imp__win32_utime:
  .long _win32_utime
.globl __imp__win32_vfprintf
__imp__win32_vfprintf:
  .long _win32_vfprintf
.globl __imp__win32_waitpid
__imp__win32_waitpid:
  .long _win32_waitpid
.globl __imp__win32_write
__imp__win32_write:
  .long _win32_write
