.section .rdata,"dr"
.globl __imp__Perl_init_os_extras
__imp__Perl_init_os_extras:
  .long _Perl_init_os_extras
.globl __imp__Perl_win32_init
__imp__Perl_win32_init:
  .long _Perl_win32_init
.globl __imp__Perl_win32_term
__imp__Perl_win32_term:
  .long _Perl_win32_term
.globl __imp__win32_abort
__imp__win32_abort:
  .long _win32_abort
.globl __imp__win32_access
__imp__win32_access:
  .long _win32_access
.globl __imp__win32_alarm
__imp__win32_alarm:
  .long _win32_alarm
.globl __imp__win32_ansipath
__imp__win32_ansipath:
  .long _win32_ansipath
.globl __imp__win32_async_check
__imp__win32_async_check:
  .long _win32_async_check
.globl __imp__win32_calloc
__imp__win32_calloc:
  .long _win32_calloc
.globl __imp__win32_chdir
__imp__win32_chdir:
  .long _win32_chdir
.globl __imp__win32_chmod
__imp__win32_chmod:
  .long _win32_chmod
.globl __imp__win32_chsize
__imp__win32_chsize:
  .long _win32_chsize
.globl __imp__win32_clearenv
__imp__win32_clearenv:
  .long _win32_clearenv
.globl __imp__win32_clearerr
__imp__win32_clearerr:
  .long _win32_clearerr
.globl __imp__win32_close
__imp__win32_close:
  .long _win32_close
.globl __imp__win32_closedir
__imp__win32_closedir:
  .long _win32_closedir
.globl __imp__win32_crypt
__imp__win32_crypt:
  .long _win32_crypt
.globl __imp__win32_dup
__imp__win32_dup:
  .long _win32_dup
.globl __imp__win32_dup2
__imp__win32_dup2:
  .long _win32_dup2
.globl __imp__win32_environ
__imp__win32_environ:
  .long _win32_environ
.globl __imp__win32_errno
__imp__win32_errno:
  .long _win32_errno
.globl __imp__win32_execv
__imp__win32_execv:
  .long _win32_execv
.globl __imp__win32_execvp
__imp__win32_execvp:
  .long _win32_execvp
.globl __imp__win32_fclose
__imp__win32_fclose:
  .long _win32_fclose
.globl __imp__win32_fdopen
__imp__win32_fdopen:
  .long _win32_fdopen
.globl __imp__win32_feof
__imp__win32_feof:
  .long _win32_feof
.globl __imp__win32_ferror
__imp__win32_ferror:
  .long _win32_ferror
.globl __imp__win32_fflush
__imp__win32_fflush:
  .long _win32_fflush
.globl __imp__win32_fgetc
__imp__win32_fgetc:
  .long _win32_fgetc
.globl __imp__win32_fileno
__imp__win32_fileno:
  .long _win32_fileno
.globl __imp__win32_flock
__imp__win32_flock:
  .long _win32_flock
.globl __imp__win32_fopen
__imp__win32_fopen:
  .long _win32_fopen
.globl __imp__win32_fread
__imp__win32_fread:
  .long _win32_fread
.globl __imp__win32_free
__imp__win32_free:
  .long _win32_free
.globl __imp__win32_free_childdir
__imp__win32_free_childdir:
  .long _win32_free_childdir
.globl __imp__win32_free_childenv
__imp__win32_free_childenv:
  .long _win32_free_childenv
.globl __imp__win32_freopen
__imp__win32_freopen:
  .long _win32_freopen
.globl __imp__win32_fseek
__imp__win32_fseek:
  .long _win32_fseek
.globl __imp__win32_fstat
__imp__win32_fstat:
  .long _win32_fstat
.globl __imp__win32_ftell
__imp__win32_ftell:
  .long _win32_ftell
.globl __imp__win32_fwrite
__imp__win32_fwrite:
  .long _win32_fwrite
.globl __imp__win32_get_childdir
__imp__win32_get_childdir:
  .long _win32_get_childdir
.globl __imp__win32_get_childenv
__imp__win32_get_childenv:
  .long _win32_get_childenv
.globl __imp__win32_get_osfhandle
__imp__win32_get_osfhandle:
  .long _win32_get_osfhandle
.globl __imp__win32_getenv
__imp__win32_getenv:
  .long _win32_getenv
.globl __imp__win32_getpid
__imp__win32_getpid:
  .long _win32_getpid
.globl __imp__win32_gettimeofday
__imp__win32_gettimeofday:
  .long _win32_gettimeofday
.globl __imp__win32_ioctl
__imp__win32_ioctl:
  .long _win32_ioctl
.globl __imp__win32_isatty
__imp__win32_isatty:
  .long _win32_isatty
.globl __imp__win32_kill
__imp__win32_kill:
  .long _win32_kill
.globl __imp__win32_link
__imp__win32_link:
  .long _win32_link
.globl __imp__win32_lseek
__imp__win32_lseek:
  .long _win32_lseek
.globl __imp__win32_lstat
__imp__win32_lstat:
  .long _win32_lstat
.globl __imp__win32_malloc
__imp__win32_malloc:
  .long _win32_malloc
.globl __imp__win32_mkdir
__imp__win32_mkdir:
  .long _win32_mkdir
.globl __imp__win32_msgwait
__imp__win32_msgwait:
  .long _win32_msgwait
.globl __imp__win32_open
__imp__win32_open:
  .long _win32_open
.globl __imp__win32_open_osfhandle
__imp__win32_open_osfhandle:
  .long _win32_open_osfhandle
.globl __imp__win32_opendir
__imp__win32_opendir:
  .long _win32_opendir
.globl __imp__win32_pause
__imp__win32_pause:
  .long _win32_pause
.globl __imp__win32_pclose
__imp__win32_pclose:
  .long _win32_pclose
.globl __imp__win32_pipe
__imp__win32_pipe:
  .long _win32_pipe
.globl __imp__win32_popen
__imp__win32_popen:
  .long _win32_popen
.globl __imp__win32_popenlist
__imp__win32_popenlist:
  .long _win32_popenlist
.globl __imp__win32_putenv
__imp__win32_putenv:
  .long _win32_putenv
.globl __imp__win32_read
__imp__win32_read:
  .long _win32_read
.globl __imp__win32_readdir
__imp__win32_readdir:
  .long _win32_readdir
.globl __imp__win32_readlink
__imp__win32_readlink:
  .long _win32_readlink
.globl __imp__win32_realloc
__imp__win32_realloc:
  .long _win32_realloc
.globl __imp__win32_rename
__imp__win32_rename:
  .long _win32_rename
.globl __imp__win32_rewinddir
__imp__win32_rewinddir:
  .long _win32_rewinddir
.globl __imp__win32_rmdir
__imp__win32_rmdir:
  .long _win32_rmdir
.globl __imp__win32_seekdir
__imp__win32_seekdir:
  .long _win32_seekdir
.globl __imp__win32_setmode
__imp__win32_setmode:
  .long _win32_setmode
.globl __imp__win32_setvbuf
__imp__win32_setvbuf:
  .long _win32_setvbuf
.globl __imp__win32_signal
__imp__win32_signal:
  .long _win32_signal
.globl __imp__win32_sleep
__imp__win32_sleep:
  .long _win32_sleep
.globl __imp__win32_spawnvp
__imp__win32_spawnvp:
  .long _win32_spawnvp
.globl __imp__win32_stat
__imp__win32_stat:
  .long _win32_stat
.globl __imp__win32_stderr
__imp__win32_stderr:
  .long _win32_stderr
.globl __imp__win32_stdin
__imp__win32_stdin:
  .long _win32_stdin
.globl __imp__win32_stdout
__imp__win32_stdout:
  .long _win32_stdout
.globl __imp__win32_str_os_error
__imp__win32_str_os_error:
  .long _win32_str_os_error
.globl __imp__win32_strerror
__imp__win32_strerror:
  .long _win32_strerror
.globl __imp__win32_symlink
__imp__win32_symlink:
  .long _win32_symlink
.globl __imp__win32_tell
__imp__win32_tell:
  .long _win32_tell
.globl __imp__win32_telldir
__imp__win32_telldir:
  .long _win32_telldir
.globl __imp__win32_times
__imp__win32_times:
  .long _win32_times
.globl __imp__win32_tmpfd
__imp__win32_tmpfd:
  .long _win32_tmpfd
.globl __imp__win32_tmpfd_mode
__imp__win32_tmpfd_mode:
  .long _win32_tmpfd_mode
.globl __imp__win32_ungetc
__imp__win32_ungetc:
  .long _win32_ungetc
.globl __imp__win32_unlink
__imp__win32_unlink:
  .long _win32_unlink
.globl __imp__win32_utime
__imp__win32_utime:
  .long _win32_utime
.globl __imp__win32_vfprintf
__imp__win32_vfprintf:
  .long _win32_vfprintf
.globl __imp__win32_waitpid
__imp__win32_waitpid:
  .long _win32_waitpid
.globl __imp__win32_write
__imp__win32_write:
  .long _win32_write
