.section .rdata,"dr"
.globl __imp__PL_AboveLatin1
__imp__PL_AboveLatin1:
  .long _PL_AboveLatin1
.globl __imp__PL_Assigned_invlist
__imp__PL_Assigned_invlist:
  .long _PL_Assigned_invlist
.globl __imp__PL_CCC_non0_non230
__imp__PL_CCC_non0_non230:
  .long _PL_CCC_non0_non230
.globl __imp__PL_DBcontrol
__imp__PL_DBcontrol:
  .long _PL_DBcontrol
.globl __imp__PL_DBcv
__imp__PL_DBcv:
  .long _PL_DBcv
.globl __imp__PL_DBgv
__imp__PL_DBgv:
  .long _PL_DBgv
.globl __imp__PL_DBline
__imp__PL_DBline:
  .long _PL_DBline
.globl __imp__PL_DBsignal
__imp__PL_DBsignal:
  .long _PL_DBsignal
.globl __imp__PL_DBsingle
__imp__PL_DBsingle:
  .long _PL_DBsingle
.globl __imp__PL_DBsub
__imp__PL_DBsub:
  .long _PL_DBsub
.globl __imp__PL_DBtrace
__imp__PL_DBtrace:
  .long _PL_DBtrace
.globl __imp__PL_EXACTFish_bitmask
__imp__PL_EXACTFish_bitmask:
  .long _PL_EXACTFish_bitmask
.globl __imp__PL_EXACT_REQ8_bitmask
__imp__PL_EXACT_REQ8_bitmask:
  .long _PL_EXACT_REQ8_bitmask
.globl __imp__PL_GCB_invlist
__imp__PL_GCB_invlist:
  .long _PL_GCB_invlist
.globl __imp__PL_HasMultiCharFold
__imp__PL_HasMultiCharFold:
  .long _PL_HasMultiCharFold
.globl __imp__PL_InBitmap
__imp__PL_InBitmap:
  .long _PL_InBitmap
.globl __imp__PL_InMultiCharFold
__imp__PL_InMultiCharFold:
  .long _PL_InMultiCharFold
.globl __imp__PL_LB_invlist
__imp__PL_LB_invlist:
  .long _PL_LB_invlist
.globl __imp__PL_Latin1
__imp__PL_Latin1:
  .long _PL_Latin1
.globl __imp__PL_No
__imp__PL_No:
  .long _PL_No
.globl __imp__PL_Posix_ptrs
__imp__PL_Posix_ptrs:
  .long _PL_Posix_ptrs
.globl __imp__PL_Private_Use
__imp__PL_Private_Use:
  .long _PL_Private_Use
.globl __imp__PL_SB_invlist
__imp__PL_SB_invlist:
  .long _PL_SB_invlist
.globl __imp__PL_SCX_invlist
__imp__PL_SCX_invlist:
  .long _PL_SCX_invlist
.globl __imp__PL_Sv
__imp__PL_Sv:
  .long _PL_Sv
.globl __imp__PL_TR_SPECIAL_HANDLING_UTF8
__imp__PL_TR_SPECIAL_HANDLING_UTF8:
  .long _PL_TR_SPECIAL_HANDLING_UTF8
.globl __imp__PL_UpperLatin1
__imp__PL_UpperLatin1:
  .long _PL_UpperLatin1
.globl __imp__PL_WARN_ALL
__imp__PL_WARN_ALL:
  .long _PL_WARN_ALL
.globl __imp__PL_WARN_NONE
__imp__PL_WARN_NONE:
  .long _PL_WARN_NONE
.globl __imp__PL_WB_invlist
__imp__PL_WB_invlist:
  .long _PL_WB_invlist
.globl __imp__PL_XPosix_ptrs
__imp__PL_XPosix_ptrs:
  .long _PL_XPosix_ptrs
.globl __imp__PL_Xpv
__imp__PL_Xpv:
  .long _PL_Xpv
.globl __imp__PL_Yes
__imp__PL_Yes:
  .long _PL_Yes
.globl __imp__PL_Zero
__imp__PL_Zero:
  .long _PL_Zero
.globl __imp__PL_an
__imp__PL_an:
  .long _PL_an
.globl __imp__PL_argvgv
__imp__PL_argvgv:
  .long _PL_argvgv
.globl __imp__PL_argvout_stack
__imp__PL_argvout_stack:
  .long _PL_argvout_stack
.globl __imp__PL_argvoutgv
__imp__PL_argvoutgv:
  .long _PL_argvoutgv
.globl __imp__PL_basetime
__imp__PL_basetime:
  .long _PL_basetime
.globl __imp__PL_beginav
__imp__PL_beginav:
  .long _PL_beginav
.globl __imp__PL_beginav_save
__imp__PL_beginav_save:
  .long _PL_beginav_save
.globl __imp__PL_bincompat_options
__imp__PL_bincompat_options:
  .long _PL_bincompat_options
.globl __imp__PL_bitcount
__imp__PL_bitcount:
  .long _PL_bitcount
.globl __imp__PL_blockhooks
__imp__PL_blockhooks:
  .long _PL_blockhooks
.globl __imp__PL_body_arenas
__imp__PL_body_arenas:
  .long _PL_body_arenas
.globl __imp__PL_body_roots
__imp__PL_body_roots:
  .long _PL_body_roots
.globl __imp__PL_bodytarget
__imp__PL_bodytarget:
  .long _PL_bodytarget
.globl __imp__PL_breakable_sub_gen
__imp__PL_breakable_sub_gen:
  .long _PL_breakable_sub_gen
.globl __imp__PL_charclass
__imp__PL_charclass:
  .long _PL_charclass
.globl __imp__PL_check
__imp__PL_check:
  .long _PL_check
.globl __imp__PL_checkav
__imp__PL_checkav:
  .long _PL_checkav
.globl __imp__PL_checkav_save
__imp__PL_checkav_save:
  .long _PL_checkav_save
.globl __imp__PL_chopset
__imp__PL_chopset:
  .long _PL_chopset
.globl __imp__PL_clocktick
__imp__PL_clocktick:
  .long _PL_clocktick
.globl __imp__PL_collation_ix
__imp__PL_collation_ix:
  .long _PL_collation_ix
.globl __imp__PL_collation_name
__imp__PL_collation_name:
  .long _PL_collation_name
.globl __imp__PL_collation_standard
__imp__PL_collation_standard:
  .long _PL_collation_standard
.globl __imp__PL_collxfrm_base
__imp__PL_collxfrm_base:
  .long _PL_collxfrm_base
.globl __imp__PL_collxfrm_mult
__imp__PL_collxfrm_mult:
  .long _PL_collxfrm_mult
.globl __imp__PL_colors
__imp__PL_colors:
  .long _PL_colors
.globl __imp__PL_colorset
__imp__PL_colorset:
  .long _PL_colorset
.globl __imp__PL_compcv
__imp__PL_compcv:
  .long _PL_compcv
.globl __imp__PL_compiling
__imp__PL_compiling:
  .long _PL_compiling
.globl __imp__PL_comppad
__imp__PL_comppad:
  .long _PL_comppad
.globl __imp__PL_comppad_name
__imp__PL_comppad_name:
  .long _PL_comppad_name
.globl __imp__PL_comppad_name_fill
__imp__PL_comppad_name_fill:
  .long _PL_comppad_name_fill
.globl __imp__PL_comppad_name_floor
__imp__PL_comppad_name_floor:
  .long _PL_comppad_name_floor
.globl __imp__PL_constpadix
__imp__PL_constpadix:
  .long _PL_constpadix
.globl __imp__PL_cop_seqmax
__imp__PL_cop_seqmax:
  .long _PL_cop_seqmax
.globl __imp__PL_core_reg_engine
__imp__PL_core_reg_engine:
  .long _PL_core_reg_engine
.globl __imp__PL_csighandlerp
__imp__PL_csighandlerp:
  .long _PL_csighandlerp
.globl __imp__PL_ctype_name
__imp__PL_ctype_name:
  .long _PL_ctype_name
.globl __imp__PL_curcop
__imp__PL_curcop:
  .long _PL_curcop
.globl __imp__PL_curcopdb
__imp__PL_curcopdb:
  .long _PL_curcopdb
.globl __imp__PL_curinterp
__imp__PL_curinterp:
  .long _PL_curinterp
.globl __imp__PL_curpad
__imp__PL_curpad:
  .long _PL_curpad
.globl __imp__PL_curpm
__imp__PL_curpm:
  .long _PL_curpm
.globl __imp__PL_curpm_under
__imp__PL_curpm_under:
  .long _PL_curpm_under
.globl __imp__PL_curstack
__imp__PL_curstack:
  .long _PL_curstack
.globl __imp__PL_curstackinfo
__imp__PL_curstackinfo:
  .long _PL_curstackinfo
.globl __imp__PL_curstash
__imp__PL_curstash:
  .long _PL_curstash
.globl __imp__PL_curstname
__imp__PL_curstname:
  .long _PL_curstname
.globl __imp__PL_custom_op_descs
__imp__PL_custom_op_descs:
  .long _PL_custom_op_descs
.globl __imp__PL_custom_op_names
__imp__PL_custom_op_names:
  .long _PL_custom_op_names
.globl __imp__PL_custom_ops
__imp__PL_custom_ops:
  .long _PL_custom_ops
.globl __imp__PL_cv_has_eval
__imp__PL_cv_has_eval:
  .long _PL_cv_has_eval
.globl __imp__PL_dbargs
__imp__PL_dbargs:
  .long _PL_dbargs
.globl __imp__PL_debstash
__imp__PL_debstash:
  .long _PL_debstash
.globl __imp__PL_debug
__imp__PL_debug:
  .long _PL_debug
.globl __imp__PL_debug_pad
__imp__PL_debug_pad:
  .long _PL_debug_pad
.globl __imp__PL_def_layerlist
__imp__PL_def_layerlist:
  .long _PL_def_layerlist
.globl __imp__PL_defgv
__imp__PL_defgv:
  .long _PL_defgv
.globl __imp__PL_defoutgv
__imp__PL_defoutgv:
  .long _PL_defoutgv
.globl __imp__PL_defstash
__imp__PL_defstash:
  .long _PL_defstash
.globl __imp__PL_delaymagic
__imp__PL_delaymagic:
  .long _PL_delaymagic
.globl __imp__PL_delaymagic_egid
__imp__PL_delaymagic_egid:
  .long _PL_delaymagic_egid
.globl __imp__PL_delaymagic_euid
__imp__PL_delaymagic_euid:
  .long _PL_delaymagic_euid
.globl __imp__PL_delaymagic_gid
__imp__PL_delaymagic_gid:
  .long _PL_delaymagic_gid
.globl __imp__PL_delaymagic_uid
__imp__PL_delaymagic_uid:
  .long _PL_delaymagic_uid
.globl __imp__PL_destroyhook
__imp__PL_destroyhook:
  .long _PL_destroyhook
.globl __imp__PL_diehook
__imp__PL_diehook:
  .long _PL_diehook
.globl __imp__PL_do_undump
__imp__PL_do_undump:
  .long _PL_do_undump
.globl __imp__PL_doswitches
__imp__PL_doswitches:
  .long _PL_doswitches
.globl __imp__PL_dowarn
__imp__PL_dowarn:
  .long _PL_dowarn
.globl __imp__PL_dump_re_max_len
__imp__PL_dump_re_max_len:
  .long _PL_dump_re_max_len
.globl __imp__PL_dumpindent
__imp__PL_dumpindent:
  .long _PL_dumpindent
.globl __imp__PL_e_script
__imp__PL_e_script:
  .long _PL_e_script
.globl __imp__PL_efloatbuf
__imp__PL_efloatbuf:
  .long _PL_efloatbuf
.globl __imp__PL_efloatsize
__imp__PL_efloatsize:
  .long _PL_efloatsize
.globl __imp__PL_endav
__imp__PL_endav:
  .long _PL_endav
.globl __imp__PL_envgv
__imp__PL_envgv:
  .long _PL_envgv
.globl __imp__PL_errgv
__imp__PL_errgv:
  .long _PL_errgv
.globl __imp__PL_errors
__imp__PL_errors:
  .long _PL_errors
.globl __imp__PL_eval_begin_nest_depth
__imp__PL_eval_begin_nest_depth:
  .long _PL_eval_begin_nest_depth
.globl __imp__PL_eval_root
__imp__PL_eval_root:
  .long _PL_eval_root
.globl __imp__PL_eval_start
__imp__PL_eval_start:
  .long _PL_eval_start
.globl __imp__PL_evalseq
__imp__PL_evalseq:
  .long _PL_evalseq
.globl __imp__PL_exit_flags
__imp__PL_exit_flags:
  .long _PL_exit_flags
.globl __imp__PL_exitlist
__imp__PL_exitlist:
  .long _PL_exitlist
.globl __imp__PL_exitlistlen
__imp__PL_exitlistlen:
  .long _PL_exitlistlen
.globl __imp__PL_extended_cp_format
__imp__PL_extended_cp_format:
  .long _PL_extended_cp_format
.globl __imp__PL_extended_utf8_dfa_tab
__imp__PL_extended_utf8_dfa_tab:
  .long _PL_extended_utf8_dfa_tab
.globl __imp__PL_fdpid
__imp__PL_fdpid:
  .long _PL_fdpid
.globl __imp__PL_filemode
__imp__PL_filemode:
  .long _PL_filemode
.globl __imp__PL_firstgv
__imp__PL_firstgv:
  .long _PL_firstgv
.globl __imp__PL_fold
__imp__PL_fold:
  .long _PL_fold
.globl __imp__PL_fold_latin1
__imp__PL_fold_latin1:
  .long _PL_fold_latin1
.globl __imp__PL_fold_locale
__imp__PL_fold_locale:
  .long _PL_fold_locale
.globl __imp__PL_forkprocess
__imp__PL_forkprocess:
  .long _PL_forkprocess
.globl __imp__PL_formtarget
__imp__PL_formtarget:
  .long _PL_formtarget
.globl __imp__PL_generation
__imp__PL_generation:
  .long _PL_generation
.globl __imp__PL_gensym
__imp__PL_gensym:
  .long _PL_gensym
.globl __imp__PL_globalstash
__imp__PL_globalstash:
  .long _PL_globalstash
.globl __imp__PL_globhook
__imp__PL_globhook:
  .long _PL_globhook
.globl __imp__PL_hash_rand_bits
__imp__PL_hash_rand_bits:
  .long _PL_hash_rand_bits
.globl __imp__PL_hash_rand_bits_enabled
__imp__PL_hash_rand_bits_enabled:
  .long _PL_hash_rand_bits_enabled
.globl __imp__PL_hash_seed_set
__imp__PL_hash_seed_set:
  .long _PL_hash_seed_set
.globl __imp__PL_hash_seed_w
__imp__PL_hash_seed_w:
  .long _PL_hash_seed_w
.globl __imp__PL_hash_state_w
__imp__PL_hash_state_w:
  .long _PL_hash_state_w
.globl __imp__PL_hexdigit
__imp__PL_hexdigit:
  .long _PL_hexdigit
.globl __imp__PL_hintgv
__imp__PL_hintgv:
  .long _PL_hintgv
.globl __imp__PL_hook__require__after
__imp__PL_hook__require__after:
  .long _PL_hook__require__after
.globl __imp__PL_hook__require__before
__imp__PL_hook__require__before:
  .long _PL_hook__require__before
.globl __imp__PL_hv_fetch_ent_mh
__imp__PL_hv_fetch_ent_mh:
  .long _PL_hv_fetch_ent_mh
.globl __imp__PL_in_clean_all
__imp__PL_in_clean_all:
  .long _PL_in_clean_all
.globl __imp__PL_in_clean_objs
__imp__PL_in_clean_objs:
  .long _PL_in_clean_objs
.globl __imp__PL_in_eval
__imp__PL_in_eval:
  .long _PL_in_eval
.globl __imp__PL_in_load_module
__imp__PL_in_load_module:
  .long _PL_in_load_module
.globl __imp__PL_in_some_fold
__imp__PL_in_some_fold:
  .long _PL_in_some_fold
.globl __imp__PL_in_utf8_COLLATE_locale
__imp__PL_in_utf8_COLLATE_locale:
  .long _PL_in_utf8_COLLATE_locale
.globl __imp__PL_in_utf8_CTYPE_locale
__imp__PL_in_utf8_CTYPE_locale:
  .long _PL_in_utf8_CTYPE_locale
.globl __imp__PL_in_utf8_turkic_locale
__imp__PL_in_utf8_turkic_locale:
  .long _PL_in_utf8_turkic_locale
.globl __imp__PL_incgv
__imp__PL_incgv:
  .long _PL_incgv
.globl __imp__PL_inf
__imp__PL_inf:
  .long _PL_inf
.globl __imp__PL_infix_plugin
__imp__PL_infix_plugin:
  .long _PL_infix_plugin
.globl __imp__PL_initav
__imp__PL_initav:
  .long _PL_initav
.globl __imp__PL_inplace
__imp__PL_inplace:
  .long _PL_inplace
.globl __imp__PL_internal_random_state
__imp__PL_internal_random_state:
  .long _PL_internal_random_state
.globl __imp__PL_isa_DOES
__imp__PL_isa_DOES:
  .long _PL_isa_DOES
.globl __imp__PL_isarev
__imp__PL_isarev:
  .long _PL_isarev
.globl __imp__PL_keyword_plugin
__imp__PL_keyword_plugin:
  .long _PL_keyword_plugin
.globl __imp__PL_known_layers
__imp__PL_known_layers:
  .long _PL_known_layers
.globl __imp__PL_langinfo_sv
__imp__PL_langinfo_sv:
  .long _PL_langinfo_sv
.globl __imp__PL_last_in_gv
__imp__PL_last_in_gv:
  .long _PL_last_in_gv
.globl __imp__PL_lastfd
__imp__PL_lastfd:
  .long _PL_lastfd
.globl __imp__PL_lastgotoprobe
__imp__PL_lastgotoprobe:
  .long _PL_lastgotoprobe
.globl __imp__PL_laststatval
__imp__PL_laststatval:
  .long _PL_laststatval
.globl __imp__PL_laststype
__imp__PL_laststype:
  .long _PL_laststype
.globl __imp__PL_latin1_lc
__imp__PL_latin1_lc:
  .long _PL_latin1_lc
.globl __imp__PL_localizing
__imp__PL_localizing:
  .long _PL_localizing
.globl __imp__PL_localpatches
__imp__PL_localpatches:
  .long _PL_localpatches
.globl __imp__PL_lockhook
__imp__PL_lockhook:
  .long _PL_lockhook
.globl __imp__PL_magic_data
__imp__PL_magic_data:
  .long _PL_magic_data
.globl __imp__PL_magic_vtable_names
__imp__PL_magic_vtable_names:
  .long _PL_magic_vtable_names
.globl __imp__PL_magic_vtables
__imp__PL_magic_vtables:
  .long _PL_magic_vtables
.globl __imp__PL_main_cv
__imp__PL_main_cv:
  .long _PL_main_cv
.globl __imp__PL_main_root
__imp__PL_main_root:
  .long _PL_main_root
.globl __imp__PL_main_start
__imp__PL_main_start:
  .long _PL_main_start
.globl __imp__PL_mainstack
__imp__PL_mainstack:
  .long _PL_mainstack
.globl __imp__PL_markstack
__imp__PL_markstack:
  .long _PL_markstack
.globl __imp__PL_markstack_max
__imp__PL_markstack_max:
  .long _PL_markstack_max
.globl __imp__PL_markstack_ptr
__imp__PL_markstack_ptr:
  .long _PL_markstack_ptr
.globl __imp__PL_max_intro_pending
__imp__PL_max_intro_pending:
  .long _PL_max_intro_pending
.globl __imp__PL_maxsysfd
__imp__PL_maxsysfd:
  .long _PL_maxsysfd
.globl __imp__PL_memory_wrap
__imp__PL_memory_wrap:
  .long _PL_memory_wrap
.globl __imp__PL_mess_sv
__imp__PL_mess_sv:
  .long _PL_mess_sv
.globl __imp__PL_min_intro_pending
__imp__PL_min_intro_pending:
  .long _PL_min_intro_pending
.globl __imp__PL_minus_E
__imp__PL_minus_E:
  .long _PL_minus_E
.globl __imp__PL_minus_F
__imp__PL_minus_F:
  .long _PL_minus_F
.globl __imp__PL_minus_a
__imp__PL_minus_a:
  .long _PL_minus_a
.globl __imp__PL_minus_c
__imp__PL_minus_c:
  .long _PL_minus_c
.globl __imp__PL_minus_l
__imp__PL_minus_l:
  .long _PL_minus_l
.globl __imp__PL_minus_n
__imp__PL_minus_n:
  .long _PL_minus_n
.globl __imp__PL_minus_p
__imp__PL_minus_p:
  .long _PL_minus_p
.globl __imp__PL_mod_latin1_uc
__imp__PL_mod_latin1_uc:
  .long _PL_mod_latin1_uc
.globl __imp__PL_modcount
__imp__PL_modcount:
  .long _PL_modcount
.globl __imp__PL_modglobal
__imp__PL_modglobal:
  .long _PL_modglobal
.globl __imp__PL_multideref_pc
__imp__PL_multideref_pc:
  .long _PL_multideref_pc
.globl __imp__PL_nan
__imp__PL_nan:
  .long _PL_nan
.globl __imp__PL_no_aelem
__imp__PL_no_aelem:
  .long _PL_no_aelem
.globl __imp__PL_no_func
__imp__PL_no_func:
  .long _PL_no_func
.globl __imp__PL_no_helem_sv
__imp__PL_no_helem_sv:
  .long _PL_no_helem_sv
.globl __imp__PL_no_localize_ref
__imp__PL_no_localize_ref:
  .long _PL_no_localize_ref
.globl __imp__PL_no_modify
__imp__PL_no_modify:
  .long _PL_no_modify
.globl __imp__PL_no_myglob
__imp__PL_no_myglob:
  .long _PL_no_myglob
.globl __imp__PL_no_security
__imp__PL_no_security:
  .long _PL_no_security
.globl __imp__PL_no_sock_func
__imp__PL_no_sock_func:
  .long _PL_no_sock_func
.globl __imp__PL_no_symref_sv
__imp__PL_no_symref_sv:
  .long _PL_no_symref_sv
.globl __imp__PL_no_usym
__imp__PL_no_usym:
  .long _PL_no_usym
.globl __imp__PL_nomemok
__imp__PL_nomemok:
  .long _PL_nomemok
.globl __imp__PL_numeric_name
__imp__PL_numeric_name:
  .long _PL_numeric_name
.globl __imp__PL_numeric_radix_sv
__imp__PL_numeric_radix_sv:
  .long _PL_numeric_radix_sv
.globl __imp__PL_numeric_standard
__imp__PL_numeric_standard:
  .long _PL_numeric_standard
.globl __imp__PL_numeric_underlying
__imp__PL_numeric_underlying:
  .long _PL_numeric_underlying
.globl __imp__PL_numeric_underlying_is_standard
__imp__PL_numeric_underlying_is_standard:
  .long _PL_numeric_underlying_is_standard
.globl __imp__PL_ofsgv
__imp__PL_ofsgv:
  .long _PL_ofsgv
.globl __imp__PL_oldname
__imp__PL_oldname:
  .long _PL_oldname
.globl __imp__PL_op
__imp__PL_op:
  .long _PL_op
.globl __imp__PL_op_desc
__imp__PL_op_desc:
  .long _PL_op_desc
.globl __imp__PL_op_mask
__imp__PL_op_mask:
  .long _PL_op_mask
.globl __imp__PL_op_name
__imp__PL_op_name:
  .long _PL_op_name
.globl __imp__PL_op_private_bitdef_ix
__imp__PL_op_private_bitdef_ix:
  .long _PL_op_private_bitdef_ix
.globl __imp__PL_op_private_bitdefs
__imp__PL_op_private_bitdefs:
  .long _PL_op_private_bitdefs
.globl __imp__PL_op_private_bitfields
__imp__PL_op_private_bitfields:
  .long _PL_op_private_bitfields
.globl __imp__PL_op_private_labels
__imp__PL_op_private_labels:
  .long _PL_op_private_labels
.globl __imp__PL_op_seq
__imp__PL_op_seq:
  .long _PL_op_seq
.globl __imp__PL_op_sequence
__imp__PL_op_sequence:
  .long _PL_op_sequence
.globl __imp__PL_opargs
__imp__PL_opargs:
  .long _PL_opargs
.globl __imp__PL_opfreehook
__imp__PL_opfreehook:
  .long _PL_opfreehook
.globl __imp__PL_origalen
__imp__PL_origalen:
  .long _PL_origalen
.globl __imp__PL_origargc
__imp__PL_origargc:
  .long _PL_origargc
.globl __imp__PL_origargv
__imp__PL_origargv:
  .long _PL_origargv
.globl __imp__PL_origfilename
__imp__PL_origfilename:
  .long _PL_origfilename
.globl __imp__PL_ors_sv
__imp__PL_ors_sv:
  .long _PL_ors_sv
.globl __imp__PL_osname
__imp__PL_osname:
  .long _PL_osname
.globl __imp__PL_pad_reset_pending
__imp__PL_pad_reset_pending:
  .long _PL_pad_reset_pending
.globl __imp__PL_padix
__imp__PL_padix:
  .long _PL_padix
.globl __imp__PL_padix_floor
__imp__PL_padix_floor:
  .long _PL_padix_floor
.globl __imp__PL_padlist_generation
__imp__PL_padlist_generation:
  .long _PL_padlist_generation
.globl __imp__PL_padname_const
__imp__PL_padname_const:
  .long _PL_padname_const
.globl __imp__PL_padname_undef
__imp__PL_padname_undef:
  .long _PL_padname_undef
.globl __imp__PL_parser
__imp__PL_parser:
  .long _PL_parser
.globl __imp__PL_patchlevel
__imp__PL_patchlevel:
  .long _PL_patchlevel
.globl __imp__PL_peepp
__imp__PL_peepp:
  .long _PL_peepp
.globl __imp__PL_perl_destruct_level
__imp__PL_perl_destruct_level:
  .long _PL_perl_destruct_level
.globl __imp__PL_perldb
__imp__PL_perldb:
  .long _PL_perldb
.globl __imp__PL_perlio
__imp__PL_perlio:
  .long _PL_perlio
.globl __imp__PL_perlio_fd_refcnt
__imp__PL_perlio_fd_refcnt:
  .long _PL_perlio_fd_refcnt
.globl __imp__PL_perlio_fd_refcnt_size
__imp__PL_perlio_fd_refcnt_size:
  .long _PL_perlio_fd_refcnt_size
.globl __imp__PL_phase
__imp__PL_phase:
  .long _PL_phase
.globl __imp__PL_phase_names
__imp__PL_phase_names:
  .long _PL_phase_names
.globl __imp__PL_ppaddr
__imp__PL_ppaddr:
  .long _PL_ppaddr
.globl __imp__PL_preambleav
__imp__PL_preambleav:
  .long _PL_preambleav
.globl __imp__PL_prevailing_version
__imp__PL_prevailing_version:
  .long _PL_prevailing_version
.globl __imp__PL_profiledata
__imp__PL_profiledata:
  .long _PL_profiledata
.globl __imp__PL_psig_name
__imp__PL_psig_name:
  .long _PL_psig_name
.globl __imp__PL_psig_pend
__imp__PL_psig_pend:
  .long _PL_psig_pend
.globl __imp__PL_psig_ptr
__imp__PL_psig_ptr:
  .long _PL_psig_ptr
.globl __imp__PL_random_state
__imp__PL_random_state:
  .long _PL_random_state
.globl __imp__PL_reg_curpm
__imp__PL_reg_curpm:
  .long _PL_reg_curpm
.globl __imp__PL_registered_mros
__imp__PL_registered_mros:
  .long _PL_registered_mros
.globl __imp__PL_regmatch_slab
__imp__PL_regmatch_slab:
  .long _PL_regmatch_slab
.globl __imp__PL_regmatch_state
__imp__PL_regmatch_state:
  .long _PL_regmatch_state
.globl __imp__PL_regnode_info
__imp__PL_regnode_info:
  .long _PL_regnode_info
.globl __imp__PL_regnode_name
__imp__PL_regnode_name:
  .long _PL_regnode_name
.globl __imp__PL_replgv
__imp__PL_replgv:
  .long _PL_replgv
.globl __imp__PL_restartjmpenv
__imp__PL_restartjmpenv:
  .long _PL_restartjmpenv
.globl __imp__PL_restartop
__imp__PL_restartop:
  .long _PL_restartop
.globl __imp__PL_rpeepp
__imp__PL_rpeepp:
  .long _PL_rpeepp
.globl __imp__PL_rs
__imp__PL_rs:
  .long _PL_rs
.globl __imp__PL_runops
__imp__PL_runops:
  .long _PL_runops
.globl __imp__PL_savebegin
__imp__PL_savebegin:
  .long _PL_savebegin
.globl __imp__PL_savestack
__imp__PL_savestack:
  .long _PL_savestack
.globl __imp__PL_savestack_ix
__imp__PL_savestack_ix:
  .long _PL_savestack_ix
.globl __imp__PL_savestack_max
__imp__PL_savestack_max:
  .long _PL_savestack_max
.globl __imp__PL_scopestack
__imp__PL_scopestack:
  .long _PL_scopestack
.globl __imp__PL_scopestack_ix
__imp__PL_scopestack_ix:
  .long _PL_scopestack_ix
.globl __imp__PL_scopestack_max
__imp__PL_scopestack_max:
  .long _PL_scopestack_max
.globl __imp__PL_scopestack_name
__imp__PL_scopestack_name:
  .long _PL_scopestack_name
.globl __imp__PL_scratch_langinfo
__imp__PL_scratch_langinfo:
  .long _PL_scratch_langinfo
.globl __imp__PL_secondgv
__imp__PL_secondgv:
  .long _PL_secondgv
.globl __imp__PL_setlocale_buf
__imp__PL_setlocale_buf:
  .long _PL_setlocale_buf
.globl __imp__PL_setlocale_bufsize
__imp__PL_setlocale_bufsize:
  .long _PL_setlocale_bufsize
.globl __imp__PL_sharehook
__imp__PL_sharehook:
  .long _PL_sharehook
.globl __imp__PL_sig_name
__imp__PL_sig_name:
  .long _PL_sig_name
.globl __imp__PL_sig_num
__imp__PL_sig_num:
  .long _PL_sig_num
.globl __imp__PL_sig_pending
__imp__PL_sig_pending:
  .long _PL_sig_pending
.globl __imp__PL_sig_trapped
__imp__PL_sig_trapped:
  .long _PL_sig_trapped
.globl __imp__PL_sigfpe_saved
__imp__PL_sigfpe_saved:
  .long _PL_sigfpe_saved
.globl __imp__PL_sighandler1p
__imp__PL_sighandler1p:
  .long _PL_sighandler1p
.globl __imp__PL_sighandler3p
__imp__PL_sighandler3p:
  .long _PL_sighandler3p
.globl __imp__PL_sighandlerp
__imp__PL_sighandlerp:
  .long _PL_sighandlerp
.globl __imp__PL_signalhook
__imp__PL_signalhook:
  .long _PL_signalhook
.globl __imp__PL_signals
__imp__PL_signals:
  .long _PL_signals
.globl __imp__PL_simple_bitmask
__imp__PL_simple_bitmask:
  .long _PL_simple_bitmask
.globl __imp__PL_sortcop
__imp__PL_sortcop:
  .long _PL_sortcop
.globl __imp__PL_splitstr
__imp__PL_splitstr:
  .long _PL_splitstr
.globl __imp__PL_srand_called
__imp__PL_srand_called:
  .long _PL_srand_called
.globl __imp__PL_srand_override
__imp__PL_srand_override:
  .long _PL_srand_override
.globl __imp__PL_srand_override_next
__imp__PL_srand_override_next:
  .long _PL_srand_override_next
.globl __imp__PL_stack_base
__imp__PL_stack_base:
  .long _PL_stack_base
.globl __imp__PL_stack_max
__imp__PL_stack_max:
  .long _PL_stack_max
.globl __imp__PL_stack_sp
__imp__PL_stack_sp:
  .long _PL_stack_sp
.globl __imp__PL_start_env
__imp__PL_start_env:
  .long _PL_start_env
.globl __imp__PL_stashcache
__imp__PL_stashcache:
  .long _PL_stashcache
.globl __imp__PL_statcache
__imp__PL_statcache:
  .long _PL_statcache
.globl __imp__PL_statgv
__imp__PL_statgv:
  .long _PL_statgv
.globl __imp__PL_statname
__imp__PL_statname:
  .long _PL_statname
.globl __imp__PL_statusvalue
__imp__PL_statusvalue:
  .long _PL_statusvalue
.globl __imp__PL_statusvalue_posix
__imp__PL_statusvalue_posix:
  .long _PL_statusvalue_posix
.globl __imp__PL_stderrgv
__imp__PL_stderrgv:
  .long _PL_stderrgv
.globl __imp__PL_stdingv
__imp__PL_stdingv:
  .long _PL_stdingv
.globl __imp__PL_strict_utf8_dfa_tab
__imp__PL_strict_utf8_dfa_tab:
  .long _PL_strict_utf8_dfa_tab
.globl __imp__PL_strtab
__imp__PL_strtab:
  .long _PL_strtab
.globl __imp__PL_strxfrm_NUL_replacement
__imp__PL_strxfrm_NUL_replacement:
  .long _PL_strxfrm_NUL_replacement
.globl __imp__PL_strxfrm_is_behaved
__imp__PL_strxfrm_is_behaved:
  .long _PL_strxfrm_is_behaved
.globl __imp__PL_strxfrm_max_cp
__imp__PL_strxfrm_max_cp:
  .long _PL_strxfrm_max_cp
.globl __imp__PL_sub_generation
__imp__PL_sub_generation:
  .long _PL_sub_generation
.globl __imp__PL_subline
__imp__PL_subline:
  .long _PL_subline
.globl __imp__PL_subname
__imp__PL_subname:
  .long _PL_subname
.globl __imp__PL_sv_arenaroot
__imp__PL_sv_arenaroot:
  .long _PL_sv_arenaroot
.globl __imp__PL_sv_consts
__imp__PL_sv_consts:
  .long _PL_sv_consts
.globl __imp__PL_sv_count
__imp__PL_sv_count:
  .long _PL_sv_count
.globl __imp__PL_sv_immortals
__imp__PL_sv_immortals:
  .long _PL_sv_immortals
.globl __imp__PL_sv_placeholder
__imp__PL_sv_placeholder:
  .long _PL_sv_placeholder
.globl __imp__PL_sv_root
__imp__PL_sv_root:
  .long _PL_sv_root
.globl __imp__PL_sys_intern
__imp__PL_sys_intern:
  .long _PL_sys_intern
.globl __imp__PL_taint_warn
__imp__PL_taint_warn:
  .long _PL_taint_warn
.globl __imp__PL_tainted
__imp__PL_tainted:
  .long _PL_tainted
.globl __imp__PL_tainting
__imp__PL_tainting:
  .long _PL_tainting
.globl __imp__PL_threadhook
__imp__PL_threadhook:
  .long _PL_threadhook
.globl __imp__PL_tmps_floor
__imp__PL_tmps_floor:
  .long _PL_tmps_floor
.globl __imp__PL_tmps_ix
__imp__PL_tmps_ix:
  .long _PL_tmps_ix
.globl __imp__PL_tmps_max
__imp__PL_tmps_max:
  .long _PL_tmps_max
.globl __imp__PL_tmps_stack
__imp__PL_tmps_stack:
  .long _PL_tmps_stack
.globl __imp__PL_top_env
__imp__PL_top_env:
  .long _PL_top_env
.globl __imp__PL_toptarget
__imp__PL_toptarget:
  .long _PL_toptarget
.globl __imp__PL_underlying_radix_sv
__imp__PL_underlying_radix_sv:
  .long _PL_underlying_radix_sv
.globl __imp__PL_unicode
__imp__PL_unicode:
  .long _PL_unicode
.globl __imp__PL_unitcheckav
__imp__PL_unitcheckav:
  .long _PL_unitcheckav
.globl __imp__PL_unitcheckav_save
__imp__PL_unitcheckav_save:
  .long _PL_unitcheckav_save
.globl __imp__PL_unlockhook
__imp__PL_unlockhook:
  .long _PL_unlockhook
.globl __imp__PL_unsafe
__imp__PL_unsafe:
  .long _PL_unsafe
.globl __imp__PL_user_def_props
__imp__PL_user_def_props:
  .long _PL_user_def_props
.globl __imp__PL_utf8_charname_begin
__imp__PL_utf8_charname_begin:
  .long _PL_utf8_charname_begin
.globl __imp__PL_utf8_charname_continue
__imp__PL_utf8_charname_continue:
  .long _PL_utf8_charname_continue
.globl __imp__PL_utf8_foldclosures
__imp__PL_utf8_foldclosures:
  .long _PL_utf8_foldclosures
.globl __imp__PL_utf8_idcont
__imp__PL_utf8_idcont:
  .long _PL_utf8_idcont
.globl __imp__PL_utf8_idstart
__imp__PL_utf8_idstart:
  .long _PL_utf8_idstart
.globl __imp__PL_utf8_mark
__imp__PL_utf8_mark:
  .long _PL_utf8_mark
.globl __imp__PL_utf8_perl_idcont
__imp__PL_utf8_perl_idcont:
  .long _PL_utf8_perl_idcont
.globl __imp__PL_utf8_perl_idstart
__imp__PL_utf8_perl_idstart:
  .long _PL_utf8_perl_idstart
.globl __imp__PL_utf8_tofold
__imp__PL_utf8_tofold:
  .long _PL_utf8_tofold
.globl __imp__PL_utf8_tolower
__imp__PL_utf8_tolower:
  .long _PL_utf8_tolower
.globl __imp__PL_utf8_tosimplefold
__imp__PL_utf8_tosimplefold:
  .long _PL_utf8_tosimplefold
.globl __imp__PL_utf8_totitle
__imp__PL_utf8_totitle:
  .long _PL_utf8_totitle
.globl __imp__PL_utf8_toupper
__imp__PL_utf8_toupper:
  .long _PL_utf8_toupper
.globl __imp__PL_utf8_xidcont
__imp__PL_utf8_xidcont:
  .long _PL_utf8_xidcont
.globl __imp__PL_utf8_xidstart
__imp__PL_utf8_xidstart:
  .long _PL_utf8_xidstart
.globl __imp__PL_utf8cache
__imp__PL_utf8cache:
  .long _PL_utf8cache
.globl __imp__PL_utf8locale
__imp__PL_utf8locale:
  .long _PL_utf8locale
.globl __imp__PL_utf8skip
__imp__PL_utf8skip:
  .long _PL_utf8skip
.globl __imp__PL_uudmap
__imp__PL_uudmap:
  .long _PL_uudmap
.globl __imp__PL_uuemap
__imp__PL_uuemap:
  .long _PL_uuemap
.globl __imp__PL_varies_bitmask
__imp__PL_varies_bitmask:
  .long _PL_varies_bitmask
.globl __imp__PL_veto_cleanup
__imp__PL_veto_cleanup:
  .long _PL_veto_cleanup
.globl __imp__PL_warn_locale
__imp__PL_warn_locale:
  .long _PL_warn_locale
.globl __imp__PL_warn_nl
__imp__PL_warn_nl:
  .long _PL_warn_nl
.globl __imp__PL_warn_nosemi
__imp__PL_warn_nosemi:
  .long _PL_warn_nosemi
.globl __imp__PL_warn_reserved
__imp__PL_warn_reserved:
  .long _PL_warn_reserved
.globl __imp__PL_warn_uninit
__imp__PL_warn_uninit:
  .long _PL_warn_uninit
.globl __imp__PL_warn_uninit_sv
__imp__PL_warn_uninit_sv:
  .long _PL_warn_uninit_sv
.globl __imp__PL_warnhook
__imp__PL_warnhook:
  .long _PL_warnhook
.globl __imp__PL_watchaddr
__imp__PL_watchaddr:
  .long _PL_watchaddr
.globl __imp__PL_watchok
__imp__PL_watchok:
  .long _PL_watchok
.globl __imp__PL_xsubfilename
__imp__PL_xsubfilename:
  .long _PL_xsubfilename
.globl __imp__Perl_PerlIO_clearerr
__imp__Perl_PerlIO_clearerr:
  .long _Perl_PerlIO_clearerr
.globl __imp__Perl_PerlIO_close
__imp__Perl_PerlIO_close:
  .long _Perl_PerlIO_close
.globl __imp__Perl_PerlIO_context_layers
__imp__Perl_PerlIO_context_layers:
  .long _Perl_PerlIO_context_layers
.globl __imp__Perl_PerlIO_eof
__imp__Perl_PerlIO_eof:
  .long _Perl_PerlIO_eof
.globl __imp__Perl_PerlIO_error
__imp__Perl_PerlIO_error:
  .long _Perl_PerlIO_error
.globl __imp__Perl_PerlIO_fileno
__imp__Perl_PerlIO_fileno:
  .long _Perl_PerlIO_fileno
.globl __imp__Perl_PerlIO_flush
__imp__Perl_PerlIO_flush:
  .long _Perl_PerlIO_flush
.globl __imp__Perl_PerlIO_get_base
__imp__Perl_PerlIO_get_base:
  .long _Perl_PerlIO_get_base
.globl __imp__Perl_PerlIO_get_bufsiz
__imp__Perl_PerlIO_get_bufsiz:
  .long _Perl_PerlIO_get_bufsiz
.globl __imp__Perl_PerlIO_get_cnt
__imp__Perl_PerlIO_get_cnt:
  .long _Perl_PerlIO_get_cnt
.globl __imp__Perl_PerlIO_get_ptr
__imp__Perl_PerlIO_get_ptr:
  .long _Perl_PerlIO_get_ptr
.globl __imp__Perl_PerlIO_read
__imp__Perl_PerlIO_read:
  .long _Perl_PerlIO_read
.globl __imp__Perl_PerlIO_restore_errno
__imp__Perl_PerlIO_restore_errno:
  .long _Perl_PerlIO_restore_errno
.globl __imp__Perl_PerlIO_seek
__imp__Perl_PerlIO_seek:
  .long _Perl_PerlIO_seek
.globl __imp__Perl_PerlIO_set_cnt
__imp__Perl_PerlIO_set_cnt:
  .long _Perl_PerlIO_set_cnt
.globl __imp__Perl_PerlIO_set_ptrcnt
__imp__Perl_PerlIO_set_ptrcnt:
  .long _Perl_PerlIO_set_ptrcnt
.globl __imp__Perl_PerlIO_setlinebuf
__imp__Perl_PerlIO_setlinebuf:
  .long _Perl_PerlIO_setlinebuf
.globl __imp__Perl_PerlIO_stderr
__imp__Perl_PerlIO_stderr:
  .long _Perl_PerlIO_stderr
.globl __imp__Perl_PerlIO_stdin
__imp__Perl_PerlIO_stdin:
  .long _Perl_PerlIO_stdin
.globl __imp__Perl_PerlIO_stdout
__imp__Perl_PerlIO_stdout:
  .long _Perl_PerlIO_stdout
.globl __imp__Perl_PerlIO_tell
__imp__Perl_PerlIO_tell:
  .long _Perl_PerlIO_tell
.globl __imp__Perl_PerlIO_write
__imp__Perl_PerlIO_write:
  .long _Perl_PerlIO_write
.globl __imp__Perl_PerlLIO_dup_cloexec
__imp__Perl_PerlLIO_dup_cloexec:
  .long _Perl_PerlLIO_dup_cloexec
.globl __imp__Perl_PerlLIO_open3_cloexec
__imp__Perl_PerlLIO_open3_cloexec:
  .long _Perl_PerlLIO_open3_cloexec
.globl __imp__Perl_PerlLIO_open_cloexec
__imp__Perl_PerlLIO_open_cloexec:
  .long _Perl_PerlLIO_open_cloexec
.globl __imp__Perl_PerlProc_pipe_cloexec
__imp__Perl_PerlProc_pipe_cloexec:
  .long _Perl_PerlProc_pipe_cloexec
.globl __imp__Perl__add_range_to_invlist
__imp__Perl__add_range_to_invlist:
  .long _Perl__add_range_to_invlist
.globl __imp__Perl__force_out_malformed_utf8_message
__imp__Perl__force_out_malformed_utf8_message:
  .long _Perl__force_out_malformed_utf8_message
.globl __imp__Perl__inverse_folds
__imp__Perl__inverse_folds:
  .long _Perl__inverse_folds
.globl __imp__Perl__invlistEQ
__imp__Perl__invlistEQ:
  .long _Perl__invlistEQ
.globl __imp__Perl__invlist_dump
__imp__Perl__invlist_dump:
  .long _Perl__invlist_dump
.globl __imp__Perl__invlist_intersection_maybe_complement_2nd
__imp__Perl__invlist_intersection_maybe_complement_2nd:
  .long _Perl__invlist_intersection_maybe_complement_2nd
.globl __imp__Perl__invlist_invert
__imp__Perl__invlist_invert:
  .long _Perl__invlist_invert
.globl __imp__Perl__invlist_search
__imp__Perl__invlist_search:
  .long _Perl__invlist_search
.globl __imp__Perl__invlist_union_maybe_complement_2nd
__imp__Perl__invlist_union_maybe_complement_2nd:
  .long _Perl__invlist_union_maybe_complement_2nd
.globl __imp__Perl__is_in_locale_category
__imp__Perl__is_in_locale_category:
  .long _Perl__is_in_locale_category
.globl __imp__Perl__is_uni_FOO
__imp__Perl__is_uni_FOO:
  .long _Perl__is_uni_FOO
.globl __imp__Perl__is_utf8_FOO
__imp__Perl__is_utf8_FOO:
  .long _Perl__is_utf8_FOO
.globl __imp__Perl__is_utf8_perl_idcont
__imp__Perl__is_utf8_perl_idcont:
  .long _Perl__is_utf8_perl_idcont
.globl __imp__Perl__is_utf8_perl_idstart
__imp__Perl__is_utf8_perl_idstart:
  .long _Perl__is_utf8_perl_idstart
.globl __imp__Perl__new_invlist
__imp__Perl__new_invlist:
  .long _Perl__new_invlist
.globl __imp__Perl__new_invlist_C_array
__imp__Perl__new_invlist_C_array:
  .long _Perl__new_invlist_C_array
.globl __imp__Perl__to_fold_latin1
__imp__Perl__to_fold_latin1:
  .long _Perl__to_fold_latin1
.globl __imp__Perl__to_uni_fold_flags
__imp__Perl__to_uni_fold_flags:
  .long _Perl__to_uni_fold_flags
.globl __imp__Perl__to_upper_title_latin1
__imp__Perl__to_upper_title_latin1:
  .long _Perl__to_upper_title_latin1
.globl __imp__Perl__to_utf8_fold_flags
__imp__Perl__to_utf8_fold_flags:
  .long _Perl__to_utf8_fold_flags
.globl __imp__Perl__to_utf8_lower_flags
__imp__Perl__to_utf8_lower_flags:
  .long _Perl__to_utf8_lower_flags
.globl __imp__Perl__to_utf8_title_flags
__imp__Perl__to_utf8_title_flags:
  .long _Perl__to_utf8_title_flags
.globl __imp__Perl__to_utf8_upper_flags
__imp__Perl__to_utf8_upper_flags:
  .long _Perl__to_utf8_upper_flags
.globl __imp__Perl__utf8n_to_uvchr_msgs_helper
__imp__Perl__utf8n_to_uvchr_msgs_helper:
  .long _Perl__utf8n_to_uvchr_msgs_helper
.globl __imp__Perl_abort_execution
__imp__Perl_abort_execution:
  .long _Perl_abort_execution
.globl __imp__Perl_add_above_Latin1_folds
__imp__Perl_add_above_Latin1_folds:
  .long _Perl_add_above_Latin1_folds
.globl __imp__Perl_allocmy
__imp__Perl_allocmy:
  .long _Perl_allocmy
.globl __imp__Perl_amagic_applies
__imp__Perl_amagic_applies:
  .long _Perl_amagic_applies
.globl __imp__Perl_amagic_call
__imp__Perl_amagic_call:
  .long _Perl_amagic_call
.globl __imp__Perl_amagic_deref_call
__imp__Perl_amagic_deref_call:
  .long _Perl_amagic_deref_call
.globl __imp__Perl_amagic_is_enabled
__imp__Perl_amagic_is_enabled:
  .long _Perl_amagic_is_enabled
.globl __imp__Perl_apply
__imp__Perl_apply:
  .long _Perl_apply
.globl __imp__Perl_apply_builtin_cv_attributes
__imp__Perl_apply_builtin_cv_attributes:
  .long _Perl_apply_builtin_cv_attributes
.globl __imp__Perl_av_arylen_p
__imp__Perl_av_arylen_p:
  .long _Perl_av_arylen_p
.globl __imp__Perl_av_clear
__imp__Perl_av_clear:
  .long _Perl_av_clear
.globl __imp__Perl_av_create_and_push
__imp__Perl_av_create_and_push:
  .long _Perl_av_create_and_push
.globl __imp__Perl_av_create_and_unshift_one
__imp__Perl_av_create_and_unshift_one:
  .long _Perl_av_create_and_unshift_one
.globl __imp__Perl_av_delete
__imp__Perl_av_delete:
  .long _Perl_av_delete
.globl __imp__Perl_av_exists
__imp__Perl_av_exists:
  .long _Perl_av_exists
.globl __imp__Perl_av_extend
__imp__Perl_av_extend:
  .long _Perl_av_extend
.globl __imp__Perl_av_extend_guts
__imp__Perl_av_extend_guts:
  .long _Perl_av_extend_guts
.globl __imp__Perl_av_fetch
__imp__Perl_av_fetch:
  .long _Perl_av_fetch
.globl __imp__Perl_av_fill
__imp__Perl_av_fill:
  .long _Perl_av_fill
.globl __imp__Perl_av_iter_p
__imp__Perl_av_iter_p:
  .long _Perl_av_iter_p
.globl __imp__Perl_av_len
__imp__Perl_av_len:
  .long _Perl_av_len
.globl __imp__Perl_av_make
__imp__Perl_av_make:
  .long _Perl_av_make
.globl __imp__Perl_av_nonelem
__imp__Perl_av_nonelem:
  .long _Perl_av_nonelem
.globl __imp__Perl_av_pop
__imp__Perl_av_pop:
  .long _Perl_av_pop
.globl __imp__Perl_av_push
__imp__Perl_av_push:
  .long _Perl_av_push
.globl __imp__Perl_av_reify
__imp__Perl_av_reify:
  .long _Perl_av_reify
.globl __imp__Perl_av_shift
__imp__Perl_av_shift:
  .long _Perl_av_shift
.globl __imp__Perl_av_store
__imp__Perl_av_store:
  .long _Perl_av_store
.globl __imp__Perl_av_undef
__imp__Perl_av_undef:
  .long _Perl_av_undef
.globl __imp__Perl_av_unshift
__imp__Perl_av_unshift:
  .long _Perl_av_unshift
.globl __imp__Perl_bind_match
__imp__Perl_bind_match:
  .long _Perl_bind_match
.globl __imp__Perl_block_end
__imp__Perl_block_end:
  .long _Perl_block_end
.globl __imp__Perl_block_gimme
__imp__Perl_block_gimme:
  .long _Perl_block_gimme
.globl __imp__Perl_block_start
__imp__Perl_block_start:
  .long _Perl_block_start
.globl __imp__Perl_boot_core_PerlIO
__imp__Perl_boot_core_PerlIO:
  .long _Perl_boot_core_PerlIO
.globl __imp__Perl_boot_core_UNIVERSAL
__imp__Perl_boot_core_UNIVERSAL:
  .long _Perl_boot_core_UNIVERSAL
.globl __imp__Perl_boot_core_builtin
__imp__Perl_boot_core_builtin:
  .long _Perl_boot_core_builtin
.globl __imp__Perl_boot_core_mro
__imp__Perl_boot_core_mro:
  .long _Perl_boot_core_mro
.globl __imp__Perl_build_infix_plugin
__imp__Perl_build_infix_plugin:
  .long _Perl_build_infix_plugin
.globl __imp__Perl_bytes_cmp_utf8
__imp__Perl_bytes_cmp_utf8:
  .long _Perl_bytes_cmp_utf8
.globl __imp__Perl_bytes_from_utf8_loc
__imp__Perl_bytes_from_utf8_loc:
  .long _Perl_bytes_from_utf8_loc
.globl __imp__Perl_bytes_to_utf8
__imp__Perl_bytes_to_utf8:
  .long _Perl_bytes_to_utf8
.globl __imp__Perl_call_list
__imp__Perl_call_list:
  .long _Perl_call_list
.globl __imp__Perl_call_method
__imp__Perl_call_method:
  .long _Perl_call_method
.globl __imp__Perl_call_sv
__imp__Perl_call_sv:
  .long _Perl_call_sv
.globl __imp__Perl_caller_cx
__imp__Perl_caller_cx:
  .long _Perl_caller_cx
.globl __imp__Perl_cando
__imp__Perl_cando:
  .long _Perl_cando
.globl __imp__Perl_cast_iv
__imp__Perl_cast_iv:
  .long _Perl_cast_iv
.globl __imp__Perl_cast_uv
__imp__Perl_cast_uv:
  .long _Perl_cast_uv
.globl __imp__Perl_check_hash_fields_and_hekify
__imp__Perl_check_hash_fields_and_hekify:
  .long _Perl_check_hash_fields_and_hekify
.globl __imp__Perl_check_utf8_print
__imp__Perl_check_utf8_print:
  .long _Perl_check_utf8_print
.globl __imp__Perl_ck_anoncode
__imp__Perl_ck_anoncode:
  .long _Perl_ck_anoncode
.globl __imp__Perl_ck_backtick
__imp__Perl_ck_backtick:
  .long _Perl_ck_backtick
.globl __imp__Perl_ck_bitop
__imp__Perl_ck_bitop:
  .long _Perl_ck_bitop
.globl __imp__Perl_ck_classname
__imp__Perl_ck_classname:
  .long _Perl_ck_classname
.globl __imp__Perl_ck_cmp
__imp__Perl_ck_cmp:
  .long _Perl_ck_cmp
.globl __imp__Perl_ck_concat
__imp__Perl_ck_concat:
  .long _Perl_ck_concat
.globl __imp__Perl_ck_defined
__imp__Perl_ck_defined:
  .long _Perl_ck_defined
.globl __imp__Perl_ck_delete
__imp__Perl_ck_delete:
  .long _Perl_ck_delete
.globl __imp__Perl_ck_each
__imp__Perl_ck_each:
  .long _Perl_ck_each
.globl __imp__Perl_ck_entersub_args_core
__imp__Perl_ck_entersub_args_core:
  .long _Perl_ck_entersub_args_core
.globl __imp__Perl_ck_entersub_args_proto
__imp__Perl_ck_entersub_args_proto:
  .long _Perl_ck_entersub_args_proto
.globl __imp__Perl_ck_eof
__imp__Perl_ck_eof:
  .long _Perl_ck_eof
.globl __imp__Perl_ck_eval
__imp__Perl_ck_eval:
  .long _Perl_ck_eval
.globl __imp__Perl_ck_exec
__imp__Perl_ck_exec:
  .long _Perl_ck_exec
.globl __imp__Perl_ck_exists
__imp__Perl_ck_exists:
  .long _Perl_ck_exists
.globl __imp__Perl_ck_ftst
__imp__Perl_ck_ftst:
  .long _Perl_ck_ftst
.globl __imp__Perl_ck_fun
__imp__Perl_ck_fun:
  .long _Perl_ck_fun
.globl __imp__Perl_ck_glob
__imp__Perl_ck_glob:
  .long _Perl_ck_glob
.globl __imp__Perl_ck_grep
__imp__Perl_ck_grep:
  .long _Perl_ck_grep
.globl __imp__Perl_ck_helemexistsor
__imp__Perl_ck_helemexistsor:
  .long _Perl_ck_helemexistsor
.globl __imp__Perl_ck_index
__imp__Perl_ck_index:
  .long _Perl_ck_index
.globl __imp__Perl_ck_isa
__imp__Perl_ck_isa:
  .long _Perl_ck_isa
.globl __imp__Perl_ck_join
__imp__Perl_ck_join:
  .long _Perl_ck_join
.globl __imp__Perl_ck_length
__imp__Perl_ck_length:
  .long _Perl_ck_length
.globl __imp__Perl_ck_lfun
__imp__Perl_ck_lfun:
  .long _Perl_ck_lfun
.globl __imp__Perl_ck_listiob
__imp__Perl_ck_listiob:
  .long _Perl_ck_listiob
.globl __imp__Perl_ck_match
__imp__Perl_ck_match:
  .long _Perl_ck_match
.globl __imp__Perl_ck_method
__imp__Perl_ck_method:
  .long _Perl_ck_method
.globl __imp__Perl_ck_null
__imp__Perl_ck_null:
  .long _Perl_ck_null
.globl __imp__Perl_ck_open
__imp__Perl_ck_open:
  .long _Perl_ck_open
.globl __imp__Perl_ck_prototype
__imp__Perl_ck_prototype:
  .long _Perl_ck_prototype
.globl __imp__Perl_ck_readline
__imp__Perl_ck_readline:
  .long _Perl_ck_readline
.globl __imp__Perl_ck_refassign
__imp__Perl_ck_refassign:
  .long _Perl_ck_refassign
.globl __imp__Perl_ck_repeat
__imp__Perl_ck_repeat:
  .long _Perl_ck_repeat
.globl __imp__Perl_ck_require
__imp__Perl_ck_require:
  .long _Perl_ck_require
.globl __imp__Perl_ck_return
__imp__Perl_ck_return:
  .long _Perl_ck_return
.globl __imp__Perl_ck_rfun
__imp__Perl_ck_rfun:
  .long _Perl_ck_rfun
.globl __imp__Perl_ck_rvconst
__imp__Perl_ck_rvconst:
  .long _Perl_ck_rvconst
.globl __imp__Perl_ck_sassign
__imp__Perl_ck_sassign:
  .long _Perl_ck_sassign
.globl __imp__Perl_ck_select
__imp__Perl_ck_select:
  .long _Perl_ck_select
.globl __imp__Perl_ck_shift
__imp__Perl_ck_shift:
  .long _Perl_ck_shift
.globl __imp__Perl_ck_smartmatch
__imp__Perl_ck_smartmatch:
  .long _Perl_ck_smartmatch
.globl __imp__Perl_ck_sort
__imp__Perl_ck_sort:
  .long _Perl_ck_sort
.globl __imp__Perl_ck_spair
__imp__Perl_ck_spair:
  .long _Perl_ck_spair
.globl __imp__Perl_ck_split
__imp__Perl_ck_split:
  .long _Perl_ck_split
.globl __imp__Perl_ck_stringify
__imp__Perl_ck_stringify:
  .long _Perl_ck_stringify
.globl __imp__Perl_ck_subr
__imp__Perl_ck_subr:
  .long _Perl_ck_subr
.globl __imp__Perl_ck_substr
__imp__Perl_ck_substr:
  .long _Perl_ck_substr
.globl __imp__Perl_ck_svconst
__imp__Perl_ck_svconst:
  .long _Perl_ck_svconst
.globl __imp__Perl_ck_tell
__imp__Perl_ck_tell:
  .long _Perl_ck_tell
.globl __imp__Perl_ck_trunc
__imp__Perl_ck_trunc:
  .long _Perl_ck_trunc
.globl __imp__Perl_ck_trycatch
__imp__Perl_ck_trycatch:
  .long _Perl_ck_trycatch
.globl __imp__Perl_ck_warner
__imp__Perl_ck_warner:
  .long _Perl_ck_warner
.globl __imp__Perl_ck_warner_d
__imp__Perl_ck_warner_d:
  .long _Perl_ck_warner_d
.globl __imp__Perl_ckwarn
__imp__Perl_ckwarn:
  .long _Perl_ckwarn
.globl __imp__Perl_ckwarn_d
__imp__Perl_ckwarn_d:
  .long _Perl_ckwarn_d
.globl __imp__Perl_class_add_ADJUST
__imp__Perl_class_add_ADJUST:
  .long _Perl_class_add_ADJUST
.globl __imp__Perl_class_add_field
__imp__Perl_class_add_field:
  .long _Perl_class_add_field
.globl __imp__Perl_class_apply_attributes
__imp__Perl_class_apply_attributes:
  .long _Perl_class_apply_attributes
.globl __imp__Perl_class_apply_field_attributes
__imp__Perl_class_apply_field_attributes:
  .long _Perl_class_apply_field_attributes
.globl __imp__Perl_class_prepare_initfield_parse
__imp__Perl_class_prepare_initfield_parse:
  .long _Perl_class_prepare_initfield_parse
.globl __imp__Perl_class_prepare_method_parse
__imp__Perl_class_prepare_method_parse:
  .long _Perl_class_prepare_method_parse
.globl __imp__Perl_class_set_field_defop
__imp__Perl_class_set_field_defop:
  .long _Perl_class_set_field_defop
.globl __imp__Perl_class_setup_stash
__imp__Perl_class_setup_stash:
  .long _Perl_class_setup_stash
.globl __imp__Perl_class_wrap_method_body
__imp__Perl_class_wrap_method_body:
  .long _Perl_class_wrap_method_body
.globl __imp__Perl_clear_defarray
__imp__Perl_clear_defarray:
  .long _Perl_clear_defarray
.globl __imp__Perl_closest_cop
__imp__Perl_closest_cop:
  .long _Perl_closest_cop
.globl __imp__Perl_cmpchain_extend
__imp__Perl_cmpchain_extend:
  .long _Perl_cmpchain_extend
.globl __imp__Perl_cmpchain_finish
__imp__Perl_cmpchain_finish:
  .long _Perl_cmpchain_finish
.globl __imp__Perl_cmpchain_start
__imp__Perl_cmpchain_start:
  .long _Perl_cmpchain_start
.globl __imp__Perl_cntrl_to_mnemonic
__imp__Perl_cntrl_to_mnemonic:
  .long _Perl_cntrl_to_mnemonic
.globl __imp__Perl_construct_ahocorasick_from_trie
__imp__Perl_construct_ahocorasick_from_trie:
  .long _Perl_construct_ahocorasick_from_trie
.globl __imp__Perl_cop_fetch_label
__imp__Perl_cop_fetch_label:
  .long _Perl_cop_fetch_label
.globl __imp__Perl_cop_store_label
__imp__Perl_cop_store_label:
  .long _Perl_cop_store_label
.globl __imp__Perl_core_prototype
__imp__Perl_core_prototype:
  .long _Perl_core_prototype
.globl __imp__Perl_coresub_op
__imp__Perl_coresub_op:
  .long _Perl_coresub_op
.globl __imp__Perl_create_eval_scope
__imp__Perl_create_eval_scope:
  .long _Perl_create_eval_scope
.globl __imp__Perl_croak
__imp__Perl_croak:
  .long _Perl_croak
.globl __imp__Perl_croak_caller
__imp__Perl_croak_caller:
  .long _Perl_croak_caller
.globl __imp__Perl_croak_kw_unless_class
__imp__Perl_croak_kw_unless_class:
  .long _Perl_croak_kw_unless_class
.globl __imp__Perl_croak_no_mem_ext
__imp__Perl_croak_no_mem_ext:
  .long _Perl_croak_no_mem_ext
.globl __imp__Perl_croak_no_modify
__imp__Perl_croak_no_modify:
  .long _Perl_croak_no_modify
.globl __imp__Perl_croak_popstack
__imp__Perl_croak_popstack:
  .long _Perl_croak_popstack
.globl __imp__Perl_croak_sv
__imp__Perl_croak_sv:
  .long _Perl_croak_sv
.globl __imp__Perl_croak_xs_usage
__imp__Perl_croak_xs_usage:
  .long _Perl_croak_xs_usage
.globl __imp__Perl_csighandler
__imp__Perl_csighandler:
  .long _Perl_csighandler
.globl __imp__Perl_csighandler1
__imp__Perl_csighandler1:
  .long _Perl_csighandler1
.globl __imp__Perl_csighandler3
__imp__Perl_csighandler3:
  .long _Perl_csighandler3
.globl __imp__Perl_current_re_engine
__imp__Perl_current_re_engine:
  .long _Perl_current_re_engine
.globl __imp__Perl_custom_op_get_field
__imp__Perl_custom_op_get_field:
  .long _Perl_custom_op_get_field
.globl __imp__Perl_cv_ckproto_len_flags
__imp__Perl_cv_ckproto_len_flags:
  .long _Perl_cv_ckproto_len_flags
.globl __imp__Perl_cv_clone
__imp__Perl_cv_clone:
  .long _Perl_cv_clone
.globl __imp__Perl_cv_clone_into
__imp__Perl_cv_clone_into:
  .long _Perl_cv_clone_into
.globl __imp__Perl_cv_const_sv
__imp__Perl_cv_const_sv:
  .long _Perl_cv_const_sv
.globl __imp__Perl_cv_const_sv_or_av
__imp__Perl_cv_const_sv_or_av:
  .long _Perl_cv_const_sv_or_av
.globl __imp__Perl_cv_forget_slab
__imp__Perl_cv_forget_slab:
  .long _Perl_cv_forget_slab
.globl __imp__Perl_cv_name
__imp__Perl_cv_name:
  .long _Perl_cv_name
.globl __imp__Perl_cv_set_call_checker_flags
__imp__Perl_cv_set_call_checker_flags:
  .long _Perl_cv_set_call_checker_flags
.globl __imp__Perl_cv_undef
__imp__Perl_cv_undef:
  .long _Perl_cv_undef
.globl __imp__Perl_cv_undef_flags
__imp__Perl_cv_undef_flags:
  .long _Perl_cv_undef_flags
.globl __imp__Perl_cvgv_from_hek
__imp__Perl_cvgv_from_hek:
  .long _Perl_cvgv_from_hek
.globl __imp__Perl_cvgv_set
__imp__Perl_cvgv_set:
  .long _Perl_cvgv_set
.globl __imp__Perl_cvstash_set
__imp__Perl_cvstash_set:
  .long _Perl_cvstash_set
.globl __imp__Perl_cxinc
__imp__Perl_cxinc:
  .long _Perl_cxinc
.globl __imp__Perl_deb
__imp__Perl_deb:
  .long _Perl_deb
.globl __imp__Perl_deb_stack_all
__imp__Perl_deb_stack_all:
  .long _Perl_deb_stack_all
.globl __imp__Perl_debstack
__imp__Perl_debstack:
  .long _Perl_debstack
.globl __imp__Perl_debug_hash_seed
__imp__Perl_debug_hash_seed:
  .long _Perl_debug_hash_seed
.globl __imp__Perl_defelem_target
__imp__Perl_defelem_target:
  .long _Perl_defelem_target
.globl __imp__Perl_delete_eval_scope
__imp__Perl_delete_eval_scope:
  .long _Perl_delete_eval_scope
.globl __imp__Perl_delimcpy
__imp__Perl_delimcpy:
  .long _Perl_delimcpy
.globl __imp__Perl_despatch_signals
__imp__Perl_despatch_signals:
  .long _Perl_despatch_signals
.globl __imp__Perl_die
__imp__Perl_die:
  .long _Perl_die
.globl __imp__Perl_die_sv
__imp__Perl_die_sv:
  .long _Perl_die_sv
.globl __imp__Perl_die_unwind
__imp__Perl_die_unwind:
  .long _Perl_die_unwind
.globl __imp__Perl_do_aexec5
__imp__Perl_do_aexec5:
  .long _Perl_do_aexec5
.globl __imp__Perl_do_aspawn
__imp__Perl_do_aspawn:
  .long _Perl_do_aspawn
.globl __imp__Perl_do_close
__imp__Perl_do_close:
  .long _Perl_do_close
.globl __imp__Perl_do_dump_pad
__imp__Perl_do_dump_pad:
  .long _Perl_do_dump_pad
.globl __imp__Perl_do_eof
__imp__Perl_do_eof:
  .long _Perl_do_eof
.globl __imp__Perl_do_exec
__imp__Perl_do_exec:
  .long _Perl_do_exec
.globl __imp__Perl_do_join
__imp__Perl_do_join:
  .long _Perl_do_join
.globl __imp__Perl_do_kv
__imp__Perl_do_kv:
  .long _Perl_do_kv
.globl __imp__Perl_do_ncmp
__imp__Perl_do_ncmp:
  .long _Perl_do_ncmp
.globl __imp__Perl_do_open6
__imp__Perl_do_open6:
  .long _Perl_do_open6
.globl __imp__Perl_do_open_raw
__imp__Perl_do_open_raw:
  .long _Perl_do_open_raw
.globl __imp__Perl_do_openn
__imp__Perl_do_openn:
  .long _Perl_do_openn
.globl __imp__Perl_do_print
__imp__Perl_do_print:
  .long _Perl_do_print
.globl __imp__Perl_do_readline
__imp__Perl_do_readline:
  .long _Perl_do_readline
.globl __imp__Perl_do_seek
__imp__Perl_do_seek:
  .long _Perl_do_seek
.globl __imp__Perl_do_spawn
__imp__Perl_do_spawn:
  .long _Perl_do_spawn
.globl __imp__Perl_do_sprintf
__imp__Perl_do_sprintf:
  .long _Perl_do_sprintf
.globl __imp__Perl_do_sysseek
__imp__Perl_do_sysseek:
  .long _Perl_do_sysseek
.globl __imp__Perl_do_tell
__imp__Perl_do_tell:
  .long _Perl_do_tell
.globl __imp__Perl_do_trans
__imp__Perl_do_trans:
  .long _Perl_do_trans
.globl __imp__Perl_do_vecget
__imp__Perl_do_vecget:
  .long _Perl_do_vecget
.globl __imp__Perl_do_vecset
__imp__Perl_do_vecset:
  .long _Perl_do_vecset
.globl __imp__Perl_do_vop
__imp__Perl_do_vop:
  .long _Perl_do_vop
.globl __imp__Perl_dofile
__imp__Perl_dofile:
  .long _Perl_dofile
.globl __imp__Perl_doref
__imp__Perl_doref:
  .long _Perl_doref
.globl __imp__Perl_dounwind
__imp__Perl_dounwind:
  .long _Perl_dounwind
.globl __imp__Perl_drand48_init_r
__imp__Perl_drand48_init_r:
  .long _Perl_drand48_init_r
.globl __imp__Perl_drand48_r
__imp__Perl_drand48_r:
  .long _Perl_drand48_r
.globl __imp__Perl_dump_indent
__imp__Perl_dump_indent:
  .long _Perl_dump_indent
.globl __imp__Perl_dup_warnings
__imp__Perl_dup_warnings:
  .long _Perl_dup_warnings
.globl __imp__Perl_eval_sv
__imp__Perl_eval_sv:
  .long _Perl_eval_sv
.globl __imp__Perl_fatal_warner
__imp__Perl_fatal_warner:
  .long _Perl_fatal_warner
.globl __imp__Perl_fbm_compile
__imp__Perl_fbm_compile:
  .long _Perl_fbm_compile
.globl __imp__Perl_fbm_instr
__imp__Perl_fbm_instr:
  .long _Perl_fbm_instr
.globl __imp__Perl_filter_add
__imp__Perl_filter_add:
  .long _Perl_filter_add
.globl __imp__Perl_filter_del
__imp__Perl_filter_del:
  .long _Perl_filter_del
.globl __imp__Perl_filter_read
__imp__Perl_filter_read:
  .long _Perl_filter_read
.globl __imp__Perl_finalize_optree
__imp__Perl_finalize_optree:
  .long _Perl_finalize_optree
.globl __imp__Perl_find_lexical_cv
__imp__Perl_find_lexical_cv:
  .long _Perl_find_lexical_cv
.globl __imp__Perl_find_runcv
__imp__Perl_find_runcv:
  .long _Perl_find_runcv
.globl __imp__Perl_find_runcv_where
__imp__Perl_find_runcv_where:
  .long _Perl_find_runcv_where
.globl __imp__Perl_find_script
__imp__Perl_find_script:
  .long _Perl_find_script
.globl __imp__Perl_finish_export_lexical
__imp__Perl_finish_export_lexical:
  .long _Perl_finish_export_lexical
.globl __imp__Perl_foldEQ_utf8_flags
__imp__Perl_foldEQ_utf8_flags:
  .long _Perl_foldEQ_utf8_flags
.globl __imp__Perl_forbid_outofblock_ops
__imp__Perl_forbid_outofblock_ops:
  .long _Perl_forbid_outofblock_ops
.globl __imp__Perl_form
__imp__Perl_form:
  .long _Perl_form
.globl __imp__Perl_form_alien_digit_msg
__imp__Perl_form_alien_digit_msg:
  .long _Perl_form_alien_digit_msg
.globl __imp__Perl_form_cp_too_large_msg
__imp__Perl_form_cp_too_large_msg:
  .long _Perl_form_cp_too_large_msg
.globl __imp__Perl_free_tied_hv_pool
__imp__Perl_free_tied_hv_pool:
  .long _Perl_free_tied_hv_pool
.globl __imp__Perl_free_tmps
__imp__Perl_free_tmps:
  .long _Perl_free_tmps
.globl __imp__Perl_get_ANYOFHbbm_contents
__imp__Perl_get_ANYOFHbbm_contents:
  .long _Perl_get_ANYOFHbbm_contents
.globl __imp__Perl_get_ANYOFM_contents
__imp__Perl_get_ANYOFM_contents:
  .long _Perl_get_ANYOFM_contents
.globl __imp__Perl_get_and_check_backslash_N_name
__imp__Perl_get_and_check_backslash_N_name:
  .long _Perl_get_and_check_backslash_N_name
.globl __imp__Perl_get_av
__imp__Perl_get_av:
  .long _Perl_get_av
.globl __imp__Perl_get_cv
__imp__Perl_get_cv:
  .long _Perl_get_cv
.globl __imp__Perl_get_cvn_flags
__imp__Perl_get_cvn_flags:
  .long _Perl_get_cvn_flags
.globl __imp__Perl_get_db_sub
__imp__Perl_get_db_sub:
  .long _Perl_get_db_sub
.globl __imp__Perl_get_extended_os_errno
__imp__Perl_get_extended_os_errno:
  .long _Perl_get_extended_os_errno
.globl __imp__Perl_get_hash_seed
__imp__Perl_get_hash_seed:
  .long _Perl_get_hash_seed
.globl __imp__Perl_get_hv
__imp__Perl_get_hv:
  .long _Perl_get_hv
.globl __imp__Perl_get_re_arg
__imp__Perl_get_re_arg:
  .long _Perl_get_re_arg
.globl __imp__Perl_get_regclass_aux_data
__imp__Perl_get_regclass_aux_data:
  .long _Perl_get_regclass_aux_data
.globl __imp__Perl_get_sv
__imp__Perl_get_sv:
  .long _Perl_get_sv
.globl __imp__Perl_get_win32_message_utf8ness
__imp__Perl_get_win32_message_utf8ness:
  .long _Perl_get_win32_message_utf8ness
.globl __imp__Perl_gmtime64_r
__imp__Perl_gmtime64_r:
  .long _Perl_gmtime64_r
.globl __imp__Perl_gp_free
__imp__Perl_gp_free:
  .long _Perl_gp_free
.globl __imp__Perl_gp_ref
__imp__Perl_gp_ref:
  .long _Perl_gp_ref
.globl __imp__Perl_grok_atoUV
__imp__Perl_grok_atoUV:
  .long _Perl_grok_atoUV
.globl __imp__Perl_grok_bin_oct_hex
__imp__Perl_grok_bin_oct_hex:
  .long _Perl_grok_bin_oct_hex
.globl __imp__Perl_grok_bslash_c
__imp__Perl_grok_bslash_c:
  .long _Perl_grok_bslash_c
.globl __imp__Perl_grok_bslash_o
__imp__Perl_grok_bslash_o:
  .long _Perl_grok_bslash_o
.globl __imp__Perl_grok_bslash_x
__imp__Perl_grok_bslash_x:
  .long _Perl_grok_bslash_x
.globl __imp__Perl_grok_number
__imp__Perl_grok_number:
  .long _Perl_grok_number
.globl __imp__Perl_grok_number_flags
__imp__Perl_grok_number_flags:
  .long _Perl_grok_number_flags
.globl __imp__Perl_gv_add_by_type
__imp__Perl_gv_add_by_type:
  .long _Perl_gv_add_by_type
.globl __imp__Perl_gv_autoload_pvn
__imp__Perl_gv_autoload_pvn:
  .long _Perl_gv_autoload_pvn
.globl __imp__Perl_gv_check
__imp__Perl_gv_check:
  .long _Perl_gv_check
.globl __imp__Perl_gv_efullname4
__imp__Perl_gv_efullname4:
  .long _Perl_gv_efullname4
.globl __imp__Perl_gv_fetchfile
__imp__Perl_gv_fetchfile:
  .long _Perl_gv_fetchfile
.globl __imp__Perl_gv_fetchfile_flags
__imp__Perl_gv_fetchfile_flags:
  .long _Perl_gv_fetchfile_flags
.globl __imp__Perl_gv_fetchmeth_pvn
__imp__Perl_gv_fetchmeth_pvn:
  .long _Perl_gv_fetchmeth_pvn
.globl __imp__Perl_gv_fetchmethod_autoload
__imp__Perl_gv_fetchmethod_autoload:
  .long _Perl_gv_fetchmethod_autoload
.globl __imp__Perl_gv_fetchmethod_pvn_flags
__imp__Perl_gv_fetchmethod_pvn_flags:
  .long _Perl_gv_fetchmethod_pvn_flags
.globl __imp__Perl_gv_fetchmethod_sv_flags
__imp__Perl_gv_fetchmethod_sv_flags:
  .long _Perl_gv_fetchmethod_sv_flags
.globl __imp__Perl_gv_fetchpv
__imp__Perl_gv_fetchpv:
  .long _Perl_gv_fetchpv
.globl __imp__Perl_gv_fetchpvn_flags
__imp__Perl_gv_fetchpvn_flags:
  .long _Perl_gv_fetchpvn_flags
.globl __imp__Perl_gv_fetchsv
__imp__Perl_gv_fetchsv:
  .long _Perl_gv_fetchsv
.globl __imp__Perl_gv_fullname4
__imp__Perl_gv_fullname4:
  .long _Perl_gv_fullname4
.globl __imp__Perl_gv_init_pv
__imp__Perl_gv_init_pv:
  .long _Perl_gv_init_pv
.globl __imp__Perl_gv_init_pvn
__imp__Perl_gv_init_pvn:
  .long _Perl_gv_init_pvn
.globl __imp__Perl_gv_init_sv
__imp__Perl_gv_init_sv:
  .long _Perl_gv_init_sv
.globl __imp__Perl_gv_name_set
__imp__Perl_gv_name_set:
  .long _Perl_gv_name_set
.globl __imp__Perl_gv_override
__imp__Perl_gv_override:
  .long _Perl_gv_override
.globl __imp__Perl_gv_setref
__imp__Perl_gv_setref:
  .long _Perl_gv_setref
.globl __imp__Perl_gv_stashpv
__imp__Perl_gv_stashpv:
  .long _Perl_gv_stashpv
.globl __imp__Perl_gv_stashpvn
__imp__Perl_gv_stashpvn:
  .long _Perl_gv_stashpvn
.globl __imp__Perl_gv_stashsv
__imp__Perl_gv_stashsv:
  .long _Perl_gv_stashsv
.globl __imp__Perl_gv_stashsvpvn_cached
__imp__Perl_gv_stashsvpvn_cached:
  .long _Perl_gv_stashsvpvn_cached
.globl __imp__Perl_gv_try_downgrade
__imp__Perl_gv_try_downgrade:
  .long _Perl_gv_try_downgrade
.globl __imp__Perl_hfree_next_entry
__imp__Perl_hfree_next_entry:
  .long _Perl_hfree_next_entry
.globl __imp__Perl_hv_auxalloc
__imp__Perl_hv_auxalloc:
  .long _Perl_hv_auxalloc
.globl __imp__Perl_hv_backreferences_p
__imp__Perl_hv_backreferences_p:
  .long _Perl_hv_backreferences_p
.globl __imp__Perl_hv_clear
__imp__Perl_hv_clear:
  .long _Perl_hv_clear
.globl __imp__Perl_hv_clear_placeholders
__imp__Perl_hv_clear_placeholders:
  .long _Perl_hv_clear_placeholders
.globl __imp__Perl_hv_common
__imp__Perl_hv_common:
  .long _Perl_hv_common
.globl __imp__Perl_hv_common_key_len
__imp__Perl_hv_common_key_len:
  .long _Perl_hv_common_key_len
.globl __imp__Perl_hv_copy_hints_hv
__imp__Perl_hv_copy_hints_hv:
  .long _Perl_hv_copy_hints_hv
.globl __imp__Perl_hv_eiter_set
__imp__Perl_hv_eiter_set:
  .long _Perl_hv_eiter_set
.globl __imp__Perl_hv_ename_add
__imp__Perl_hv_ename_add:
  .long _Perl_hv_ename_add
.globl __imp__Perl_hv_ename_delete
__imp__Perl_hv_ename_delete:
  .long _Perl_hv_ename_delete
.globl __imp__Perl_hv_free_ent
__imp__Perl_hv_free_ent:
  .long _Perl_hv_free_ent
.globl __imp__Perl_hv_iterinit
__imp__Perl_hv_iterinit:
  .long _Perl_hv_iterinit
.globl __imp__Perl_hv_iterkey
__imp__Perl_hv_iterkey:
  .long _Perl_hv_iterkey
.globl __imp__Perl_hv_iterkeysv
__imp__Perl_hv_iterkeysv:
  .long _Perl_hv_iterkeysv
.globl __imp__Perl_hv_iternext_flags
__imp__Perl_hv_iternext_flags:
  .long _Perl_hv_iternext_flags
.globl __imp__Perl_hv_iterval
__imp__Perl_hv_iterval:
  .long _Perl_hv_iterval
.globl __imp__Perl_hv_kill_backrefs
__imp__Perl_hv_kill_backrefs:
  .long _Perl_hv_kill_backrefs
.globl __imp__Perl_hv_ksplit
__imp__Perl_hv_ksplit:
  .long _Perl_hv_ksplit
.globl __imp__Perl_hv_name_set
__imp__Perl_hv_name_set:
  .long _Perl_hv_name_set
.globl __imp__Perl_hv_placeholders_get
__imp__Perl_hv_placeholders_get:
  .long _Perl_hv_placeholders_get
.globl __imp__Perl_hv_pushkv
__imp__Perl_hv_pushkv:
  .long _Perl_hv_pushkv
.globl __imp__Perl_hv_riter_set
__imp__Perl_hv_riter_set:
  .long _Perl_hv_riter_set
.globl __imp__Perl_hv_undef_flags
__imp__Perl_hv_undef_flags:
  .long _Perl_hv_undef_flags
.globl __imp__Perl_import_builtin_bundle
__imp__Perl_import_builtin_bundle:
  .long _Perl_import_builtin_bundle
.globl __imp__Perl_infix_plugin_standard
__imp__Perl_infix_plugin_standard:
  .long _Perl_infix_plugin_standard
.globl __imp__Perl_init_argv_symbols
__imp__Perl_init_argv_symbols:
  .long _Perl_init_argv_symbols
.globl __imp__Perl_init_constants
__imp__Perl_init_constants:
  .long _Perl_init_constants
.globl __imp__Perl_init_dbargs
__imp__Perl_init_dbargs:
  .long _Perl_init_dbargs
.globl __imp__Perl_init_debugger
__imp__Perl_init_debugger:
  .long _Perl_init_debugger
.globl __imp__Perl_init_i18nl10n
__imp__Perl_init_i18nl10n:
  .long _Perl_init_i18nl10n
.globl __imp__Perl_init_named_cv
__imp__Perl_init_named_cv:
  .long _Perl_init_named_cv
.globl __imp__Perl_init_uniprops
__imp__Perl_init_uniprops:
  .long _Perl_init_uniprops
.globl __imp__Perl_intro_my
__imp__Perl_intro_my:
  .long _Perl_intro_my
.globl __imp__Perl_invert
__imp__Perl_invert:
  .long _Perl_invert
.globl __imp__Perl_invlist_clone
__imp__Perl_invlist_clone:
  .long _Perl_invlist_clone
.globl __imp__Perl_invoke_exception_hook
__imp__Perl_invoke_exception_hook:
  .long _Perl_invoke_exception_hook
.globl __imp__Perl_io_close
__imp__Perl_io_close:
  .long _Perl_io_close
.globl __imp__Perl_is_grapheme
__imp__Perl_is_grapheme:
  .long _Perl_is_grapheme
.globl __imp__Perl_is_lvalue_sub
__imp__Perl_is_lvalue_sub:
  .long _Perl_is_lvalue_sub
.globl __imp__Perl_is_utf8_FF_helper_
__imp__Perl_is_utf8_FF_helper_:
  .long _Perl_is_utf8_FF_helper_
.globl __imp__Perl_isinfnan
__imp__Perl_isinfnan:
  .long _Perl_isinfnan
.globl __imp__Perl_isinfnansv
__imp__Perl_isinfnansv:
  .long _Perl_isinfnansv
.globl __imp__Perl_jmaybe
__imp__Perl_jmaybe:
  .long _Perl_jmaybe
.globl __imp__Perl_keyword
__imp__Perl_keyword:
  .long _Perl_keyword
.globl __imp__Perl_keyword_plugin_standard
__imp__Perl_keyword_plugin_standard:
  .long _Perl_keyword_plugin_standard
.globl __imp__Perl_leave_adjust_stacks
__imp__Perl_leave_adjust_stacks:
  .long _Perl_leave_adjust_stacks
.globl __imp__Perl_leave_scope
__imp__Perl_leave_scope:
  .long _Perl_leave_scope
.globl __imp__Perl_lex_start
__imp__Perl_lex_start:
  .long _Perl_lex_start
.globl __imp__Perl_list
__imp__Perl_list:
  .long _Perl_list
.globl __imp__Perl_load_charnames
__imp__Perl_load_charnames:
  .long _Perl_load_charnames
.globl __imp__Perl_load_module
__imp__Perl_load_module:
  .long _Perl_load_module
.globl __imp__Perl_localize
__imp__Perl_localize:
  .long _Perl_localize
.globl __imp__Perl_localtime64_r
__imp__Perl_localtime64_r:
  .long _Perl_localtime64_r
.globl __imp__Perl_looks_like_number
__imp__Perl_looks_like_number:
  .long _Perl_looks_like_number
.globl __imp__Perl_magic_clear_all_env
__imp__Perl_magic_clear_all_env:
  .long _Perl_magic_clear_all_env
.globl __imp__Perl_magic_cleararylen_p
__imp__Perl_magic_cleararylen_p:
  .long _Perl_magic_cleararylen_p
.globl __imp__Perl_magic_clearenv
__imp__Perl_magic_clearenv:
  .long _Perl_magic_clearenv
.globl __imp__Perl_magic_clearhint
__imp__Perl_magic_clearhint:
  .long _Perl_magic_clearhint
.globl __imp__Perl_magic_clearhints
__imp__Perl_magic_clearhints:
  .long _Perl_magic_clearhints
.globl __imp__Perl_magic_clearhook
__imp__Perl_magic_clearhook:
  .long _Perl_magic_clearhook
.globl __imp__Perl_magic_clearhookall
__imp__Perl_magic_clearhookall:
  .long _Perl_magic_clearhookall
.globl __imp__Perl_magic_clearisa
__imp__Perl_magic_clearisa:
  .long _Perl_magic_clearisa
.globl __imp__Perl_magic_clearpack
__imp__Perl_magic_clearpack:
  .long _Perl_magic_clearpack
.globl __imp__Perl_magic_clearsig
__imp__Perl_magic_clearsig:
  .long _Perl_magic_clearsig
.globl __imp__Perl_magic_copycallchecker
__imp__Perl_magic_copycallchecker:
  .long _Perl_magic_copycallchecker
.globl __imp__Perl_magic_existspack
__imp__Perl_magic_existspack:
  .long _Perl_magic_existspack
.globl __imp__Perl_magic_freearylen_p
__imp__Perl_magic_freearylen_p:
  .long _Perl_magic_freearylen_p
.globl __imp__Perl_magic_freecollxfrm
__imp__Perl_magic_freecollxfrm:
  .long _Perl_magic_freecollxfrm
.globl __imp__Perl_magic_freedestruct
__imp__Perl_magic_freedestruct:
  .long _Perl_magic_freedestruct
.globl __imp__Perl_magic_freemglob
__imp__Perl_magic_freemglob:
  .long _Perl_magic_freemglob
.globl __imp__Perl_magic_freeovrld
__imp__Perl_magic_freeovrld:
  .long _Perl_magic_freeovrld
.globl __imp__Perl_magic_freeutf8
__imp__Perl_magic_freeutf8:
  .long _Perl_magic_freeutf8
.globl __imp__Perl_magic_get
__imp__Perl_magic_get:
  .long _Perl_magic_get
.globl __imp__Perl_magic_getarylen
__imp__Perl_magic_getarylen:
  .long _Perl_magic_getarylen
.globl __imp__Perl_magic_getdebugvar
__imp__Perl_magic_getdebugvar:
  .long _Perl_magic_getdebugvar
.globl __imp__Perl_magic_getdefelem
__imp__Perl_magic_getdefelem:
  .long _Perl_magic_getdefelem
.globl __imp__Perl_magic_getnkeys
__imp__Perl_magic_getnkeys:
  .long _Perl_magic_getnkeys
.globl __imp__Perl_magic_getpack
__imp__Perl_magic_getpack:
  .long _Perl_magic_getpack
.globl __imp__Perl_magic_getpos
__imp__Perl_magic_getpos:
  .long _Perl_magic_getpos
.globl __imp__Perl_magic_getsig
__imp__Perl_magic_getsig:
  .long _Perl_magic_getsig
.globl __imp__Perl_magic_getsubstr
__imp__Perl_magic_getsubstr:
  .long _Perl_magic_getsubstr
.globl __imp__Perl_magic_gettaint
__imp__Perl_magic_gettaint:
  .long _Perl_magic_gettaint
.globl __imp__Perl_magic_getuvar
__imp__Perl_magic_getuvar:
  .long _Perl_magic_getuvar
.globl __imp__Perl_magic_getvec
__imp__Perl_magic_getvec:
  .long _Perl_magic_getvec
.globl __imp__Perl_magic_killbackrefs
__imp__Perl_magic_killbackrefs:
  .long _Perl_magic_killbackrefs
.globl __imp__Perl_magic_methcall
__imp__Perl_magic_methcall:
  .long _Perl_magic_methcall
.globl __imp__Perl_magic_nextpack
__imp__Perl_magic_nextpack:
  .long _Perl_magic_nextpack
.globl __imp__Perl_magic_regdata_cnt
__imp__Perl_magic_regdata_cnt:
  .long _Perl_magic_regdata_cnt
.globl __imp__Perl_magic_regdatum_get
__imp__Perl_magic_regdatum_get:
  .long _Perl_magic_regdatum_get
.globl __imp__Perl_magic_regdatum_set
__imp__Perl_magic_regdatum_set:
  .long _Perl_magic_regdatum_set
.globl __imp__Perl_magic_scalarpack
__imp__Perl_magic_scalarpack:
  .long _Perl_magic_scalarpack
.globl __imp__Perl_magic_set
__imp__Perl_magic_set:
  .long _Perl_magic_set
.globl __imp__Perl_magic_set_all_env
__imp__Perl_magic_set_all_env:
  .long _Perl_magic_set_all_env
.globl __imp__Perl_magic_setarylen
__imp__Perl_magic_setarylen:
  .long _Perl_magic_setarylen
.globl __imp__Perl_magic_setcollxfrm
__imp__Perl_magic_setcollxfrm:
  .long _Perl_magic_setcollxfrm
.globl __imp__Perl_magic_setdbline
__imp__Perl_magic_setdbline:
  .long _Perl_magic_setdbline
.globl __imp__Perl_magic_setdebugvar
__imp__Perl_magic_setdebugvar:
  .long _Perl_magic_setdebugvar
.globl __imp__Perl_magic_setdefelem
__imp__Perl_magic_setdefelem:
  .long _Perl_magic_setdefelem
.globl __imp__Perl_magic_setenv
__imp__Perl_magic_setenv:
  .long _Perl_magic_setenv
.globl __imp__Perl_magic_sethint
__imp__Perl_magic_sethint:
  .long _Perl_magic_sethint
.globl __imp__Perl_magic_sethook
__imp__Perl_magic_sethook:
  .long _Perl_magic_sethook
.globl __imp__Perl_magic_sethookall
__imp__Perl_magic_sethookall:
  .long _Perl_magic_sethookall
.globl __imp__Perl_magic_setisa
__imp__Perl_magic_setisa:
  .long _Perl_magic_setisa
.globl __imp__Perl_magic_setlvref
__imp__Perl_magic_setlvref:
  .long _Perl_magic_setlvref
.globl __imp__Perl_magic_setmglob
__imp__Perl_magic_setmglob:
  .long _Perl_magic_setmglob
.globl __imp__Perl_magic_setnkeys
__imp__Perl_magic_setnkeys:
  .long _Perl_magic_setnkeys
.globl __imp__Perl_magic_setnonelem
__imp__Perl_magic_setnonelem:
  .long _Perl_magic_setnonelem
.globl __imp__Perl_magic_setpack
__imp__Perl_magic_setpack:
  .long _Perl_magic_setpack
.globl __imp__Perl_magic_setpos
__imp__Perl_magic_setpos:
  .long _Perl_magic_setpos
.globl __imp__Perl_magic_setregexp
__imp__Perl_magic_setregexp:
  .long _Perl_magic_setregexp
.globl __imp__Perl_magic_setsig
__imp__Perl_magic_setsig:
  .long _Perl_magic_setsig
.globl __imp__Perl_magic_setsigall
__imp__Perl_magic_setsigall:
  .long _Perl_magic_setsigall
.globl __imp__Perl_magic_setsubstr
__imp__Perl_magic_setsubstr:
  .long _Perl_magic_setsubstr
.globl __imp__Perl_magic_settaint
__imp__Perl_magic_settaint:
  .long _Perl_magic_settaint
.globl __imp__Perl_magic_setutf8
__imp__Perl_magic_setutf8:
  .long _Perl_magic_setutf8
.globl __imp__Perl_magic_setuvar
__imp__Perl_magic_setuvar:
  .long _Perl_magic_setuvar
.globl __imp__Perl_magic_setvec
__imp__Perl_magic_setvec:
  .long _Perl_magic_setvec
.globl __imp__Perl_magic_sizepack
__imp__Perl_magic_sizepack:
  .long _Perl_magic_sizepack
.globl __imp__Perl_magic_wipepack
__imp__Perl_magic_wipepack:
  .long _Perl_magic_wipepack
.globl __imp__Perl_make_trie
__imp__Perl_make_trie:
  .long _Perl_make_trie
.globl __imp__Perl_markstack_grow
__imp__Perl_markstack_grow:
  .long _Perl_markstack_grow
.globl __imp__Perl_mem_collxfrm_
__imp__Perl_mem_collxfrm_:
  .long _Perl_mem_collxfrm_
.globl __imp__Perl_mess
__imp__Perl_mess:
  .long _Perl_mess
.globl __imp__Perl_mg_clear
__imp__Perl_mg_clear:
  .long _Perl_mg_clear
.globl __imp__Perl_mg_copy
__imp__Perl_mg_copy:
  .long _Perl_mg_copy
.globl __imp__Perl_mg_find
__imp__Perl_mg_find:
  .long _Perl_mg_find
.globl __imp__Perl_mg_find_mglob
__imp__Perl_mg_find_mglob:
  .long _Perl_mg_find_mglob
.globl __imp__Perl_mg_findext
__imp__Perl_mg_findext:
  .long _Perl_mg_findext
.globl __imp__Perl_mg_free
__imp__Perl_mg_free:
  .long _Perl_mg_free
.globl __imp__Perl_mg_free_type
__imp__Perl_mg_free_type:
  .long _Perl_mg_free_type
.globl __imp__Perl_mg_freeext
__imp__Perl_mg_freeext:
  .long _Perl_mg_freeext
.globl __imp__Perl_mg_get
__imp__Perl_mg_get:
  .long _Perl_mg_get
.globl __imp__Perl_mg_localize
__imp__Perl_mg_localize:
  .long _Perl_mg_localize
.globl __imp__Perl_mg_magical
__imp__Perl_mg_magical:
  .long _Perl_mg_magical
.globl __imp__Perl_mg_set
__imp__Perl_mg_set:
  .long _Perl_mg_set
.globl __imp__Perl_mg_size
__imp__Perl_mg_size:
  .long _Perl_mg_size
.globl __imp__Perl_mini_mktime
__imp__Perl_mini_mktime:
  .long _Perl_mini_mktime
.globl __imp__Perl_mode_from_discipline
__imp__Perl_mode_from_discipline:
  .long _Perl_mode_from_discipline
.globl __imp__Perl_more_bodies
__imp__Perl_more_bodies:
  .long _Perl_more_bodies
.globl __imp__Perl_more_sv
__imp__Perl_more_sv:
  .long _Perl_more_sv
.globl __imp__Perl_moreswitches
__imp__Perl_moreswitches:
  .long _Perl_moreswitches
.globl __imp__Perl_mortal_destructor_sv
__imp__Perl_mortal_destructor_sv:
  .long _Perl_mortal_destructor_sv
.globl __imp__Perl_mro_get_linear_isa
__imp__Perl_mro_get_linear_isa:
  .long _Perl_mro_get_linear_isa
.globl __imp__Perl_mro_isa_changed_in
__imp__Perl_mro_isa_changed_in:
  .long _Perl_mro_isa_changed_in
.globl __imp__Perl_mro_meta_init
__imp__Perl_mro_meta_init:
  .long _Perl_mro_meta_init
.globl __imp__Perl_mro_method_changed_in
__imp__Perl_mro_method_changed_in:
  .long _Perl_mro_method_changed_in
.globl __imp__Perl_mro_package_moved
__imp__Perl_mro_package_moved:
  .long _Perl_mro_package_moved
.globl __imp__Perl_my_atof
__imp__Perl_my_atof:
  .long _Perl_my_atof
.globl __imp__Perl_my_atof3
__imp__Perl_my_atof3:
  .long _Perl_my_atof3
.globl __imp__Perl_my_attrs
__imp__Perl_my_attrs:
  .long _Perl_my_attrs
.globl __imp__Perl_my_clearenv
__imp__Perl_my_clearenv:
  .long _Perl_my_clearenv
.globl __imp__Perl_my_cxt_init
__imp__Perl_my_cxt_init:
  .long _Perl_my_cxt_init
.globl __imp__Perl_my_dirfd
__imp__Perl_my_dirfd:
  .long _Perl_my_dirfd
.globl __imp__Perl_my_exit
__imp__Perl_my_exit:
  .long _Perl_my_exit
.globl __imp__Perl_my_failure_exit
__imp__Perl_my_failure_exit:
  .long _Perl_my_failure_exit
.globl __imp__Perl_my_fflush_all
__imp__Perl_my_fflush_all:
  .long _Perl_my_fflush_all
.globl __imp__Perl_my_lstat_flags
__imp__Perl_my_lstat_flags:
  .long _Perl_my_lstat_flags
.globl __imp__Perl_my_mkostemp
__imp__Perl_my_mkostemp:
  .long _Perl_my_mkostemp
.globl __imp__Perl_my_mkstemp
__imp__Perl_my_mkstemp:
  .long _Perl_my_mkstemp
.globl __imp__Perl_my_pclose
__imp__Perl_my_pclose:
  .long _Perl_my_pclose
.globl __imp__Perl_my_popen
__imp__Perl_my_popen:
  .long _Perl_my_popen
.globl __imp__Perl_my_popen_list
__imp__Perl_my_popen_list:
  .long _Perl_my_popen_list
.globl __imp__Perl_my_setenv
__imp__Perl_my_setenv:
  .long _Perl_my_setenv
.globl __imp__Perl_my_snprintf
__imp__Perl_my_snprintf:
  .long _Perl_my_snprintf
.globl __imp__Perl_my_stat_flags
__imp__Perl_my_stat_flags:
  .long _Perl_my_stat_flags
.globl __imp__Perl_my_strerror
__imp__Perl_my_strerror:
  .long _Perl_my_strerror
.globl __imp__Perl_my_unexec
__imp__Perl_my_unexec:
  .long _Perl_my_unexec
.globl __imp__Perl_newANONATTRSUB
__imp__Perl_newANONATTRSUB:
  .long _Perl_newANONATTRSUB
.globl __imp__Perl_newANONHASH
__imp__Perl_newANONHASH:
  .long _Perl_newANONHASH
.globl __imp__Perl_newANONLIST
__imp__Perl_newANONLIST:
  .long _Perl_newANONLIST
.globl __imp__Perl_newARGDEFELEMOP
__imp__Perl_newARGDEFELEMOP:
  .long _Perl_newARGDEFELEMOP
.globl __imp__Perl_newASSIGNOP
__imp__Perl_newASSIGNOP:
  .long _Perl_newASSIGNOP
.globl __imp__Perl_newATTRSUB_x
__imp__Perl_newATTRSUB_x:
  .long _Perl_newATTRSUB_x
.globl __imp__Perl_newAVREF
__imp__Perl_newAVREF:
  .long _Perl_newAVREF
.globl __imp__Perl_newBINOP
__imp__Perl_newBINOP:
  .long _Perl_newBINOP
.globl __imp__Perl_newCONDOP
__imp__Perl_newCONDOP:
  .long _Perl_newCONDOP
.globl __imp__Perl_newCONSTSUB
__imp__Perl_newCONSTSUB:
  .long _Perl_newCONSTSUB
.globl __imp__Perl_newCONSTSUB_flags
__imp__Perl_newCONSTSUB_flags:
  .long _Perl_newCONSTSUB_flags
.globl __imp__Perl_newCVREF
__imp__Perl_newCVREF:
  .long _Perl_newCVREF
.globl __imp__Perl_newDEFEROP
__imp__Perl_newDEFEROP:
  .long _Perl_newDEFEROP
.globl __imp__Perl_newFORM
__imp__Perl_newFORM:
  .long _Perl_newFORM
.globl __imp__Perl_newFOROP
__imp__Perl_newFOROP:
  .long _Perl_newFOROP
.globl __imp__Perl_newGIVENOP
__imp__Perl_newGIVENOP:
  .long _Perl_newGIVENOP
.globl __imp__Perl_newGP
__imp__Perl_newGP:
  .long _Perl_newGP
.globl __imp__Perl_newGVOP
__imp__Perl_newGVOP:
  .long _Perl_newGVOP
.globl __imp__Perl_newGVREF
__imp__Perl_newGVREF:
  .long _Perl_newGVREF
.globl __imp__Perl_newHVREF
__imp__Perl_newHVREF:
  .long _Perl_newHVREF
.globl __imp__Perl_newHVhv
__imp__Perl_newHVhv:
  .long _Perl_newHVhv
.globl __imp__Perl_newLISTOP
__imp__Perl_newLISTOP:
  .long _Perl_newLISTOP
.globl __imp__Perl_newLISTOPn
__imp__Perl_newLISTOPn:
  .long _Perl_newLISTOPn
.globl __imp__Perl_newLOGOP
__imp__Perl_newLOGOP:
  .long _Perl_newLOGOP
.globl __imp__Perl_newLOOPEX
__imp__Perl_newLOOPEX:
  .long _Perl_newLOOPEX
.globl __imp__Perl_newLOOPOP
__imp__Perl_newLOOPOP:
  .long _Perl_newLOOPOP
.globl __imp__Perl_newMETHOP
__imp__Perl_newMETHOP:
  .long _Perl_newMETHOP
.globl __imp__Perl_newMYSUB
__imp__Perl_newMYSUB:
  .long _Perl_newMYSUB
.globl __imp__Perl_newNULLLIST
__imp__Perl_newNULLLIST:
  .long _Perl_newNULLLIST
.globl __imp__Perl_newOP
__imp__Perl_newOP:
  .long _Perl_newOP
.globl __imp__Perl_newPADNAMELIST
__imp__Perl_newPADNAMELIST:
  .long _Perl_newPADNAMELIST
.globl __imp__Perl_newPMOP
__imp__Perl_newPMOP:
  .long _Perl_newPMOP
.globl __imp__Perl_newPROG
__imp__Perl_newPROG:
  .long _Perl_newPROG
.globl __imp__Perl_newPVOP
__imp__Perl_newPVOP:
  .long _Perl_newPVOP
.globl __imp__Perl_newRANGE
__imp__Perl_newRANGE:
  .long _Perl_newRANGE
.globl __imp__Perl_newRV
__imp__Perl_newRV:
  .long _Perl_newRV
.globl __imp__Perl_newSLICEOP
__imp__Perl_newSLICEOP:
  .long _Perl_newSLICEOP
.globl __imp__Perl_newSTATEOP
__imp__Perl_newSTATEOP:
  .long _Perl_newSTATEOP
.globl __imp__Perl_newSTUB
__imp__Perl_newSTUB:
  .long _Perl_newSTUB
.globl __imp__Perl_newSV
__imp__Perl_newSV:
  .long _Perl_newSV
.globl __imp__Perl_newSVOP
__imp__Perl_newSVOP:
  .long _Perl_newSVOP
.globl __imp__Perl_newSVREF
__imp__Perl_newSVREF:
  .long _Perl_newSVREF
.globl __imp__Perl_newSVavdefelem
__imp__Perl_newSVavdefelem:
  .long _Perl_newSVavdefelem
.globl __imp__Perl_newSVhek
__imp__Perl_newSVhek:
  .long _Perl_newSVhek
.globl __imp__Perl_newSVhek_mortal
__imp__Perl_newSVhek_mortal:
  .long _Perl_newSVhek_mortal
.globl __imp__Perl_newSViv
__imp__Perl_newSViv:
  .long _Perl_newSViv
.globl __imp__Perl_newSVnv
__imp__Perl_newSVnv:
  .long _Perl_newSVnv
.globl __imp__Perl_newSVpv
__imp__Perl_newSVpv:
  .long _Perl_newSVpv
.globl __imp__Perl_newSVpv_share
__imp__Perl_newSVpv_share:
  .long _Perl_newSVpv_share
.globl __imp__Perl_newSVpvf
__imp__Perl_newSVpvf:
  .long _Perl_newSVpvf
.globl __imp__Perl_newSVpvn
__imp__Perl_newSVpvn:
  .long _Perl_newSVpvn
.globl __imp__Perl_newSVpvn_flags
__imp__Perl_newSVpvn_flags:
  .long _Perl_newSVpvn_flags
.globl __imp__Perl_newSVpvn_share
__imp__Perl_newSVpvn_share:
  .long _Perl_newSVpvn_share
.globl __imp__Perl_newSVrv
__imp__Perl_newSVrv:
  .long _Perl_newSVrv
.globl __imp__Perl_newSVsv_flags
__imp__Perl_newSVsv_flags:
  .long _Perl_newSVsv_flags
.globl __imp__Perl_newSVuv
__imp__Perl_newSVuv:
  .long _Perl_newSVuv
.globl __imp__Perl_newTRYCATCHOP
__imp__Perl_newTRYCATCHOP:
  .long _Perl_newTRYCATCHOP
.globl __imp__Perl_newUNOP
__imp__Perl_newUNOP:
  .long _Perl_newUNOP
.globl __imp__Perl_newUNOP_AUX
__imp__Perl_newUNOP_AUX:
  .long _Perl_newUNOP_AUX
.globl __imp__Perl_newWHENOP
__imp__Perl_newWHENOP:
  .long _Perl_newWHENOP
.globl __imp__Perl_newWHILEOP
__imp__Perl_newWHILEOP:
  .long _Perl_newWHILEOP
.globl __imp__Perl_newXS
__imp__Perl_newXS:
  .long _Perl_newXS
.globl __imp__Perl_newXS_deffile
__imp__Perl_newXS_deffile:
  .long _Perl_newXS_deffile
.globl __imp__Perl_newXS_flags
__imp__Perl_newXS_flags:
  .long _Perl_newXS_flags
.globl __imp__Perl_new_stackinfo_flags
__imp__Perl_new_stackinfo_flags:
  .long _Perl_new_stackinfo_flags
.globl __imp__Perl_new_version
__imp__Perl_new_version:
  .long _Perl_new_version
.globl __imp__Perl_new_warnings_bitfield
__imp__Perl_new_warnings_bitfield:
  .long _Perl_new_warnings_bitfield
.globl __imp__Perl_nextargv
__imp__Perl_nextargv:
  .long _Perl_nextargv
.globl __imp__Perl_ninstr
__imp__Perl_ninstr:
  .long _Perl_ninstr
.globl __imp__Perl_no_bareword_allowed
__imp__Perl_no_bareword_allowed:
  .long _Perl_no_bareword_allowed
.globl __imp__Perl_no_bareword_filehandle
__imp__Perl_no_bareword_filehandle:
  .long _Perl_no_bareword_filehandle
.globl __imp__Perl_noperl_die
__imp__Perl_noperl_die:
  .long _Perl_noperl_die
.globl __imp__Perl_nothreadhook
__imp__Perl_nothreadhook:
  .long _Perl_nothreadhook
.globl __imp__Perl_notify_parser_that_changed_to_utf8
__imp__Perl_notify_parser_that_changed_to_utf8:
  .long _Perl_notify_parser_that_changed_to_utf8
.globl __imp__Perl_oopsAV
__imp__Perl_oopsAV:
  .long _Perl_oopsAV
.globl __imp__Perl_oopsHV
__imp__Perl_oopsHV:
  .long _Perl_oopsHV
.globl __imp__Perl_op_append_elem
__imp__Perl_op_append_elem:
  .long _Perl_op_append_elem
.globl __imp__Perl_op_append_list
__imp__Perl_op_append_list:
  .long _Perl_op_append_list
.globl __imp__Perl_op_contextualize
__imp__Perl_op_contextualize:
  .long _Perl_op_contextualize
.globl __imp__Perl_op_convert_list
__imp__Perl_op_convert_list:
  .long _Perl_op_convert_list
.globl __imp__Perl_op_force_list
__imp__Perl_op_force_list:
  .long _Perl_op_force_list
.globl __imp__Perl_op_free
__imp__Perl_op_free:
  .long _Perl_op_free
.globl __imp__Perl_op_linklist
__imp__Perl_op_linklist:
  .long _Perl_op_linklist
.globl __imp__Perl_op_lvalue_flags
__imp__Perl_op_lvalue_flags:
  .long _Perl_op_lvalue_flags
.globl __imp__Perl_op_null
__imp__Perl_op_null:
  .long _Perl_op_null
.globl __imp__Perl_op_parent
__imp__Perl_op_parent:
  .long _Perl_op_parent
.globl __imp__Perl_op_prepend_elem
__imp__Perl_op_prepend_elem:
  .long _Perl_op_prepend_elem
.globl __imp__Perl_op_prune_chain_head
__imp__Perl_op_prune_chain_head:
  .long _Perl_op_prune_chain_head
.globl __imp__Perl_op_scope
__imp__Perl_op_scope:
  .long _Perl_op_scope
.globl __imp__Perl_op_sibling_splice
__imp__Perl_op_sibling_splice:
  .long _Perl_op_sibling_splice
.globl __imp__Perl_op_unscope
__imp__Perl_op_unscope:
  .long _Perl_op_unscope
.globl __imp__Perl_op_varname
__imp__Perl_op_varname:
  .long _Perl_op_varname
.globl __imp__Perl_op_wrap_finally
__imp__Perl_op_wrap_finally:
  .long _Perl_op_wrap_finally
.globl __imp__Perl_opslab_force_free
__imp__Perl_opslab_force_free:
  .long _Perl_opslab_force_free
.globl __imp__Perl_opslab_free
__imp__Perl_opslab_free:
  .long _Perl_opslab_free
.globl __imp__Perl_opslab_free_nopad
__imp__Perl_opslab_free_nopad:
  .long _Perl_opslab_free_nopad
.globl __imp__Perl_optimize_optree
__imp__Perl_optimize_optree:
  .long _Perl_optimize_optree
.globl __imp__Perl_package
__imp__Perl_package:
  .long _Perl_package
.globl __imp__Perl_package_version
__imp__Perl_package_version:
  .long _Perl_package_version
.globl __imp__Perl_pad_add_anon
__imp__Perl_pad_add_anon:
  .long _Perl_pad_add_anon
.globl __imp__Perl_pad_add_name_pvn
__imp__Perl_pad_add_name_pvn:
  .long _Perl_pad_add_name_pvn
.globl __imp__Perl_pad_add_name_sv
__imp__Perl_pad_add_name_sv:
  .long _Perl_pad_add_name_sv
.globl __imp__Perl_pad_add_weakref
__imp__Perl_pad_add_weakref:
  .long _Perl_pad_add_weakref
.globl __imp__Perl_pad_alloc
__imp__Perl_pad_alloc:
  .long _Perl_pad_alloc
.globl __imp__Perl_pad_block_start
__imp__Perl_pad_block_start:
  .long _Perl_pad_block_start
.globl __imp__Perl_pad_findmy_pvn
__imp__Perl_pad_findmy_pvn:
  .long _Perl_pad_findmy_pvn
.globl __imp__Perl_pad_findmy_sv
__imp__Perl_pad_findmy_sv:
  .long _Perl_pad_findmy_sv
.globl __imp__Perl_pad_fixup_inner_anons
__imp__Perl_pad_fixup_inner_anons:
  .long _Perl_pad_fixup_inner_anons
.globl __imp__Perl_pad_free
__imp__Perl_pad_free:
  .long _Perl_pad_free
.globl __imp__Perl_pad_leavemy
__imp__Perl_pad_leavemy:
  .long _Perl_pad_leavemy
.globl __imp__Perl_pad_new
__imp__Perl_pad_new:
  .long _Perl_pad_new
.globl __imp__Perl_pad_push
__imp__Perl_pad_push:
  .long _Perl_pad_push
.globl __imp__Perl_pad_swipe
__imp__Perl_pad_swipe:
  .long _Perl_pad_swipe
.globl __imp__Perl_pad_tidy
__imp__Perl_pad_tidy:
  .long _Perl_pad_tidy
.globl __imp__Perl_padname_free
__imp__Perl_padname_free:
  .long _Perl_padname_free
.globl __imp__Perl_padnamelist_fetch
__imp__Perl_padnamelist_fetch:
  .long _Perl_padnamelist_fetch
.globl __imp__Perl_padnamelist_free
__imp__Perl_padnamelist_free:
  .long _Perl_padnamelist_free
.globl __imp__Perl_padnamelist_store
__imp__Perl_padnamelist_store:
  .long _Perl_padnamelist_store
.globl __imp__Perl_parse_unicode_opts
__imp__Perl_parse_unicode_opts:
  .long _Perl_parse_unicode_opts
.globl __imp__Perl_parser_free
__imp__Perl_parser_free:
  .long _Perl_parser_free
.globl __imp__Perl_parser_free_nexttoke_ops
__imp__Perl_parser_free_nexttoke_ops:
  .long _Perl_parser_free_nexttoke_ops
.globl __imp__Perl_peep
__imp__Perl_peep:
  .long _Perl_peep
.globl __imp__Perl_pmruntime
__imp__Perl_pmruntime:
  .long _Perl_pmruntime
.globl __imp__Perl_pop_scope
__imp__Perl_pop_scope:
  .long _Perl_pop_scope
.globl __imp__Perl_populate_bitmap_from_invlist
__imp__Perl_populate_bitmap_from_invlist:
  .long _Perl_populate_bitmap_from_invlist
.globl __imp__Perl_populate_invlist_from_bitmap
__imp__Perl_populate_invlist_from_bitmap:
  .long _Perl_populate_invlist_from_bitmap
.globl __imp__Perl_populate_isa
__imp__Perl_populate_isa:
  .long _Perl_populate_isa
.globl __imp__Perl_pp_aassign
__imp__Perl_pp_aassign:
  .long _Perl_pp_aassign
.globl __imp__Perl_pp_abs
__imp__Perl_pp_abs:
  .long _Perl_pp_abs
.globl __imp__Perl_pp_add
__imp__Perl_pp_add:
  .long _Perl_pp_add
.globl __imp__Perl_pp_aeach
__imp__Perl_pp_aeach:
  .long _Perl_pp_aeach
.globl __imp__Perl_pp_aelem
__imp__Perl_pp_aelem:
  .long _Perl_pp_aelem
.globl __imp__Perl_pp_aelemfast
__imp__Perl_pp_aelemfast:
  .long _Perl_pp_aelemfast
.globl __imp__Perl_pp_aelemfastlex_store
__imp__Perl_pp_aelemfastlex_store:
  .long _Perl_pp_aelemfastlex_store
.globl __imp__Perl_pp_akeys
__imp__Perl_pp_akeys:
  .long _Perl_pp_akeys
.globl __imp__Perl_pp_alarm
__imp__Perl_pp_alarm:
  .long _Perl_pp_alarm
.globl __imp__Perl_pp_and
__imp__Perl_pp_and:
  .long _Perl_pp_and
.globl __imp__Perl_pp_anoncode
__imp__Perl_pp_anoncode:
  .long _Perl_pp_anoncode
.globl __imp__Perl_pp_anonconst
__imp__Perl_pp_anonconst:
  .long _Perl_pp_anonconst
.globl __imp__Perl_pp_anonhash
__imp__Perl_pp_anonhash:
  .long _Perl_pp_anonhash
.globl __imp__Perl_pp_anonlist
__imp__Perl_pp_anonlist:
  .long _Perl_pp_anonlist
.globl __imp__Perl_pp_argcheck
__imp__Perl_pp_argcheck:
  .long _Perl_pp_argcheck
.globl __imp__Perl_pp_argdefelem
__imp__Perl_pp_argdefelem:
  .long _Perl_pp_argdefelem
.globl __imp__Perl_pp_argelem
__imp__Perl_pp_argelem:
  .long _Perl_pp_argelem
.globl __imp__Perl_pp_aslice
__imp__Perl_pp_aslice:
  .long _Perl_pp_aslice
.globl __imp__Perl_pp_atan2
__imp__Perl_pp_atan2:
  .long _Perl_pp_atan2
.globl __imp__Perl_pp_av2arylen
__imp__Perl_pp_av2arylen:
  .long _Perl_pp_av2arylen
.globl __imp__Perl_pp_avhvswitch
__imp__Perl_pp_avhvswitch:
  .long _Perl_pp_avhvswitch
.globl __imp__Perl_pp_backtick
__imp__Perl_pp_backtick:
  .long _Perl_pp_backtick
.globl __imp__Perl_pp_binmode
__imp__Perl_pp_binmode:
  .long _Perl_pp_binmode
.globl __imp__Perl_pp_bit_and
__imp__Perl_pp_bit_and:
  .long _Perl_pp_bit_and
.globl __imp__Perl_pp_bit_or
__imp__Perl_pp_bit_or:
  .long _Perl_pp_bit_or
.globl __imp__Perl_pp_bless
__imp__Perl_pp_bless:
  .long _Perl_pp_bless
.globl __imp__Perl_pp_blessed
__imp__Perl_pp_blessed:
  .long _Perl_pp_blessed
.globl __imp__Perl_pp_break
__imp__Perl_pp_break:
  .long _Perl_pp_break
.globl __imp__Perl_pp_caller
__imp__Perl_pp_caller:
  .long _Perl_pp_caller
.globl __imp__Perl_pp_catch
__imp__Perl_pp_catch:
  .long _Perl_pp_catch
.globl __imp__Perl_pp_ceil
__imp__Perl_pp_ceil:
  .long _Perl_pp_ceil
.globl __imp__Perl_pp_chdir
__imp__Perl_pp_chdir:
  .long _Perl_pp_chdir
.globl __imp__Perl_pp_chop
__imp__Perl_pp_chop:
  .long _Perl_pp_chop
.globl __imp__Perl_pp_chown
__imp__Perl_pp_chown:
  .long _Perl_pp_chown
.globl __imp__Perl_pp_chr
__imp__Perl_pp_chr:
  .long _Perl_pp_chr
.globl __imp__Perl_pp_chroot
__imp__Perl_pp_chroot:
  .long _Perl_pp_chroot
.globl __imp__Perl_pp_classname
__imp__Perl_pp_classname:
  .long _Perl_pp_classname
.globl __imp__Perl_pp_clonecv
__imp__Perl_pp_clonecv:
  .long _Perl_pp_clonecv
.globl __imp__Perl_pp_close
__imp__Perl_pp_close:
  .long _Perl_pp_close
.globl __imp__Perl_pp_closedir
__imp__Perl_pp_closedir:
  .long _Perl_pp_closedir
.globl __imp__Perl_pp_cmpchain_and
__imp__Perl_pp_cmpchain_and:
  .long _Perl_pp_cmpchain_and
.globl __imp__Perl_pp_cmpchain_dup
__imp__Perl_pp_cmpchain_dup:
  .long _Perl_pp_cmpchain_dup
.globl __imp__Perl_pp_complement
__imp__Perl_pp_complement:
  .long _Perl_pp_complement
.globl __imp__Perl_pp_concat
__imp__Perl_pp_concat:
  .long _Perl_pp_concat
.globl __imp__Perl_pp_cond_expr
__imp__Perl_pp_cond_expr:
  .long _Perl_pp_cond_expr
.globl __imp__Perl_pp_const
__imp__Perl_pp_const:
  .long _Perl_pp_const
.globl __imp__Perl_pp_continue
__imp__Perl_pp_continue:
  .long _Perl_pp_continue
.globl __imp__Perl_pp_coreargs
__imp__Perl_pp_coreargs:
  .long _Perl_pp_coreargs
.globl __imp__Perl_pp_crypt
__imp__Perl_pp_crypt:
  .long _Perl_pp_crypt
.globl __imp__Perl_pp_dbmopen
__imp__Perl_pp_dbmopen:
  .long _Perl_pp_dbmopen
.globl __imp__Perl_pp_dbstate
__imp__Perl_pp_dbstate:
  .long _Perl_pp_dbstate
.globl __imp__Perl_pp_defined
__imp__Perl_pp_defined:
  .long _Perl_pp_defined
.globl __imp__Perl_pp_delete
__imp__Perl_pp_delete:
  .long _Perl_pp_delete
.globl __imp__Perl_pp_die
__imp__Perl_pp_die:
  .long _Perl_pp_die
.globl __imp__Perl_pp_divide
__imp__Perl_pp_divide:
  .long _Perl_pp_divide
.globl __imp__Perl_pp_each
__imp__Perl_pp_each:
  .long _Perl_pp_each
.globl __imp__Perl_pp_ehostent
__imp__Perl_pp_ehostent:
  .long _Perl_pp_ehostent
.globl __imp__Perl_pp_emptyavhv
__imp__Perl_pp_emptyavhv:
  .long _Perl_pp_emptyavhv
.globl __imp__Perl_pp_enter
__imp__Perl_pp_enter:
  .long _Perl_pp_enter
.globl __imp__Perl_pp_entereval
__imp__Perl_pp_entereval:
  .long _Perl_pp_entereval
.globl __imp__Perl_pp_entergiven
__imp__Perl_pp_entergiven:
  .long _Perl_pp_entergiven
.globl __imp__Perl_pp_enteriter
__imp__Perl_pp_enteriter:
  .long _Perl_pp_enteriter
.globl __imp__Perl_pp_enterloop
__imp__Perl_pp_enterloop:
  .long _Perl_pp_enterloop
.globl __imp__Perl_pp_entersub
__imp__Perl_pp_entersub:
  .long _Perl_pp_entersub
.globl __imp__Perl_pp_entertry
__imp__Perl_pp_entertry:
  .long _Perl_pp_entertry
.globl __imp__Perl_pp_entertrycatch
__imp__Perl_pp_entertrycatch:
  .long _Perl_pp_entertrycatch
.globl __imp__Perl_pp_enterwhen
__imp__Perl_pp_enterwhen:
  .long _Perl_pp_enterwhen
.globl __imp__Perl_pp_enterwrite
__imp__Perl_pp_enterwrite:
  .long _Perl_pp_enterwrite
.globl __imp__Perl_pp_eof
__imp__Perl_pp_eof:
  .long _Perl_pp_eof
.globl __imp__Perl_pp_eq
__imp__Perl_pp_eq:
  .long _Perl_pp_eq
.globl __imp__Perl_pp_exec
__imp__Perl_pp_exec:
  .long _Perl_pp_exec
.globl __imp__Perl_pp_exists
__imp__Perl_pp_exists:
  .long _Perl_pp_exists
.globl __imp__Perl_pp_exit
__imp__Perl_pp_exit:
  .long _Perl_pp_exit
.globl __imp__Perl_pp_fc
__imp__Perl_pp_fc:
  .long _Perl_pp_fc
.globl __imp__Perl_pp_fileno
__imp__Perl_pp_fileno:
  .long _Perl_pp_fileno
.globl __imp__Perl_pp_flip
__imp__Perl_pp_flip:
  .long _Perl_pp_flip
.globl __imp__Perl_pp_flock
__imp__Perl_pp_flock:
  .long _Perl_pp_flock
.globl __imp__Perl_pp_floor
__imp__Perl_pp_floor:
  .long _Perl_pp_floor
.globl __imp__Perl_pp_flop
__imp__Perl_pp_flop:
  .long _Perl_pp_flop
.globl __imp__Perl_pp_fork
__imp__Perl_pp_fork:
  .long _Perl_pp_fork
.globl __imp__Perl_pp_formline
__imp__Perl_pp_formline:
  .long _Perl_pp_formline
.globl __imp__Perl_pp_ftis
__imp__Perl_pp_ftis:
  .long _Perl_pp_ftis
.globl __imp__Perl_pp_ftlink
__imp__Perl_pp_ftlink:
  .long _Perl_pp_ftlink
.globl __imp__Perl_pp_ftrowned
__imp__Perl_pp_ftrowned:
  .long _Perl_pp_ftrowned
.globl __imp__Perl_pp_ftrread
__imp__Perl_pp_ftrread:
  .long _Perl_pp_ftrread
.globl __imp__Perl_pp_fttext
__imp__Perl_pp_fttext:
  .long _Perl_pp_fttext
.globl __imp__Perl_pp_fttty
__imp__Perl_pp_fttty:
  .long _Perl_pp_fttty
.globl __imp__Perl_pp_ge
__imp__Perl_pp_ge:
  .long _Perl_pp_ge
.globl __imp__Perl_pp_gelem
__imp__Perl_pp_gelem:
  .long _Perl_pp_gelem
.globl __imp__Perl_pp_getc
__imp__Perl_pp_getc:
  .long _Perl_pp_getc
.globl __imp__Perl_pp_getlogin
__imp__Perl_pp_getlogin:
  .long _Perl_pp_getlogin
.globl __imp__Perl_pp_getpgrp
__imp__Perl_pp_getpgrp:
  .long _Perl_pp_getpgrp
.globl __imp__Perl_pp_getppid
__imp__Perl_pp_getppid:
  .long _Perl_pp_getppid
.globl __imp__Perl_pp_getpriority
__imp__Perl_pp_getpriority:
  .long _Perl_pp_getpriority
.globl __imp__Perl_pp_ggrent
__imp__Perl_pp_ggrent:
  .long _Perl_pp_ggrent
.globl __imp__Perl_pp_ghostent
__imp__Perl_pp_ghostent:
  .long _Perl_pp_ghostent
.globl __imp__Perl_pp_glob
__imp__Perl_pp_glob:
  .long _Perl_pp_glob
.globl __imp__Perl_pp_gmtime
__imp__Perl_pp_gmtime:
  .long _Perl_pp_gmtime
.globl __imp__Perl_pp_gnetent
__imp__Perl_pp_gnetent:
  .long _Perl_pp_gnetent
.globl __imp__Perl_pp_goto
__imp__Perl_pp_goto:
  .long _Perl_pp_goto
.globl __imp__Perl_pp_gprotoent
__imp__Perl_pp_gprotoent:
  .long _Perl_pp_gprotoent
.globl __imp__Perl_pp_gpwent
__imp__Perl_pp_gpwent:
  .long _Perl_pp_gpwent
.globl __imp__Perl_pp_grepstart
__imp__Perl_pp_grepstart:
  .long _Perl_pp_grepstart
.globl __imp__Perl_pp_grepwhile
__imp__Perl_pp_grepwhile:
  .long _Perl_pp_grepwhile
.globl __imp__Perl_pp_gservent
__imp__Perl_pp_gservent:
  .long _Perl_pp_gservent
.globl __imp__Perl_pp_gt
__imp__Perl_pp_gt:
  .long _Perl_pp_gt
.globl __imp__Perl_pp_gv
__imp__Perl_pp_gv:
  .long _Perl_pp_gv
.globl __imp__Perl_pp_gvsv
__imp__Perl_pp_gvsv:
  .long _Perl_pp_gvsv
.globl __imp__Perl_pp_helem
__imp__Perl_pp_helem:
  .long _Perl_pp_helem
.globl __imp__Perl_pp_helemexistsor
__imp__Perl_pp_helemexistsor:
  .long _Perl_pp_helemexistsor
.globl __imp__Perl_pp_hintseval
__imp__Perl_pp_hintseval:
  .long _Perl_pp_hintseval
.globl __imp__Perl_pp_hslice
__imp__Perl_pp_hslice:
  .long _Perl_pp_hslice
.globl __imp__Perl_pp_i_add
__imp__Perl_pp_i_add:
  .long _Perl_pp_i_add
.globl __imp__Perl_pp_i_divide
__imp__Perl_pp_i_divide:
  .long _Perl_pp_i_divide
.globl __imp__Perl_pp_i_eq
__imp__Perl_pp_i_eq:
  .long _Perl_pp_i_eq
.globl __imp__Perl_pp_i_ge
__imp__Perl_pp_i_ge:
  .long _Perl_pp_i_ge
.globl __imp__Perl_pp_i_gt
__imp__Perl_pp_i_gt:
  .long _Perl_pp_i_gt
.globl __imp__Perl_pp_i_le
__imp__Perl_pp_i_le:
  .long _Perl_pp_i_le
.globl __imp__Perl_pp_i_lt
__imp__Perl_pp_i_lt:
  .long _Perl_pp_i_lt
.globl __imp__Perl_pp_i_modulo
__imp__Perl_pp_i_modulo:
  .long _Perl_pp_i_modulo
.globl __imp__Perl_pp_i_multiply
__imp__Perl_pp_i_multiply:
  .long _Perl_pp_i_multiply
.globl __imp__Perl_pp_i_ncmp
__imp__Perl_pp_i_ncmp:
  .long _Perl_pp_i_ncmp
.globl __imp__Perl_pp_i_ne
__imp__Perl_pp_i_ne:
  .long _Perl_pp_i_ne
.globl __imp__Perl_pp_i_negate
__imp__Perl_pp_i_negate:
  .long _Perl_pp_i_negate
.globl __imp__Perl_pp_i_subtract
__imp__Perl_pp_i_subtract:
  .long _Perl_pp_i_subtract
.globl __imp__Perl_pp_index
__imp__Perl_pp_index:
  .long _Perl_pp_index
.globl __imp__Perl_pp_initfield
__imp__Perl_pp_initfield:
  .long _Perl_pp_initfield
.globl __imp__Perl_pp_int
__imp__Perl_pp_int:
  .long _Perl_pp_int
.globl __imp__Perl_pp_introcv
__imp__Perl_pp_introcv:
  .long _Perl_pp_introcv
.globl __imp__Perl_pp_ioctl
__imp__Perl_pp_ioctl:
  .long _Perl_pp_ioctl
.globl __imp__Perl_pp_is_bool
__imp__Perl_pp_is_bool:
  .long _Perl_pp_is_bool
.globl __imp__Perl_pp_is_tainted
__imp__Perl_pp_is_tainted:
  .long _Perl_pp_is_tainted
.globl __imp__Perl_pp_is_weak
__imp__Perl_pp_is_weak:
  .long _Perl_pp_is_weak
.globl __imp__Perl_pp_isa
__imp__Perl_pp_isa:
  .long _Perl_pp_isa
.globl __imp__Perl_pp_iter
__imp__Perl_pp_iter:
  .long _Perl_pp_iter
.globl __imp__Perl_pp_join
__imp__Perl_pp_join:
  .long _Perl_pp_join
.globl __imp__Perl_pp_kvaslice
__imp__Perl_pp_kvaslice:
  .long _Perl_pp_kvaslice
.globl __imp__Perl_pp_kvhslice
__imp__Perl_pp_kvhslice:
  .long _Perl_pp_kvhslice
.globl __imp__Perl_pp_last
__imp__Perl_pp_last:
  .long _Perl_pp_last
.globl __imp__Perl_pp_lc
__imp__Perl_pp_lc:
  .long _Perl_pp_lc
.globl __imp__Perl_pp_le
__imp__Perl_pp_le:
  .long _Perl_pp_le
.globl __imp__Perl_pp_leave
__imp__Perl_pp_leave:
  .long _Perl_pp_leave
.globl __imp__Perl_pp_leaveeval
__imp__Perl_pp_leaveeval:
  .long _Perl_pp_leaveeval
.globl __imp__Perl_pp_leavegiven
__imp__Perl_pp_leavegiven:
  .long _Perl_pp_leavegiven
.globl __imp__Perl_pp_leaveloop
__imp__Perl_pp_leaveloop:
  .long _Perl_pp_leaveloop
.globl __imp__Perl_pp_leavesub
__imp__Perl_pp_leavesub:
  .long _Perl_pp_leavesub
.globl __imp__Perl_pp_leavesublv
__imp__Perl_pp_leavesublv:
  .long _Perl_pp_leavesublv
.globl __imp__Perl_pp_leavetry
__imp__Perl_pp_leavetry:
  .long _Perl_pp_leavetry
.globl __imp__Perl_pp_leavetrycatch
__imp__Perl_pp_leavetrycatch:
  .long _Perl_pp_leavetrycatch
.globl __imp__Perl_pp_leavewhen
__imp__Perl_pp_leavewhen:
  .long _Perl_pp_leavewhen
.globl __imp__Perl_pp_leavewrite
__imp__Perl_pp_leavewrite:
  .long _Perl_pp_leavewrite
.globl __imp__Perl_pp_left_shift
__imp__Perl_pp_left_shift:
  .long _Perl_pp_left_shift
.globl __imp__Perl_pp_length
__imp__Perl_pp_length:
  .long _Perl_pp_length
.globl __imp__Perl_pp_link
__imp__Perl_pp_link:
  .long _Perl_pp_link
.globl __imp__Perl_pp_list
__imp__Perl_pp_list:
  .long _Perl_pp_list
.globl __imp__Perl_pp_lock
__imp__Perl_pp_lock:
  .long _Perl_pp_lock
.globl __imp__Perl_pp_lslice
__imp__Perl_pp_lslice:
  .long _Perl_pp_lslice
.globl __imp__Perl_pp_lt
__imp__Perl_pp_lt:
  .long _Perl_pp_lt
.globl __imp__Perl_pp_lvavref
__imp__Perl_pp_lvavref:
  .long _Perl_pp_lvavref
.globl __imp__Perl_pp_lvref
__imp__Perl_pp_lvref:
  .long _Perl_pp_lvref
.globl __imp__Perl_pp_lvrefslice
__imp__Perl_pp_lvrefslice:
  .long _Perl_pp_lvrefslice
.globl __imp__Perl_pp_mapwhile
__imp__Perl_pp_mapwhile:
  .long _Perl_pp_mapwhile
.globl __imp__Perl_pp_match
__imp__Perl_pp_match:
  .long _Perl_pp_match
.globl __imp__Perl_pp_method
__imp__Perl_pp_method:
  .long _Perl_pp_method
.globl __imp__Perl_pp_method_named
__imp__Perl_pp_method_named:
  .long _Perl_pp_method_named
.globl __imp__Perl_pp_method_redir
__imp__Perl_pp_method_redir:
  .long _Perl_pp_method_redir
.globl __imp__Perl_pp_method_redir_super
__imp__Perl_pp_method_redir_super:
  .long _Perl_pp_method_redir_super
.globl __imp__Perl_pp_method_super
__imp__Perl_pp_method_super:
  .long _Perl_pp_method_super
.globl __imp__Perl_pp_methstart
__imp__Perl_pp_methstart:
  .long _Perl_pp_methstart
.globl __imp__Perl_pp_mkdir
__imp__Perl_pp_mkdir:
  .long _Perl_pp_mkdir
.globl __imp__Perl_pp_modulo
__imp__Perl_pp_modulo:
  .long _Perl_pp_modulo
.globl __imp__Perl_pp_multiconcat
__imp__Perl_pp_multiconcat:
  .long _Perl_pp_multiconcat
.globl __imp__Perl_pp_multideref
__imp__Perl_pp_multideref:
  .long _Perl_pp_multideref
.globl __imp__Perl_pp_multiply
__imp__Perl_pp_multiply:
  .long _Perl_pp_multiply
.globl __imp__Perl_pp_nbit_and
__imp__Perl_pp_nbit_and:
  .long _Perl_pp_nbit_and
.globl __imp__Perl_pp_nbit_or
__imp__Perl_pp_nbit_or:
  .long _Perl_pp_nbit_or
.globl __imp__Perl_pp_ncmp
__imp__Perl_pp_ncmp:
  .long _Perl_pp_ncmp
.globl __imp__Perl_pp_ncomplement
__imp__Perl_pp_ncomplement:
  .long _Perl_pp_ncomplement
.globl __imp__Perl_pp_ne
__imp__Perl_pp_ne:
  .long _Perl_pp_ne
.globl __imp__Perl_pp_negate
__imp__Perl_pp_negate:
  .long _Perl_pp_negate
.globl __imp__Perl_pp_next
__imp__Perl_pp_next:
  .long _Perl_pp_next
.globl __imp__Perl_pp_nextstate
__imp__Perl_pp_nextstate:
  .long _Perl_pp_nextstate
.globl __imp__Perl_pp_not
__imp__Perl_pp_not:
  .long _Perl_pp_not
.globl __imp__Perl_pp_null
__imp__Perl_pp_null:
  .long _Perl_pp_null
.globl __imp__Perl_pp_oct
__imp__Perl_pp_oct:
  .long _Perl_pp_oct
.globl __imp__Perl_pp_once
__imp__Perl_pp_once:
  .long _Perl_pp_once
.globl __imp__Perl_pp_open
__imp__Perl_pp_open:
  .long _Perl_pp_open
.globl __imp__Perl_pp_open_dir
__imp__Perl_pp_open_dir:
  .long _Perl_pp_open_dir
.globl __imp__Perl_pp_or
__imp__Perl_pp_or:
  .long _Perl_pp_or
.globl __imp__Perl_pp_ord
__imp__Perl_pp_ord:
  .long _Perl_pp_ord
.globl __imp__Perl_pp_pack
__imp__Perl_pp_pack:
  .long _Perl_pp_pack
.globl __imp__Perl_pp_padav
__imp__Perl_pp_padav:
  .long _Perl_pp_padav
.globl __imp__Perl_pp_padcv
__imp__Perl_pp_padcv:
  .long _Perl_pp_padcv
.globl __imp__Perl_pp_padhv
__imp__Perl_pp_padhv:
  .long _Perl_pp_padhv
.globl __imp__Perl_pp_padrange
__imp__Perl_pp_padrange:
  .long _Perl_pp_padrange
.globl __imp__Perl_pp_padsv
__imp__Perl_pp_padsv:
  .long _Perl_pp_padsv
.globl __imp__Perl_pp_padsv_store
__imp__Perl_pp_padsv_store:
  .long _Perl_pp_padsv_store
.globl __imp__Perl_pp_pipe_op
__imp__Perl_pp_pipe_op:
  .long _Perl_pp_pipe_op
.globl __imp__Perl_pp_poptry
__imp__Perl_pp_poptry:
  .long _Perl_pp_poptry
.globl __imp__Perl_pp_pos
__imp__Perl_pp_pos:
  .long _Perl_pp_pos
.globl __imp__Perl_pp_postdec
__imp__Perl_pp_postdec:
  .long _Perl_pp_postdec
.globl __imp__Perl_pp_postinc
__imp__Perl_pp_postinc:
  .long _Perl_pp_postinc
.globl __imp__Perl_pp_pow
__imp__Perl_pp_pow:
  .long _Perl_pp_pow
.globl __imp__Perl_pp_predec
__imp__Perl_pp_predec:
  .long _Perl_pp_predec
.globl __imp__Perl_pp_preinc
__imp__Perl_pp_preinc:
  .long _Perl_pp_preinc
.globl __imp__Perl_pp_print
__imp__Perl_pp_print:
  .long _Perl_pp_print
.globl __imp__Perl_pp_prototype
__imp__Perl_pp_prototype:
  .long _Perl_pp_prototype
.globl __imp__Perl_pp_prtf
__imp__Perl_pp_prtf:
  .long _Perl_pp_prtf
.globl __imp__Perl_pp_push
__imp__Perl_pp_push:
  .long _Perl_pp_push
.globl __imp__Perl_pp_pushdefer
__imp__Perl_pp_pushdefer:
  .long _Perl_pp_pushdefer
.globl __imp__Perl_pp_pushmark
__imp__Perl_pp_pushmark:
  .long _Perl_pp_pushmark
.globl __imp__Perl_pp_qr
__imp__Perl_pp_qr:
  .long _Perl_pp_qr
.globl __imp__Perl_pp_quotemeta
__imp__Perl_pp_quotemeta:
  .long _Perl_pp_quotemeta
.globl __imp__Perl_pp_rand
__imp__Perl_pp_rand:
  .long _Perl_pp_rand
.globl __imp__Perl_pp_range
__imp__Perl_pp_range:
  .long _Perl_pp_range
.globl __imp__Perl_pp_rcatline
__imp__Perl_pp_rcatline:
  .long _Perl_pp_rcatline
.globl __imp__Perl_pp_readdir
__imp__Perl_pp_readdir:
  .long _Perl_pp_readdir
.globl __imp__Perl_pp_readline
__imp__Perl_pp_readline:
  .long _Perl_pp_readline
.globl __imp__Perl_pp_readlink
__imp__Perl_pp_readlink:
  .long _Perl_pp_readlink
.globl __imp__Perl_pp_redo
__imp__Perl_pp_redo:
  .long _Perl_pp_redo
.globl __imp__Perl_pp_ref
__imp__Perl_pp_ref:
  .long _Perl_pp_ref
.globl __imp__Perl_pp_refaddr
__imp__Perl_pp_refaddr:
  .long _Perl_pp_refaddr
.globl __imp__Perl_pp_refassign
__imp__Perl_pp_refassign:
  .long _Perl_pp_refassign
.globl __imp__Perl_pp_refgen
__imp__Perl_pp_refgen:
  .long _Perl_pp_refgen
.globl __imp__Perl_pp_reftype
__imp__Perl_pp_reftype:
  .long _Perl_pp_reftype
.globl __imp__Perl_pp_regcomp
__imp__Perl_pp_regcomp:
  .long _Perl_pp_regcomp
.globl __imp__Perl_pp_regcreset
__imp__Perl_pp_regcreset:
  .long _Perl_pp_regcreset
.globl __imp__Perl_pp_rename
__imp__Perl_pp_rename:
  .long _Perl_pp_rename
.globl __imp__Perl_pp_repeat
__imp__Perl_pp_repeat:
  .long _Perl_pp_repeat
.globl __imp__Perl_pp_require
__imp__Perl_pp_require:
  .long _Perl_pp_require
.globl __imp__Perl_pp_reset
__imp__Perl_pp_reset:
  .long _Perl_pp_reset
.globl __imp__Perl_pp_return
__imp__Perl_pp_return:
  .long _Perl_pp_return
.globl __imp__Perl_pp_reverse
__imp__Perl_pp_reverse:
  .long _Perl_pp_reverse
.globl __imp__Perl_pp_rewinddir
__imp__Perl_pp_rewinddir:
  .long _Perl_pp_rewinddir
.globl __imp__Perl_pp_right_shift
__imp__Perl_pp_right_shift:
  .long _Perl_pp_right_shift
.globl __imp__Perl_pp_rmdir
__imp__Perl_pp_rmdir:
  .long _Perl_pp_rmdir
.globl __imp__Perl_pp_runcv
__imp__Perl_pp_runcv:
  .long _Perl_pp_runcv
.globl __imp__Perl_pp_rv2av
__imp__Perl_pp_rv2av:
  .long _Perl_pp_rv2av
.globl __imp__Perl_pp_rv2cv
__imp__Perl_pp_rv2cv:
  .long _Perl_pp_rv2cv
.globl __imp__Perl_pp_rv2gv
__imp__Perl_pp_rv2gv:
  .long _Perl_pp_rv2gv
.globl __imp__Perl_pp_rv2sv
__imp__Perl_pp_rv2sv:
  .long _Perl_pp_rv2sv
.globl __imp__Perl_pp_sassign
__imp__Perl_pp_sassign:
  .long _Perl_pp_sassign
.globl __imp__Perl_pp_sbit_and
__imp__Perl_pp_sbit_and:
  .long _Perl_pp_sbit_and
.globl __imp__Perl_pp_sbit_or
__imp__Perl_pp_sbit_or:
  .long _Perl_pp_sbit_or
.globl __imp__Perl_pp_schop
__imp__Perl_pp_schop:
  .long _Perl_pp_schop
.globl __imp__Perl_pp_scmp
__imp__Perl_pp_scmp:
  .long _Perl_pp_scmp
.globl __imp__Perl_pp_scomplement
__imp__Perl_pp_scomplement:
  .long _Perl_pp_scomplement
.globl __imp__Perl_pp_seekdir
__imp__Perl_pp_seekdir:
  .long _Perl_pp_seekdir
.globl __imp__Perl_pp_select
__imp__Perl_pp_select:
  .long _Perl_pp_select
.globl __imp__Perl_pp_semctl
__imp__Perl_pp_semctl:
  .long _Perl_pp_semctl
.globl __imp__Perl_pp_semget
__imp__Perl_pp_semget:
  .long _Perl_pp_semget
.globl __imp__Perl_pp_seq
__imp__Perl_pp_seq:
  .long _Perl_pp_seq
.globl __imp__Perl_pp_setpgrp
__imp__Perl_pp_setpgrp:
  .long _Perl_pp_setpgrp
.globl __imp__Perl_pp_setpriority
__imp__Perl_pp_setpriority:
  .long _Perl_pp_setpriority
.globl __imp__Perl_pp_shift
__imp__Perl_pp_shift:
  .long _Perl_pp_shift
.globl __imp__Perl_pp_shmwrite
__imp__Perl_pp_shmwrite:
  .long _Perl_pp_shmwrite
.globl __imp__Perl_pp_shostent
__imp__Perl_pp_shostent:
  .long _Perl_pp_shostent
.globl __imp__Perl_pp_sin
__imp__Perl_pp_sin:
  .long _Perl_pp_sin
.globl __imp__Perl_pp_sle
__imp__Perl_pp_sle:
  .long _Perl_pp_sle
.globl __imp__Perl_pp_sleep
__imp__Perl_pp_sleep:
  .long _Perl_pp_sleep
.globl __imp__Perl_pp_smartmatch
__imp__Perl_pp_smartmatch:
  .long _Perl_pp_smartmatch
.globl __imp__Perl_pp_sne
__imp__Perl_pp_sne:
  .long _Perl_pp_sne
.globl __imp__Perl_pp_sockpair
__imp__Perl_pp_sockpair:
  .long _Perl_pp_sockpair
.globl __imp__Perl_pp_sort
__imp__Perl_pp_sort:
  .long _Perl_pp_sort
.globl __imp__Perl_pp_splice
__imp__Perl_pp_splice:
  .long _Perl_pp_splice
.globl __imp__Perl_pp_split
__imp__Perl_pp_split:
  .long _Perl_pp_split
.globl __imp__Perl_pp_sprintf
__imp__Perl_pp_sprintf:
  .long _Perl_pp_sprintf
.globl __imp__Perl_pp_srand
__imp__Perl_pp_srand:
  .long _Perl_pp_srand
.globl __imp__Perl_pp_srefgen
__imp__Perl_pp_srefgen:
  .long _Perl_pp_srefgen
.globl __imp__Perl_pp_sselect
__imp__Perl_pp_sselect:
  .long _Perl_pp_sselect
.globl __imp__Perl_pp_stat
__imp__Perl_pp_stat:
  .long _Perl_pp_stat
.globl __imp__Perl_pp_stringify
__imp__Perl_pp_stringify:
  .long _Perl_pp_stringify
.globl __imp__Perl_pp_stub
__imp__Perl_pp_stub:
  .long _Perl_pp_stub
.globl __imp__Perl_pp_study
__imp__Perl_pp_study:
  .long _Perl_pp_study
.globl __imp__Perl_pp_subst
__imp__Perl_pp_subst:
  .long _Perl_pp_subst
.globl __imp__Perl_pp_substcont
__imp__Perl_pp_substcont:
  .long _Perl_pp_substcont
.globl __imp__Perl_pp_substr
__imp__Perl_pp_substr:
  .long _Perl_pp_substr
.globl __imp__Perl_pp_subtract
__imp__Perl_pp_subtract:
  .long _Perl_pp_subtract
.globl __imp__Perl_pp_syscall
__imp__Perl_pp_syscall:
  .long _Perl_pp_syscall
.globl __imp__Perl_pp_sysopen
__imp__Perl_pp_sysopen:
  .long _Perl_pp_sysopen
.globl __imp__Perl_pp_sysread
__imp__Perl_pp_sysread:
  .long _Perl_pp_sysread
.globl __imp__Perl_pp_sysseek
__imp__Perl_pp_sysseek:
  .long _Perl_pp_sysseek
.globl __imp__Perl_pp_system
__imp__Perl_pp_system:
  .long _Perl_pp_system
.globl __imp__Perl_pp_syswrite
__imp__Perl_pp_syswrite:
  .long _Perl_pp_syswrite
.globl __imp__Perl_pp_tell
__imp__Perl_pp_tell:
  .long _Perl_pp_tell
.globl __imp__Perl_pp_telldir
__imp__Perl_pp_telldir:
  .long _Perl_pp_telldir
.globl __imp__Perl_pp_tie
__imp__Perl_pp_tie:
  .long _Perl_pp_tie
.globl __imp__Perl_pp_tied
__imp__Perl_pp_tied:
  .long _Perl_pp_tied
.globl __imp__Perl_pp_time
__imp__Perl_pp_time:
  .long _Perl_pp_time
.globl __imp__Perl_pp_tms
__imp__Perl_pp_tms:
  .long _Perl_pp_tms
.globl __imp__Perl_pp_trans
__imp__Perl_pp_trans:
  .long _Perl_pp_trans
.globl __imp__Perl_pp_truncate
__imp__Perl_pp_truncate:
  .long _Perl_pp_truncate
.globl __imp__Perl_pp_uc
__imp__Perl_pp_uc:
  .long _Perl_pp_uc
.globl __imp__Perl_pp_ucfirst
__imp__Perl_pp_ucfirst:
  .long _Perl_pp_ucfirst
.globl __imp__Perl_pp_umask
__imp__Perl_pp_umask:
  .long _Perl_pp_umask
.globl __imp__Perl_pp_undef
__imp__Perl_pp_undef:
  .long _Perl_pp_undef
.globl __imp__Perl_pp_unpack
__imp__Perl_pp_unpack:
  .long _Perl_pp_unpack
.globl __imp__Perl_pp_unshift
__imp__Perl_pp_unshift:
  .long _Perl_pp_unshift
.globl __imp__Perl_pp_unstack
__imp__Perl_pp_unstack:
  .long _Perl_pp_unstack
.globl __imp__Perl_pp_untie
__imp__Perl_pp_untie:
  .long _Perl_pp_untie
.globl __imp__Perl_pp_unweaken
__imp__Perl_pp_unweaken:
  .long _Perl_pp_unweaken
.globl __imp__Perl_pp_vec
__imp__Perl_pp_vec:
  .long _Perl_pp_vec
.globl __imp__Perl_pp_wait
__imp__Perl_pp_wait:
  .long _Perl_pp_wait
.globl __imp__Perl_pp_waitpid
__imp__Perl_pp_waitpid:
  .long _Perl_pp_waitpid
.globl __imp__Perl_pp_wantarray
__imp__Perl_pp_wantarray:
  .long _Perl_pp_wantarray
.globl __imp__Perl_pp_warn
__imp__Perl_pp_warn:
  .long _Perl_pp_warn
.globl __imp__Perl_pp_weaken
__imp__Perl_pp_weaken:
  .long _Perl_pp_weaken
.globl __imp__Perl_pp_xor
__imp__Perl_pp_xor:
  .long _Perl_pp_xor
.globl __imp__Perl_pregfree2
__imp__Perl_pregfree2:
  .long _Perl_pregfree2
.globl __imp__Perl_prepare_export_lexical
__imp__Perl_prepare_export_lexical:
  .long _Perl_prepare_export_lexical
.globl __imp__Perl_prescan_version
__imp__Perl_prescan_version:
  .long _Perl_prescan_version
.globl __imp__Perl_push_scope
__imp__Perl_push_scope:
  .long _Perl_push_scope
.globl __imp__Perl_pv_escape
__imp__Perl_pv_escape:
  .long _Perl_pv_escape
.globl __imp__Perl_pv_pretty
__imp__Perl_pv_pretty:
  .long _Perl_pv_pretty
.globl __imp__Perl_pv_uni_display
__imp__Perl_pv_uni_display:
  .long _Perl_pv_uni_display
.globl __imp__Perl_qerror
__imp__Perl_qerror:
  .long _Perl_qerror
.globl __imp__Perl_rcpv_copy
__imp__Perl_rcpv_copy:
  .long _Perl_rcpv_copy
.globl __imp__Perl_rcpv_free
__imp__Perl_rcpv_free:
  .long _Perl_rcpv_free
.globl __imp__Perl_rcpv_new
__imp__Perl_rcpv_new:
  .long _Perl_rcpv_new
.globl __imp__Perl_re_compile
__imp__Perl_re_compile:
  .long _Perl_re_compile
.globl __imp__Perl_re_intuit_start
__imp__Perl_re_intuit_start:
  .long _Perl_re_intuit_start
.globl __imp__Perl_re_intuit_string
__imp__Perl_re_intuit_string:
  .long _Perl_re_intuit_string
.globl __imp__Perl_re_op_compile
__imp__Perl_re_op_compile:
  .long _Perl_re_op_compile
.globl __imp__Perl_refcounted_he_chain_2hv
__imp__Perl_refcounted_he_chain_2hv:
  .long _Perl_refcounted_he_chain_2hv
.globl __imp__Perl_refcounted_he_fetch_pv
__imp__Perl_refcounted_he_fetch_pv:
  .long _Perl_refcounted_he_fetch_pv
.globl __imp__Perl_refcounted_he_fetch_pvn
__imp__Perl_refcounted_he_fetch_pvn:
  .long _Perl_refcounted_he_fetch_pvn
.globl __imp__Perl_refcounted_he_free
__imp__Perl_refcounted_he_free:
  .long _Perl_refcounted_he_free
.globl __imp__Perl_refcounted_he_inc
__imp__Perl_refcounted_he_inc:
  .long _Perl_refcounted_he_inc
.globl __imp__Perl_refcounted_he_new_pvn
__imp__Perl_refcounted_he_new_pvn:
  .long _Perl_refcounted_he_new_pvn
.globl __imp__Perl_refcounted_he_new_sv
__imp__Perl_refcounted_he_new_sv:
  .long _Perl_refcounted_he_new_sv
.globl __imp__Perl_reg_add_data
__imp__Perl_reg_add_data:
  .long _Perl_reg_add_data
.globl __imp__Perl_reg_named_buff
__imp__Perl_reg_named_buff:
  .long _Perl_reg_named_buff
.globl __imp__Perl_reg_named_buff_iter
__imp__Perl_reg_named_buff_iter:
  .long _Perl_reg_named_buff_iter
.globl __imp__Perl_reg_numbered_buff_fetch
__imp__Perl_reg_numbered_buff_fetch:
  .long _Perl_reg_numbered_buff_fetch
.globl __imp__Perl_reg_numbered_buff_length
__imp__Perl_reg_numbered_buff_length:
  .long _Perl_reg_numbered_buff_length
.globl __imp__Perl_reg_numbered_buff_store
__imp__Perl_reg_numbered_buff_store:
  .long _Perl_reg_numbered_buff_store
.globl __imp__Perl_reg_qr_package
__imp__Perl_reg_qr_package:
  .long _Perl_reg_qr_package
.globl __imp__Perl_reg_temp_copy
__imp__Perl_reg_temp_copy:
  .long _Perl_reg_temp_copy
.globl __imp__Perl_regcurly
__imp__Perl_regcurly:
  .long _Perl_regcurly
.globl __imp__Perl_regexec_flags
__imp__Perl_regexec_flags:
  .long _Perl_regexec_flags
.globl __imp__Perl_regfree_internal
__imp__Perl_regfree_internal:
  .long _Perl_regfree_internal
.globl __imp__Perl_repeatcpy
__imp__Perl_repeatcpy:
  .long _Perl_repeatcpy
.globl __imp__Perl_report_evil_fh
__imp__Perl_report_evil_fh:
  .long _Perl_report_evil_fh
.globl __imp__Perl_report_redefined_cv
__imp__Perl_report_redefined_cv:
  .long _Perl_report_redefined_cv
.globl __imp__Perl_report_uninit
__imp__Perl_report_uninit:
  .long _Perl_report_uninit
.globl __imp__Perl_report_wrongway_fh
__imp__Perl_report_wrongway_fh:
  .long _Perl_report_wrongway_fh
.globl __imp__Perl_require_pv
__imp__Perl_require_pv:
  .long _Perl_require_pv
.globl __imp__Perl_resume_compcv
__imp__Perl_resume_compcv:
  .long _Perl_resume_compcv
.globl __imp__Perl_rninstr
__imp__Perl_rninstr:
  .long _Perl_rninstr
.globl __imp__Perl_rpeep
__imp__Perl_rpeep:
  .long _Perl_rpeep
.globl __imp__Perl_rpp_obliterate_stack_to
__imp__Perl_rpp_obliterate_stack_to:
  .long _Perl_rpp_obliterate_stack_to
.globl __imp__Perl_rsignal
__imp__Perl_rsignal:
  .long _Perl_rsignal
.globl __imp__Perl_rsignal_restore
__imp__Perl_rsignal_restore:
  .long _Perl_rsignal_restore
.globl __imp__Perl_rsignal_save
__imp__Perl_rsignal_save:
  .long _Perl_rsignal_save
.globl __imp__Perl_rsignal_state
__imp__Perl_rsignal_state:
  .long _Perl_rsignal_state
.globl __imp__Perl_runops_debug
__imp__Perl_runops_debug:
  .long _Perl_runops_debug
.globl __imp__Perl_runops_standard
__imp__Perl_runops_standard:
  .long _Perl_runops_standard
.globl __imp__Perl_rv2cv_op_cv
__imp__Perl_rv2cv_op_cv:
  .long _Perl_rv2cv_op_cv
.globl __imp__Perl_rxres_save
__imp__Perl_rxres_save:
  .long _Perl_rxres_save
.globl __imp__Perl_safesyscalloc
__imp__Perl_safesyscalloc:
  .long _Perl_safesyscalloc
.globl __imp__Perl_safesysfree
__imp__Perl_safesysfree:
  .long _Perl_safesysfree
.globl __imp__Perl_safesysmalloc
__imp__Perl_safesysmalloc:
  .long _Perl_safesysmalloc
.globl __imp__Perl_safesysrealloc
__imp__Perl_safesysrealloc:
  .long _Perl_safesysrealloc
.globl __imp__Perl_save_I16
__imp__Perl_save_I16:
  .long _Perl_save_I16
.globl __imp__Perl_save_I32
__imp__Perl_save_I32:
  .long _Perl_save_I32
.globl __imp__Perl_save_I8
__imp__Perl_save_I8:
  .long _Perl_save_I8
.globl __imp__Perl_save_adelete
__imp__Perl_save_adelete:
  .long _Perl_save_adelete
.globl __imp__Perl_save_aelem_flags
__imp__Perl_save_aelem_flags:
  .long _Perl_save_aelem_flags
.globl __imp__Perl_save_alloc
__imp__Perl_save_alloc:
  .long _Perl_save_alloc
.globl __imp__Perl_save_ary
__imp__Perl_save_ary:
  .long _Perl_save_ary
.globl __imp__Perl_save_bool
__imp__Perl_save_bool:
  .long _Perl_save_bool
.globl __imp__Perl_save_clearsv
__imp__Perl_save_clearsv:
  .long _Perl_save_clearsv
.globl __imp__Perl_save_delete
__imp__Perl_save_delete:
  .long _Perl_save_delete
.globl __imp__Perl_save_destructor_x
__imp__Perl_save_destructor_x:
  .long _Perl_save_destructor_x
.globl __imp__Perl_save_generic_pvref
__imp__Perl_save_generic_pvref:
  .long _Perl_save_generic_pvref
.globl __imp__Perl_save_generic_svref
__imp__Perl_save_generic_svref:
  .long _Perl_save_generic_svref
.globl __imp__Perl_save_gp
__imp__Perl_save_gp:
  .long _Perl_save_gp
.globl __imp__Perl_save_hash
__imp__Perl_save_hash:
  .long _Perl_save_hash
.globl __imp__Perl_save_hdelete
__imp__Perl_save_hdelete:
  .long _Perl_save_hdelete
.globl __imp__Perl_save_helem_flags
__imp__Perl_save_helem_flags:
  .long _Perl_save_helem_flags
.globl __imp__Perl_save_hints
__imp__Perl_save_hints:
  .long _Perl_save_hints
.globl __imp__Perl_save_int
__imp__Perl_save_int:
  .long _Perl_save_int
.globl __imp__Perl_save_item
__imp__Perl_save_item:
  .long _Perl_save_item
.globl __imp__Perl_save_iv
__imp__Perl_save_iv:
  .long _Perl_save_iv
.globl __imp__Perl_save_padsv_and_mortalize
__imp__Perl_save_padsv_and_mortalize:
  .long _Perl_save_padsv_and_mortalize
.globl __imp__Perl_save_pptr
__imp__Perl_save_pptr:
  .long _Perl_save_pptr
.globl __imp__Perl_save_pushptr
__imp__Perl_save_pushptr:
  .long _Perl_save_pushptr
.globl __imp__Perl_save_pushptrptr
__imp__Perl_save_pushptrptr:
  .long _Perl_save_pushptrptr
.globl __imp__Perl_save_re_context
__imp__Perl_save_re_context:
  .long _Perl_save_re_context
.globl __imp__Perl_save_scalar
__imp__Perl_save_scalar:
  .long _Perl_save_scalar
.globl __imp__Perl_save_set_svflags
__imp__Perl_save_set_svflags:
  .long _Perl_save_set_svflags
.globl __imp__Perl_save_sptr
__imp__Perl_save_sptr:
  .long _Perl_save_sptr
.globl __imp__Perl_save_strlen
__imp__Perl_save_strlen:
  .long _Perl_save_strlen
.globl __imp__Perl_save_vptr
__imp__Perl_save_vptr:
  .long _Perl_save_vptr
.globl __imp__Perl_savesharedpv
__imp__Perl_savesharedpv:
  .long _Perl_savesharedpv
.globl __imp__Perl_savestack_grow_cnt
__imp__Perl_savestack_grow_cnt:
  .long _Perl_savestack_grow_cnt
.globl __imp__Perl_savetmps
__imp__Perl_savetmps:
  .long _Perl_savetmps
.globl __imp__Perl_sawparens
__imp__Perl_sawparens:
  .long _Perl_sawparens
.globl __imp__Perl_scalar
__imp__Perl_scalar:
  .long _Perl_scalar
.globl __imp__Perl_scan_commit
__imp__Perl_scan_commit:
  .long _Perl_scan_commit
.globl __imp__Perl_scan_num
__imp__Perl_scan_num:
  .long _Perl_scan_num
.globl __imp__Perl_scan_version
__imp__Perl_scan_version:
  .long _Perl_scan_version
.globl __imp__Perl_scan_vstring
__imp__Perl_scan_vstring:
  .long _Perl_scan_vstring
.globl __imp__Perl_seed
__imp__Perl_seed:
  .long _Perl_seed
.globl __imp__Perl_set_caret_X
__imp__Perl_set_caret_X:
  .long _Perl_set_caret_X
.globl __imp__Perl_set_numeric_standard
__imp__Perl_set_numeric_standard:
  .long _Perl_set_numeric_standard
.globl __imp__Perl_set_numeric_underlying
__imp__Perl_set_numeric_underlying:
  .long _Perl_set_numeric_underlying
.globl __imp__Perl_setdefout
__imp__Perl_setdefout:
  .long _Perl_setdefout
.globl __imp__Perl_setfd_cloexec_or_inhexec_by_sysfdness
__imp__Perl_setfd_cloexec_or_inhexec_by_sysfdness:
  .long _Perl_setfd_cloexec_or_inhexec_by_sysfdness
.globl __imp__Perl_setfd_inhexec_for_sysfd
__imp__Perl_setfd_inhexec_for_sysfd:
  .long _Perl_setfd_inhexec_for_sysfd
.globl __imp__Perl_share_hek
__imp__Perl_share_hek:
  .long _Perl_share_hek
.globl __imp__Perl_sighandler
__imp__Perl_sighandler:
  .long _Perl_sighandler
.globl __imp__Perl_sighandler1
__imp__Perl_sighandler1:
  .long _Perl_sighandler1
.globl __imp__Perl_sighandler3
__imp__Perl_sighandler3:
  .long _Perl_sighandler3
.globl __imp__Perl_softref2xv
__imp__Perl_softref2xv:
  .long _Perl_softref2xv
.globl __imp__Perl_ssc_init
__imp__Perl_ssc_init:
  .long _Perl_ssc_init
.globl __imp__Perl_stack_grow
__imp__Perl_stack_grow:
  .long _Perl_stack_grow
.globl __imp__Perl_start_glob
__imp__Perl_start_glob:
  .long _Perl_start_glob
.globl __imp__Perl_start_subparse
__imp__Perl_start_subparse:
  .long _Perl_start_subparse
.globl __imp__Perl_study_chunk
__imp__Perl_study_chunk:
  .long _Perl_study_chunk
.globl __imp__Perl_sub_crush_depth
__imp__Perl_sub_crush_depth:
  .long _Perl_sub_crush_depth
.globl __imp__Perl_suspend_compcv
__imp__Perl_suspend_compcv:
  .long _Perl_suspend_compcv
.globl __imp__Perl_sv_2bool_flags
__imp__Perl_sv_2bool_flags:
  .long _Perl_sv_2bool_flags
.globl __imp__Perl_sv_2cv
__imp__Perl_sv_2cv:
  .long _Perl_sv_2cv
.globl __imp__Perl_sv_2io
__imp__Perl_sv_2io:
  .long _Perl_sv_2io
.globl __imp__Perl_sv_2iv_flags
__imp__Perl_sv_2iv_flags:
  .long _Perl_sv_2iv_flags
.globl __imp__Perl_sv_2mortal
__imp__Perl_sv_2mortal:
  .long _Perl_sv_2mortal
.globl __imp__Perl_sv_2num
__imp__Perl_sv_2num:
  .long _Perl_sv_2num
.globl __imp__Perl_sv_2nv_flags
__imp__Perl_sv_2nv_flags:
  .long _Perl_sv_2nv_flags
.globl __imp__Perl_sv_2pv_flags
__imp__Perl_sv_2pv_flags:
  .long _Perl_sv_2pv_flags
.globl __imp__Perl_sv_2pvbyte_flags
__imp__Perl_sv_2pvbyte_flags:
  .long _Perl_sv_2pvbyte_flags
.globl __imp__Perl_sv_2pvutf8_flags
__imp__Perl_sv_2pvutf8_flags:
  .long _Perl_sv_2pvutf8_flags
.globl __imp__Perl_sv_2uv_flags
__imp__Perl_sv_2uv_flags:
  .long _Perl_sv_2uv_flags
.globl __imp__Perl_sv_add_backref
__imp__Perl_sv_add_backref:
  .long _Perl_sv_add_backref
.globl __imp__Perl_sv_backoff
__imp__Perl_sv_backoff:
  .long _Perl_sv_backoff
.globl __imp__Perl_sv_bless
__imp__Perl_sv_bless:
  .long _Perl_sv_bless
.globl __imp__Perl_sv_catpv
__imp__Perl_sv_catpv:
  .long _Perl_sv_catpv
.globl __imp__Perl_sv_catpvf
__imp__Perl_sv_catpvf:
  .long _Perl_sv_catpvf
.globl __imp__Perl_sv_catpvn_flags
__imp__Perl_sv_catpvn_flags:
  .long _Perl_sv_catpvn_flags
.globl __imp__Perl_sv_catsv_flags
__imp__Perl_sv_catsv_flags:
  .long _Perl_sv_catsv_flags
.globl __imp__Perl_sv_chop
__imp__Perl_sv_chop:
  .long _Perl_sv_chop
.globl __imp__Perl_sv_clean_all
__imp__Perl_sv_clean_all:
  .long _Perl_sv_clean_all
.globl __imp__Perl_sv_clean_objs
__imp__Perl_sv_clean_objs:
  .long _Perl_sv_clean_objs
.globl __imp__Perl_sv_clear
__imp__Perl_sv_clear:
  .long _Perl_sv_clear
.globl __imp__Perl_sv_cmp
__imp__Perl_sv_cmp:
  .long _Perl_sv_cmp
.globl __imp__Perl_sv_cmp_flags
__imp__Perl_sv_cmp_flags:
  .long _Perl_sv_cmp_flags
.globl __imp__Perl_sv_cmp_locale
__imp__Perl_sv_cmp_locale:
  .long _Perl_sv_cmp_locale
.globl __imp__Perl_sv_cmp_locale_flags
__imp__Perl_sv_cmp_locale_flags:
  .long _Perl_sv_cmp_locale_flags
.globl __imp__Perl_sv_collxfrm_flags
__imp__Perl_sv_collxfrm_flags:
  .long _Perl_sv_collxfrm_flags
.globl __imp__Perl_sv_copypv_flags
__imp__Perl_sv_copypv_flags:
  .long _Perl_sv_copypv_flags
.globl __imp__Perl_sv_dec
__imp__Perl_sv_dec:
  .long _Perl_sv_dec
.globl __imp__Perl_sv_dec_nomg
__imp__Perl_sv_dec_nomg:
  .long _Perl_sv_dec_nomg
.globl __imp__Perl_sv_del_backref
__imp__Perl_sv_del_backref:
  .long _Perl_sv_del_backref
.globl __imp__Perl_sv_derived_from
__imp__Perl_sv_derived_from:
  .long _Perl_sv_derived_from
.globl __imp__Perl_sv_derived_from_hv
__imp__Perl_sv_derived_from_hv:
  .long _Perl_sv_derived_from_hv
.globl __imp__Perl_sv_derived_from_pvn
__imp__Perl_sv_derived_from_pvn:
  .long _Perl_sv_derived_from_pvn
.globl __imp__Perl_sv_destroyable
__imp__Perl_sv_destroyable:
  .long _Perl_sv_destroyable
.globl __imp__Perl_sv_eq_flags
__imp__Perl_sv_eq_flags:
  .long _Perl_sv_eq_flags
.globl __imp__Perl_sv_force_normal_flags
__imp__Perl_sv_force_normal_flags:
  .long _Perl_sv_force_normal_flags
.globl __imp__Perl_sv_free2
__imp__Perl_sv_free2:
  .long _Perl_sv_free2
.globl __imp__Perl_sv_free_arenas
__imp__Perl_sv_free_arenas:
  .long _Perl_sv_free_arenas
.globl __imp__Perl_sv_gets
__imp__Perl_sv_gets:
  .long _Perl_sv_gets
.globl __imp__Perl_sv_grow
__imp__Perl_sv_grow:
  .long _Perl_sv_grow
.globl __imp__Perl_sv_grow_fresh
__imp__Perl_sv_grow_fresh:
  .long _Perl_sv_grow_fresh
.globl __imp__Perl_sv_inc
__imp__Perl_sv_inc:
  .long _Perl_sv_inc
.globl __imp__Perl_sv_inc_nomg
__imp__Perl_sv_inc_nomg:
  .long _Perl_sv_inc_nomg
.globl __imp__Perl_sv_insert_flags
__imp__Perl_sv_insert_flags:
  .long _Perl_sv_insert_flags
.globl __imp__Perl_sv_isa_sv
__imp__Perl_sv_isa_sv:
  .long _Perl_sv_isa_sv
.globl __imp__Perl_sv_isobject
__imp__Perl_sv_isobject:
  .long _Perl_sv_isobject
.globl __imp__Perl_sv_kill_backrefs
__imp__Perl_sv_kill_backrefs:
  .long _Perl_sv_kill_backrefs
.globl __imp__Perl_sv_len
__imp__Perl_sv_len:
  .long _Perl_sv_len
.globl __imp__Perl_sv_len_utf8
__imp__Perl_sv_len_utf8:
  .long _Perl_sv_len_utf8
.globl __imp__Perl_sv_len_utf8_nomg
__imp__Perl_sv_len_utf8_nomg:
  .long _Perl_sv_len_utf8_nomg
.globl __imp__Perl_sv_magic
__imp__Perl_sv_magic:
  .long _Perl_sv_magic
.globl __imp__Perl_sv_magicext
__imp__Perl_sv_magicext:
  .long _Perl_sv_magicext
.globl __imp__Perl_sv_magicext_mglob
__imp__Perl_sv_magicext_mglob:
  .long _Perl_sv_magicext_mglob
.globl __imp__Perl_sv_mortalcopy_flags
__imp__Perl_sv_mortalcopy_flags:
  .long _Perl_sv_mortalcopy_flags
.globl __imp__Perl_sv_newmortal
__imp__Perl_sv_newmortal:
  .long _Perl_sv_newmortal
.globl __imp__Perl_sv_nosharing
__imp__Perl_sv_nosharing:
  .long _Perl_sv_nosharing
.globl __imp__Perl_sv_nounlocking
__imp__Perl_sv_nounlocking:
  .long _Perl_sv_nounlocking
.globl __imp__Perl_sv_pos_b2u_flags
__imp__Perl_sv_pos_b2u_flags:
  .long _Perl_sv_pos_b2u_flags
.globl __imp__Perl_sv_pos_u2b_flags
__imp__Perl_sv_pos_u2b_flags:
  .long _Perl_sv_pos_u2b_flags
.globl __imp__Perl_sv_pvbyten_force
__imp__Perl_sv_pvbyten_force:
  .long _Perl_sv_pvbyten_force
.globl __imp__Perl_sv_pvn_force_flags
__imp__Perl_sv_pvn_force_flags:
  .long _Perl_sv_pvn_force_flags
.globl __imp__Perl_sv_pvutf8n_force
__imp__Perl_sv_pvutf8n_force:
  .long _Perl_sv_pvutf8n_force
.globl __imp__Perl_sv_ref
__imp__Perl_sv_ref:
  .long _Perl_sv_ref
.globl __imp__Perl_sv_reftype
__imp__Perl_sv_reftype:
  .long _Perl_sv_reftype
.globl __imp__Perl_sv_replace
__imp__Perl_sv_replace:
  .long _Perl_sv_replace
.globl __imp__Perl_sv_resetpvn
__imp__Perl_sv_resetpvn:
  .long _Perl_sv_resetpvn
.globl __imp__Perl_sv_rvunweaken
__imp__Perl_sv_rvunweaken:
  .long _Perl_sv_rvunweaken
.globl __imp__Perl_sv_rvweaken
__imp__Perl_sv_rvweaken:
  .long _Perl_sv_rvweaken
.globl __imp__Perl_sv_set_undef
__imp__Perl_sv_set_undef:
  .long _Perl_sv_set_undef
.globl __imp__Perl_sv_sethek
__imp__Perl_sv_sethek:
  .long _Perl_sv_sethek
.globl __imp__Perl_sv_setiv
__imp__Perl_sv_setiv:
  .long _Perl_sv_setiv
.globl __imp__Perl_sv_setiv_mg
__imp__Perl_sv_setiv_mg:
  .long _Perl_sv_setiv_mg
.globl __imp__Perl_sv_setnv
__imp__Perl_sv_setnv:
  .long _Perl_sv_setnv
.globl __imp__Perl_sv_setnv_mg
__imp__Perl_sv_setnv_mg:
  .long _Perl_sv_setnv_mg
.globl __imp__Perl_sv_setpv
__imp__Perl_sv_setpv:
  .long _Perl_sv_setpv
.globl __imp__Perl_sv_setpv_bufsize
__imp__Perl_sv_setpv_bufsize:
  .long _Perl_sv_setpv_bufsize
.globl __imp__Perl_sv_setpv_mg
__imp__Perl_sv_setpv_mg:
  .long _Perl_sv_setpv_mg
.globl __imp__Perl_sv_setpvf
__imp__Perl_sv_setpvf:
  .long _Perl_sv_setpvf
.globl __imp__Perl_sv_setpvf_mg
__imp__Perl_sv_setpvf_mg:
  .long _Perl_sv_setpvf_mg
.globl __imp__Perl_sv_setpvn
__imp__Perl_sv_setpvn:
  .long _Perl_sv_setpvn
.globl __imp__Perl_sv_setpvn_fresh
__imp__Perl_sv_setpvn_fresh:
  .long _Perl_sv_setpvn_fresh
.globl __imp__Perl_sv_setrv_inc
__imp__Perl_sv_setrv_inc:
  .long _Perl_sv_setrv_inc
.globl __imp__Perl_sv_setrv_noinc
__imp__Perl_sv_setrv_noinc:
  .long _Perl_sv_setrv_noinc
.globl __imp__Perl_sv_setrv_noinc_mg
__imp__Perl_sv_setrv_noinc_mg:
  .long _Perl_sv_setrv_noinc_mg
.globl __imp__Perl_sv_setsv_cow
__imp__Perl_sv_setsv_cow:
  .long _Perl_sv_setsv_cow
.globl __imp__Perl_sv_setsv_flags
__imp__Perl_sv_setsv_flags:
  .long _Perl_sv_setsv_flags
.globl __imp__Perl_sv_setsv_mg
__imp__Perl_sv_setsv_mg:
  .long _Perl_sv_setsv_mg
.globl __imp__Perl_sv_setuv
__imp__Perl_sv_setuv:
  .long _Perl_sv_setuv
.globl __imp__Perl_sv_setuv_mg
__imp__Perl_sv_setuv_mg:
  .long _Perl_sv_setuv_mg
.globl __imp__Perl_sv_streq_flags
__imp__Perl_sv_streq_flags:
  .long _Perl_sv_streq_flags
.globl __imp__Perl_sv_tainted
__imp__Perl_sv_tainted:
  .long _Perl_sv_tainted
.globl __imp__Perl_sv_uni_display
__imp__Perl_sv_uni_display:
  .long _Perl_sv_uni_display
.globl __imp__Perl_sv_unmagic
__imp__Perl_sv_unmagic:
  .long _Perl_sv_unmagic
.globl __imp__Perl_sv_unref_flags
__imp__Perl_sv_unref_flags:
  .long _Perl_sv_unref_flags
.globl __imp__Perl_sv_untaint
__imp__Perl_sv_untaint:
  .long _Perl_sv_untaint
.globl __imp__Perl_sv_upgrade
__imp__Perl_sv_upgrade:
  .long _Perl_sv_upgrade
.globl __imp__Perl_sv_usepvn_flags
__imp__Perl_sv_usepvn_flags:
  .long _Perl_sv_usepvn_flags
.globl __imp__Perl_sv_utf8_decode
__imp__Perl_sv_utf8_decode:
  .long _Perl_sv_utf8_decode
.globl __imp__Perl_sv_utf8_downgrade_flags
__imp__Perl_sv_utf8_downgrade_flags:
  .long _Perl_sv_utf8_downgrade_flags
.globl __imp__Perl_sv_utf8_encode
__imp__Perl_sv_utf8_encode:
  .long _Perl_sv_utf8_encode
.globl __imp__Perl_sv_utf8_upgrade_flags_grow
__imp__Perl_sv_utf8_upgrade_flags_grow:
  .long _Perl_sv_utf8_upgrade_flags_grow
.globl __imp__Perl_sv_vsetpvfn
__imp__Perl_sv_vsetpvfn:
  .long _Perl_sv_vsetpvfn
.globl __imp__Perl_sys_init3
__imp__Perl_sys_init3:
  .long _Perl_sys_init3
.globl __imp__Perl_sys_intern_clear
__imp__Perl_sys_intern_clear:
  .long _Perl_sys_intern_clear
.globl __imp__Perl_sys_intern_init
__imp__Perl_sys_intern_init:
  .long _Perl_sys_intern_init
.globl __imp__Perl_sys_term
__imp__Perl_sys_term:
  .long _Perl_sys_term
.globl __imp__Perl_taint_env
__imp__Perl_taint_env:
  .long _Perl_taint_env
.globl __imp__Perl_taint_proper
__imp__Perl_taint_proper:
  .long _Perl_taint_proper
.globl __imp__Perl_tied_method
__imp__Perl_tied_method:
  .long _Perl_tied_method
.globl __imp__Perl_tmps_grow_p
__imp__Perl_tmps_grow_p:
  .long _Perl_tmps_grow_p
.globl __imp__Perl_translate_substr_offsets
__imp__Perl_translate_substr_offsets:
  .long _Perl_translate_substr_offsets
.globl __imp__Perl_try_amagic_bin
__imp__Perl_try_amagic_bin:
  .long _Perl_try_amagic_bin
.globl __imp__Perl_try_amagic_un
__imp__Perl_try_amagic_un:
  .long _Perl_try_amagic_un
.globl __imp__Perl_unimplemented_op
__imp__Perl_unimplemented_op:
  .long _Perl_unimplemented_op
.globl __imp__Perl_unshare_hek
__imp__Perl_unshare_hek:
  .long _Perl_unshare_hek
.globl __imp__Perl_upg_version
__imp__Perl_upg_version:
  .long _Perl_upg_version
.globl __imp__Perl_utf16_to_utf8_base
__imp__Perl_utf16_to_utf8_base:
  .long _Perl_utf16_to_utf8_base
.globl __imp__Perl_utf8_length
__imp__Perl_utf8_length:
  .long _Perl_utf8_length
.globl __imp__Perl_utf8_to_bytes
__imp__Perl_utf8_to_bytes:
  .long _Perl_utf8_to_bytes
.globl __imp__Perl_utilize
__imp__Perl_utilize:
  .long _Perl_utilize
.globl __imp__Perl_uvoffuni_to_utf8_flags_msgs
__imp__Perl_uvoffuni_to_utf8_flags_msgs:
  .long _Perl_uvoffuni_to_utf8_flags_msgs
.globl __imp__Perl_validate_proto
__imp__Perl_validate_proto:
  .long _Perl_validate_proto
.globl __imp__Perl_varname
__imp__Perl_varname:
  .long _Perl_varname
.globl __imp__Perl_vcmp
__imp__Perl_vcmp:
  .long _Perl_vcmp
.globl __imp__Perl_vcroak
__imp__Perl_vcroak:
  .long _Perl_vcroak
.globl __imp__Perl_vivify_defelem
__imp__Perl_vivify_defelem:
  .long _Perl_vivify_defelem
.globl __imp__Perl_vivify_ref
__imp__Perl_vivify_ref:
  .long _Perl_vivify_ref
.globl __imp__Perl_vmess
__imp__Perl_vmess:
  .long _Perl_vmess
.globl __imp__Perl_vnewSVpvf
__imp__Perl_vnewSVpvf:
  .long _Perl_vnewSVpvf
.globl __imp__Perl_vnormal
__imp__Perl_vnormal:
  .long _Perl_vnormal
.globl __imp__Perl_vnumify
__imp__Perl_vnumify:
  .long _Perl_vnumify
.globl __imp__Perl_vstringify
__imp__Perl_vstringify:
  .long _Perl_vstringify
.globl __imp__Perl_wait4pid
__imp__Perl_wait4pid:
  .long _Perl_wait4pid
.globl __imp__Perl_warn
__imp__Perl_warn:
  .long _Perl_warn
.globl __imp__Perl_warn_elem_scalar_context
__imp__Perl_warn_elem_scalar_context:
  .long _Perl_warn_elem_scalar_context
.globl __imp__Perl_warn_problematic_locale
__imp__Perl_warn_problematic_locale:
  .long _Perl_warn_problematic_locale
.globl __imp__Perl_warn_sv
__imp__Perl_warn_sv:
  .long _Perl_warn_sv
.globl __imp__Perl_warner
__imp__Perl_warner:
  .long _Perl_warner
.globl __imp__Perl_was_lvalue_sub
__imp__Perl_was_lvalue_sub:
  .long _Perl_was_lvalue_sub
.globl __imp__Perl_whichsig_pvn
__imp__Perl_whichsig_pvn:
  .long _Perl_whichsig_pvn
.globl __imp__Perl_write_to_stderr
__imp__Perl_write_to_stderr:
  .long _Perl_write_to_stderr
.globl __imp__Perl_xs_boot_epilog
__imp__Perl_xs_boot_epilog:
  .long _Perl_xs_boot_epilog
.globl __imp__Perl_xs_handshake
__imp__Perl_xs_handshake:
  .long _Perl_xs_handshake
.globl __imp__Perl_yyerror
__imp__Perl_yyerror:
  .long _Perl_yyerror
.globl __imp__Perl_yyerror_pv
__imp__Perl_yyerror_pv:
  .long _Perl_yyerror_pv
.globl __imp__Perl_yylex
__imp__Perl_yylex:
  .long _Perl_yylex
.globl __imp__Perl_yyparse
__imp__Perl_yyparse:
  .long _Perl_yyparse
.globl __imp__Perl_yyquit
__imp__Perl_yyquit:
  .long _Perl_yyquit
.globl __imp__Perl_yyunlex
__imp__Perl_yyunlex:
  .long _Perl_yyunlex
.globl __imp__win32_closesocket
__imp__win32_closesocket:
  .long _win32_closesocket
.globl __imp__win32_croak_not_implemented
__imp__win32_croak_not_implemented:
  .long _win32_croak_not_implemented
.globl __imp__win32_get_errno
__imp__win32_get_errno:
  .long _win32_get_errno
.globl __imp__win32_get_privlib
__imp__win32_get_privlib:
  .long _win32_get_privlib
.globl __imp__win32_get_sitelib
__imp__win32_get_sitelib:
  .long _win32_get_sitelib
.globl __imp__win32_gethostbyname
__imp__win32_gethostbyname:
  .long _win32_gethostbyname
.globl __imp__win32_getprotobynumber
__imp__win32_getprotobynumber:
  .long _win32_getprotobynumber
.globl __imp__win32_getservbyport
__imp__win32_getservbyport:
  .long _win32_getservbyport
.globl __imp__win32_htonl
__imp__win32_htonl:
  .long _win32_htonl
.globl __imp__win32_htons
__imp__win32_htons:
  .long _win32_htons
.globl __imp__win32_ntohl
__imp__win32_ntohl:
  .long _win32_ntohl
.globl __imp__win32_ntohs
__imp__win32_ntohs:
  .long _win32_ntohs
.globl __imp__win32_recv
__imp__win32_recv:
  .long _win32_recv
.globl __imp__win32_select
__imp__win32_select:
  .long _win32_select
.globl __imp__win32_send
__imp__win32_send:
  .long _win32_send
