#include <windows.h>
#include "win32/win32.h"

/* __imp__win32_abort -> win32_abort */
void * __imp__win32_abort = (void*)win32_abort;
/* __imp__win32_access -> win32_access */
void * __imp__win32_access = (void*)win32_access;
/* __imp__win32_alarm -> win32_alarm */
void * __imp__win32_alarm = (void*)win32_alarm;
/* __imp__win32_ansipath -> win32_ansipath */
void * __imp__win32_ansipath = (void*)win32_ansipath;
/* __imp__win32_async_check -> win32_async_check */
void * __imp__win32_async_check = (void*)win32_async_check;
/* __imp__win32_calloc -> win32_calloc */
void * __imp__win32_calloc = (void*)win32_calloc;
/* __imp__win32_chdir -> win32_chdir */
void * __imp__win32_chdir = (void*)win32_chdir;
/* __imp__win32_chmod -> win32_chmod */
void * __imp__win32_chmod = (void*)win32_chmod;
/* __imp__win32_chsize -> win32_chsize */
void * __imp__win32_chsize = (void*)win32_chsize;
/* __imp__win32_clearenv -> win32_clearenv */
void * __imp__win32_clearenv = (void*)win32_clearenv;
/* __imp__win32_clearerr -> win32_clearerr */
void * __imp__win32_clearerr = (void*)win32_clearerr;
/* __imp__win32_close -> win32_close */
void * __imp__win32_close = (void*)win32_close;
/* __imp__win32_closedir -> win32_closedir */
void * __imp__win32_closedir = (void*)win32_closedir;
/* __imp__win32_create_message_window -> win32_create_message_window */
void * __imp__win32_create_message_window = (void*)win32_create_message_window;
/* __imp__win32_create_message_window_class -> win32_create_message_window_class */
void * __imp__win32_create_message_window_class = (void*)win32_create_message_window_class;
/* __imp__win32_croak_not_implemented -> win32_croak_not_implemented */
void * __imp__win32_croak_not_implemented = (void*)win32_croak_not_implemented;
/* __imp__win32_crypt -> win32_crypt */
void * __imp__win32_crypt = (void*)win32_crypt;
/* __imp__win32_ctrlhandler@4 -> win32_ctrlhandler@4 */
void * __imp__win32_ctrlhandler@4 = (void*)win32_ctrlhandler@4;
/* __imp__win32_delete_internal_host -> win32_delete_internal_host */
void * __imp__win32_delete_internal_host = (void*)win32_delete_internal_host;
/* __imp__win32_dirp_dup -> win32_dirp_dup */
void * __imp__win32_dirp_dup = (void*)win32_dirp_dup;
/* __imp__win32_dup -> win32_dup */
void * __imp__win32_dup = (void*)win32_dup;
/* __imp__win32_dup2 -> win32_dup2 */
void * __imp__win32_dup2 = (void*)win32_dup2;
/* __imp__win32_dynaload -> win32_dynaload */
void * __imp__win32_dynaload = (void*)win32_dynaload;
/* __imp__win32_environ -> win32_environ */
void * __imp__win32_environ = (void*)win32_environ;
/* __imp__win32_eof -> win32_eof */
void * __imp__win32_eof = (void*)win32_eof;
/* __imp__win32_errno -> win32_errno */
void * __imp__win32_errno = (void*)win32_errno;
/* __imp__win32_execv -> win32_execv */
void * __imp__win32_execv = (void*)win32_execv;
/* __imp__win32_execvp -> win32_execvp */
void * __imp__win32_execvp = (void*)win32_execvp;
/* __imp__win32_fclose -> win32_fclose */
void * __imp__win32_fclose = (void*)win32_fclose;
/* __imp__win32_fcloseall -> win32_fcloseall */
void * __imp__win32_fcloseall = (void*)win32_fcloseall;
/* __imp__win32_fdopen -> win32_fdopen */
void * __imp__win32_fdopen = (void*)win32_fdopen;
/* __imp__win32_fdupopen -> win32_fdupopen */
void * __imp__win32_fdupopen = (void*)win32_fdupopen;
/* __imp__win32_feof -> win32_feof */
void * __imp__win32_feof = (void*)win32_feof;
/* __imp__win32_ferror -> win32_ferror */
void * __imp__win32_ferror = (void*)win32_ferror;
/* __imp__win32_fflush -> win32_fflush */
void * __imp__win32_fflush = (void*)win32_fflush;
/* __imp__win32_fgetc -> win32_fgetc */
void * __imp__win32_fgetc = (void*)win32_fgetc;
/* __imp__win32_fgetpos -> win32_fgetpos */
void * __imp__win32_fgetpos = (void*)win32_fgetpos;
/* __imp__win32_fgets -> win32_fgets */
void * __imp__win32_fgets = (void*)win32_fgets;
/* __imp__win32_fileno -> win32_fileno */
void * __imp__win32_fileno = (void*)win32_fileno;
/* __imp__win32_flock -> win32_flock */
void * __imp__win32_flock = (void*)win32_flock;
/* __imp__win32_flushall -> win32_flushall */
void * __imp__win32_flushall = (void*)win32_flushall;
/* __imp__win32_fopen -> win32_fopen */
void * __imp__win32_fopen = (void*)win32_fopen;
/* __imp__win32_fprintf -> win32_fprintf */
void * __imp__win32_fprintf = (void*)win32_fprintf;
/* __imp__win32_fputc -> win32_fputc */
void * __imp__win32_fputc = (void*)win32_fputc;
/* __imp__win32_fputs -> win32_fputs */
void * __imp__win32_fputs = (void*)win32_fputs;
/* __imp__win32_fread -> win32_fread */
void * __imp__win32_fread = (void*)win32_fread;
/* __imp__win32_free -> win32_free */
void * __imp__win32_free = (void*)win32_free;
/* __imp__win32_free_childdir -> win32_free_childdir */
void * __imp__win32_free_childdir = (void*)win32_free_childdir;
/* __imp__win32_free_childenv -> win32_free_childenv */
void * __imp__win32_free_childenv = (void*)win32_free_childenv;
/* __imp__win32_freopen -> win32_freopen */
void * __imp__win32_freopen = (void*)win32_freopen;
/* __imp__win32_fseek -> win32_fseek */
void * __imp__win32_fseek = (void*)win32_fseek;
/* __imp__win32_fsetpos -> win32_fsetpos */
void * __imp__win32_fsetpos = (void*)win32_fsetpos;
/* __imp__win32_fstat -> win32_fstat */
void * __imp__win32_fstat = (void*)win32_fstat;
/* __imp__win32_ftell -> win32_ftell */
void * __imp__win32_ftell = (void*)win32_ftell;
/* __imp__win32_fwrite -> win32_fwrite */
void * __imp__win32_fwrite = (void*)win32_fwrite;
/* __imp__win32_get_child_IO -> win32_get_child_IO */
void * __imp__win32_get_child_IO = (void*)win32_get_child_IO;
/* __imp__win32_get_childdir -> win32_get_childdir */
void * __imp__win32_get_childdir = (void*)win32_get_childdir;
/* __imp__win32_get_childenv -> win32_get_childenv */
void * __imp__win32_get_childenv = (void*)win32_get_childenv;
/* __imp__win32_get_errno -> win32_get_errno */
void * __imp__win32_get_errno = (void*)win32_get_errno;
/* __imp__win32_get_osfhandle -> win32_get_osfhandle */
void * __imp__win32_get_osfhandle = (void*)win32_get_osfhandle;
/* __imp__win32_get_privlib -> win32_get_privlib */
void * __imp__win32_get_privlib = (void*)win32_get_privlib;
/* __imp__win32_get_sitelib -> win32_get_sitelib */
void * __imp__win32_get_sitelib = (void*)win32_get_sitelib;
/* __imp__win32_get_vendorlib -> win32_get_vendorlib */
void * __imp__win32_get_vendorlib = (void*)win32_get_vendorlib;
/* __imp__win32_getc -> win32_getc */
void * __imp__win32_getc = (void*)win32_getc;
/* __imp__win32_getchar -> win32_getchar */
void * __imp__win32_getchar = (void*)win32_getchar;
/* __imp__win32_getenv -> win32_getenv */
void * __imp__win32_getenv = (void*)win32_getenv;
/* __imp__win32_getenvironmentstrings -> win32_getenvironmentstrings */
void * __imp__win32_getenvironmentstrings = (void*)win32_getenvironmentstrings;
/* __imp__win32_getpid -> win32_getpid */
void * __imp__win32_getpid = (void*)win32_getpid;
/* __imp__win32_gets -> win32_gets */
void * __imp__win32_gets = (void*)win32_gets;
/* __imp__win32_gettimeofday -> win32_gettimeofday */
void * __imp__win32_gettimeofday = (void*)win32_gettimeofday;
/* __imp__win32_internal_wait -> win32_internal_wait */
void * __imp__win32_internal_wait = (void*)win32_internal_wait;
/* __imp__win32_isatty -> win32_isatty */
void * __imp__win32_isatty = (void*)win32_isatty;
/* __imp__win32_kill -> win32_kill */
void * __imp__win32_kill = (void*)win32_kill;
/* __imp__win32_link -> win32_link */
void * __imp__win32_link = (void*)win32_link;
/* __imp__win32_longpath -> win32_longpath */
void * __imp__win32_longpath = (void*)win32_longpath;
/* __imp__win32_lseek -> win32_lseek */
void * __imp__win32_lseek = (void*)win32_lseek;
/* __imp__win32_lstat -> win32_lstat */
void * __imp__win32_lstat = (void*)win32_lstat;
/* __imp__win32_malloc -> win32_malloc */
void * __imp__win32_malloc = (void*)win32_malloc;
/* __imp__win32_message_window_proc@16 -> win32_message_window_proc@16 */
void * __imp__win32_message_window_proc@16 = (void*)win32_message_window_proc@16;
/* __imp__win32_mkdir -> win32_mkdir */
void * __imp__win32_mkdir = (void*)win32_mkdir;
/* __imp__win32_msgwait -> win32_msgwait */
void * __imp__win32_msgwait = (void*)win32_msgwait;
/* __imp__win32_open -> win32_open */
void * __imp__win32_open = (void*)win32_open;
/* __imp__win32_open_osfhandle -> win32_open_osfhandle */
void * __imp__win32_open_osfhandle = (void*)win32_open_osfhandle;
/* __imp__win32_opendir -> win32_opendir */
void * __imp__win32_opendir = (void*)win32_opendir;
/* __imp__win32_os_id -> win32_os_id */
void * __imp__win32_os_id = (void*)win32_os_id;
/* __imp__win32_pause -> win32_pause */
void * __imp__win32_pause = (void*)win32_pause;
/* __imp__win32_pclose -> win32_pclose */
void * __imp__win32_pclose = (void*)win32_pclose;
/* __imp__win32_perror -> win32_perror */
void * __imp__win32_perror = (void*)win32_perror;
/* __imp__win32_pipe -> win32_pipe */
void * __imp__win32_pipe = (void*)win32_pipe;
/* __imp__win32_popen -> win32_popen */
void * __imp__win32_popen = (void*)win32_popen;
/* __imp__win32_popenlist -> win32_popenlist */
void * __imp__win32_popenlist = (void*)win32_popenlist;
/* __imp__win32_printf -> win32_printf */
void * __imp__win32_printf = (void*)win32_printf;
/* __imp__win32_putc -> win32_putc */
void * __imp__win32_putc = (void*)win32_putc;
/* __imp__win32_putchar -> win32_putchar */
void * __imp__win32_putchar = (void*)win32_putchar;
/* __imp__win32_putenv -> win32_putenv */
void * __imp__win32_putenv = (void*)win32_putenv;
/* __imp__win32_puts -> win32_puts */
void * __imp__win32_puts = (void*)win32_puts;
/* __imp__win32_read -> win32_read */
void * __imp__win32_read = (void*)win32_read;
/* __imp__win32_readdir -> win32_readdir */
void * __imp__win32_readdir = (void*)win32_readdir;
/* __imp__win32_readlink -> win32_readlink */
void * __imp__win32_readlink = (void*)win32_readlink;
/* __imp__win32_realloc -> win32_realloc */
void * __imp__win32_realloc = (void*)win32_realloc;
/* __imp__win32_rename -> win32_rename */
void * __imp__win32_rename = (void*)win32_rename;
/* __imp__win32_rewind -> win32_rewind */
void * __imp__win32_rewind = (void*)win32_rewind;
/* __imp__win32_rewinddir -> win32_rewinddir */
void * __imp__win32_rewinddir = (void*)win32_rewinddir;
/* __imp__win32_rmdir -> win32_rmdir */
void * __imp__win32_rmdir = (void*)win32_rmdir;
/* __imp__win32_seekdir -> win32_seekdir */
void * __imp__win32_seekdir = (void*)win32_seekdir;
/* __imp__win32_setbuf -> win32_setbuf */
void * __imp__win32_setbuf = (void*)win32_setbuf;
/* __imp__win32_setmode -> win32_setmode */
void * __imp__win32_setmode = (void*)win32_setmode;
/* __imp__win32_setvbuf -> win32_setvbuf */
void * __imp__win32_setvbuf = (void*)win32_setvbuf;
/* __imp__win32_signal -> win32_signal */
void * __imp__win32_signal = (void*)win32_signal;
/* __imp__win32_signal_context -> win32_signal_context */
void * __imp__win32_signal_context = (void*)win32_signal_context;
/* __imp__win32_sleep -> win32_sleep */
void * __imp__win32_sleep = (void*)win32_sleep;
/* __imp__win32_spawnvp -> win32_spawnvp */
void * __imp__win32_spawnvp = (void*)win32_spawnvp;
/* __imp__win32_stat -> win32_stat */
void * __imp__win32_stat = (void*)win32_stat;
/* __imp__win32_stderr -> win32_stderr */
void * __imp__win32_stderr = (void*)win32_stderr;
/* __imp__win32_stdin -> win32_stdin */
void * __imp__win32_stdin = (void*)win32_stdin;
/* __imp__win32_stdout -> win32_stdout */
void * __imp__win32_stdout = (void*)win32_stdout;
/* __imp__win32_str_os_error -> win32_str_os_error */
void * __imp__win32_str_os_error = (void*)win32_str_os_error;
/* __imp__win32_strerror -> win32_strerror */
void * __imp__win32_strerror = (void*)win32_strerror;
/* __imp__win32_symlink -> win32_symlink */
void * __imp__win32_symlink = (void*)win32_symlink;
/* __imp__win32_tell -> win32_tell */
void * __imp__win32_tell = (void*)win32_tell;
/* __imp__win32_telldir -> win32_telldir */
void * __imp__win32_telldir = (void*)win32_telldir;
/* __imp__win32_times -> win32_times */
void * __imp__win32_times = (void*)win32_times;
/* __imp__win32_tmpfd -> win32_tmpfd */
void * __imp__win32_tmpfd = (void*)win32_tmpfd;
/* __imp__win32_tmpfd_mode -> win32_tmpfd_mode */
void * __imp__win32_tmpfd_mode = (void*)win32_tmpfd_mode;
/* __imp__win32_tmpfile -> win32_tmpfile */
void * __imp__win32_tmpfile = (void*)win32_tmpfile;
/* __imp__win32_uname -> win32_uname */
void * __imp__win32_uname = (void*)win32_uname;
/* __imp__win32_ungetc -> win32_ungetc */
void * __imp__win32_ungetc = (void*)win32_ungetc;
/* __imp__win32_unlink -> win32_unlink */
void * __imp__win32_unlink = (void*)win32_unlink;
/* __imp__win32_utime -> win32_utime */
void * __imp__win32_utime = (void*)win32_utime;
/* __imp__win32_vfprintf -> win32_vfprintf */
void * __imp__win32_vfprintf = (void*)win32_vfprintf;
/* __imp__win32_vprintf -> win32_vprintf */
void * __imp__win32_vprintf = (void*)win32_vprintf;
/* __imp__win32_wait -> win32_wait */
void * __imp__win32_wait = (void*)win32_wait;
/* __imp__win32_waitpid -> win32_waitpid */
void * __imp__win32_waitpid = (void*)win32_waitpid;
/* __imp__win32_write -> win32_write */
void * __imp__win32_write = (void*)win32_write;
