/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe bin\enc2xs -Q -O -o def_t.c -f def_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t ascii_encoding;
extern encode_t ascii_ctrl_encoding;
extern encode_t cp1252_encoding;
extern encode_t iso_8859_1_encoding;
extern encode_t null_encoding;
