/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -o ji_03_t.c -f ji_03_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t jis0208_raw_encoding;
