/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 D:\perl-xp\perl-5.40.3\miniperl.exe ..\bin\enc2xs -Q -O -o symbol_t.c -f symbol_t.fnm
 enc2xs VERSION 2.25
*/
extern encode_t AdobeSymbol_encoding;
extern encode_t AdobeZdingbat_encoding;
extern encode_t MacDingbats_encoding;
extern encode_t MacSymbol_encoding;
extern encode_t dingbats_encoding;
extern encode_t symbol_encoding;
